function angle_ranking_alpha_compare
% angle_ranking_alpha_compare
% MATLAB R2015-compatible helper that combines angle-ranking data across
% alpha values (and, if present, across different source types).
%
% Preferred input:
%   - angle_ranking_*_vs_*.csv files generated by penelope_report_dose_analysis
%
% Fallback input:
%   - *_Dose.xlsx / *_Dose.xls files with the standard "Dose" worksheet
%
% Outputs:
%   - combined long-form CSV
%   - combined wide/matrix CSV
%   - series-summary CSV
%   - raw ratio comparison plots ranked by selected reference alpha
%   - target-dose line plots using ranked and pair-order views

close all;
clc;
disp(['Running angle_ranking_alpha_compare from: ' mfilename('fullpath')]);

%% ---------------- USER PARAMETERS ----------------
rootDir = fileparts(mfilename('fullpath'));
if isempty(rootDir) || ~exist(rootDir, 'dir')
    rootDir = pwd;
end

% 'auto' prefers existing ranking CSVs. Use 'xlsx' to force workbook mode.
inputMode = 'auto';   % 'auto' | 'csv' | 'xlsx'

% Normalization applied independently to each alpha/source series.
% 'max' : 100 * value / max(series)
% 'sum' : 100 * value / sum(series)
% 'none': keep raw CompareTarget_pct values
normalizationMode = 'max';   % 'max' | 'sum' | 'none'
normalizedScale = 100;
targetDosePlotLogScale = false;
rawRatioReferenceAlphaAll = 2.86;
rawRatioSubsetReferenceAlpha = 1.0;
rawRatioSubsetAlphas = [0.49 1.0];

% Workbook mode only. Leave empty to ask interactively if needed.
compareBodyName = '';
targetBodyName = '';

% Leave empty to save next to the selected data root.
outDir = '';

grau = char(176);

[csvFiles, workbookFiles] = discover_input_files_r2015(rootDir);
if isempty(csvFiles) && isempty(workbookFiles)
    chosenRoot = uigetdir(rootDir, 'Select folder with angle-ranking CSVs or Dose workbooks');
    if isequal(chosenRoot, 0)
        disp('No input folder selected. Exiting angle_ranking_alpha_compare.');
        return;
    end
    rootDir = chosenRoot;
    [csvFiles, workbookFiles] = discover_input_files_r2015(rootDir);
end

if isempty(csvFiles) && isempty(workbookFiles)
    disp('No angle-ranking CSV files or Dose workbooks were found.');
    return;
end

if isempty(outDir)
    outDir = rootDir;
end
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

modeToUse = resolve_input_mode_r2015(inputMode, csvFiles, workbookFiles);
if isempty(modeToUse)
    disp('No usable input mode is available. Exiting.');
    return;
end

groups = struct('token', {}, 'compareLabel', {}, 'targetLabel', {}, 'rows', {});
if strcmp(modeToUse, 'csv')
    groups = load_ranking_groups_from_csv_r2015(csvFiles);
else
    if isempty(compareBodyName) || isempty(targetBodyName)
        defaults = {'Olho direito', 'Tumor olho dto'};
        if ~isempty(compareBodyName)
            defaults{1} = compareBodyName;
        end
        if ~isempty(targetBodyName)
            defaults{2} = targetBodyName;
        end
        answers = inputdlg({'Compare BODY label', 'Target BODY label'}, ...
            'Angle ranking from Dose workbook', 1, defaults);
        if isempty(answers)
            disp('Workbook compare/target labels were not provided. Exiting.');
            return;
        end
        compareBodyName = strtrim(answers{1});
        targetBodyName = strtrim(answers{2});
    end
    groups = load_ranking_groups_from_workbooks_r2015(workbookFiles, compareBodyName, targetBodyName);
end

if isempty(groups)
    disp('No usable angle-ranking rows were loaded.');
    return;
end

processedGroups = 0;
for g = 1:numel(groups)
    try
        process_ranking_group_r2015(groups(g), outDir, normalizationMode, normalizedScale, targetDosePlotLogScale, grau, ...
            rawRatioReferenceAlphaAll, rawRatioSubsetReferenceAlpha, rawRatioSubsetAlphas);
        processedGroups = processedGroups + 1;
        disp(['Processed combined ranking: ' groups(g).compareLabel ' vs ' groups(g).targetLabel]);
    catch ME
        disp(['Failed combined ranking ', groups(g).token, ': ' ME.message]);
    end
end

disp(['Processed ranking groups: ' num2str(processedGroups)]);
end

function [csvFiles, workbookFiles] = discover_input_files_r2015(rootDir)
csvFiles = collect_matching_files_recursive_r2015(rootDir, 'csv');
workbookFiles = collect_matching_files_recursive_r2015(rootDir, 'xlsx');
end

function files = collect_matching_files_recursive_r2015(rootDir, modeName)
files = {};
if nargin < 2 || isempty(rootDir) || ~exist(rootDir, 'dir')
    return;
end

listing = dir(rootDir);
for i = 1:numel(listing)
    item = listing(i);
    itemName = item.name;
    if strcmp(itemName, '.') || strcmp(itemName, '..')
        continue;
    end
    fullPath = fullfile(rootDir, itemName);
    if item.isdir
        nested = collect_matching_files_recursive_r2015(fullPath, modeName);
        if ~isempty(nested)
            files = [files; nested]; %#ok<AGROW>
        end
        continue;
    end

    switch lower(modeName)
        case 'csv'
            if ~isempty(regexp(itemName, '^angle_ranking_.+_vs_.+\.csv$', 'once'))
                files{end + 1, 1} = fullPath; %#ok<AGROW>
            end
        case 'xlsx'
            lowerName = lower(itemName);
            if ~isempty(regexp(lowerName, '_dose\.xlsx$', 'once')) || ~isempty(regexp(lowerName, '_dose\.xls$', 'once'))
                files{end + 1, 1} = fullPath; %#ok<AGROW>
            end
    end
end
end

function modeToUse = resolve_input_mode_r2015(inputMode, csvFiles, workbookFiles)
modeToUse = '';
requested = lower(strtrim(inputMode));
switch requested
    case 'csv'
        if ~isempty(csvFiles)
            modeToUse = 'csv';
        end
    case 'xlsx'
        if ~isempty(workbookFiles)
            modeToUse = 'xlsx';
        end
    otherwise
        if ~isempty(csvFiles)
            modeToUse = 'csv';
        elseif ~isempty(workbookFiles)
            modeToUse = 'xlsx';
        end
end
end

function groups = load_ranking_groups_from_csv_r2015(csvFiles)
groups = struct('token', {}, 'compareLabel', {}, 'targetLabel', {}, 'rows', {});
for i = 1:numel(csvFiles)
    [compareToken, targetToken] = parse_ranking_group_tokens_r2015(csvFiles{i});
    if isempty(compareToken) || isempty(targetToken)
        continue;
    end
    token = [compareToken '_vs_' targetToken];
    T = load_ranking_csv_r2015(csvFiles{i});
    if height(T) == 0
        continue;
    end
    idx = find(strcmp({groups.token}, token), 1);
    if isempty(idx)
        idx = numel(groups) + 1;
        groups(idx).token = token; %#ok<AGROW>
        groups(idx).compareLabel = display_label_from_token_r2015(compareToken); %#ok<AGROW>
        groups(idx).targetLabel = display_label_from_token_r2015(targetToken); %#ok<AGROW>
        groups(idx).rows = T; %#ok<AGROW>
    else
        groups(idx).rows = [groups(idx).rows; T];
    end
end
end

function groups = load_ranking_groups_from_workbooks_r2015(workbookFiles, compareBodyName, targetBodyName)
groups = struct('token', {}, 'compareLabel', {}, 'targetLabel', {}, 'rows', {});
compareLabel = strtrim(compareBodyName);
targetLabel = strtrim(targetBodyName);
if isempty(compareLabel) || isempty(targetLabel)
    return;
end

token = [safe_label_file_token_r2015(compareLabel) '_vs_' safe_label_file_token_r2015(targetLabel)];
rows = table();
for i = 1:numel(workbookFiles)
    T = build_ranking_table_from_workbook_r2015(workbookFiles{i}, compareLabel, targetLabel);
    if height(T) == 0
        continue;
    end
    if isempty(rows)
        rows = T;
    else
        rows = [rows; T];
    end
end

if isempty(rows)
    return;
end
groups(1).token = token;
groups(1).compareLabel = compareLabel;
groups(1).targetLabel = targetLabel;
groups(1).rows = rows;
end

function process_ranking_group_r2015(group, outDir, normalizationMode, normalizedScale, targetDosePlotLogScale, grau, rawRatioReferenceAlphaAll, rawRatioSubsetReferenceAlpha, rawRatioSubsetAlphas)
T = group.rows;
if isempty(T) || height(T) == 0
    return;
end

validMask = isfinite(T.Alpha) & isfinite(T.THETA) & isfinite(T.PHI) & isfinite(T.CompareTarget_pct);
T = T(validMask, :);
if isempty(T) || height(T) == 0
    error('No valid rows remained after filtering THETA/PHI/Alpha/ratio values.');
end

T.SourceType = fill_empty_labels_r2015(T.SourceType, 'Unknown source');

seriesMeta = build_series_metadata_r2015(T.SourceType, T.Alpha, grau);
pairMeta = build_pair_metadata_r2015(T.THETA, T.PHI);
if isempty(seriesMeta.keys) || isempty(pairMeta.labels)
    error('Could not build series or angle-pair metadata.');
end

[rawMatrix, rawErrMatrix, targetDoseMatrix, compareDoseMatrix, countMatrix] = ...
    build_series_matrices_r2015(T, seriesMeta, pairMeta);

[rawAvailableCount, rawMean, rawMax] = compute_target_statistics_r2015(rawMatrix); %#ok<ASGLU>
[normMatrix, normErrMatrix, seriesDenominator] = ...
    normalize_series_matrix_r2015(rawMatrix, rawErrMatrix, normalizationMode, normalizedScale);

[availableCount, normMean, normRange, normStd] = compute_pair_statistics_r2015(normMatrix);
pairOrder = sort_pair_order_r2015(normRange, normMean, pairMeta.theta, pairMeta.phi);

pairMeta.theta = pairMeta.theta(pairOrder);
pairMeta.phi = pairMeta.phi(pairOrder);
pairMeta.labels = pairMeta.labels(pairOrder);
pairMeta.keys = pairMeta.keys(pairOrder);
rawMatrix = rawMatrix(pairOrder, :);
rawErrMatrix = rawErrMatrix(pairOrder, :);
targetDoseMatrix = targetDoseMatrix(pairOrder, :);
compareDoseMatrix = compareDoseMatrix(pairOrder, :);
countMatrix = countMatrix(pairOrder, :);
normMatrix = normMatrix(pairOrder, :);
normErrMatrix = normErrMatrix(pairOrder, :);
availableCount = availableCount(pairOrder);
normMean = normMean(pairOrder);
normRange = normRange(pairOrder);
normStd = normStd(pairOrder);

baseName = ['combined_angle_ranking_' group.token];

longTable = build_long_output_table_r2015(group, pairMeta, seriesMeta, rawMatrix, rawErrMatrix, ...
    targetDoseMatrix, compareDoseMatrix, normMatrix, normErrMatrix, countMatrix, seriesDenominator);
matrixTable = build_matrix_output_table_r2015(pairMeta, seriesMeta, rawMatrix, rawErrMatrix, ...
    targetDoseMatrix, compareDoseMatrix, normMatrix, normErrMatrix, countMatrix, ...
    availableCount, normMean, normRange, normStd);
summaryTable = build_series_summary_table_r2015(seriesMeta, rawMatrix, countMatrix, seriesDenominator);

writetable(longTable, fullfile(outDir, [baseName '_long.csv']));
writetable(matrixTable, fullfile(outDir, [baseName '_matrix.csv']));
writetable(summaryTable, fullfile(outDir, [baseName '_series_summary.csv']));

[targetAvailableCount, targetMean, targetMax] = compute_target_statistics_r2015(targetDoseMatrix);
targetPairOrder = sort_target_pair_order_r2015(targetMean, targetMax, pairMeta.theta, pairMeta.phi);
targetPairMeta = pairMeta;
targetPairMeta.theta = targetPairMeta.theta(targetPairOrder);
targetPairMeta.phi = targetPairMeta.phi(targetPairOrder);
targetPairMeta.labels = targetPairMeta.labels(targetPairOrder);
targetPairMeta.keys = targetPairMeta.keys(targetPairOrder);
targetDoseRankMatrix = targetDoseMatrix(targetPairOrder, :);
targetCountRankMatrix = countMatrix(targetPairOrder, :);
targetAvailableCount = targetAvailableCount(targetPairOrder);
targetMean = targetMean(targetPairOrder);
targetMax = targetMax(targetPairOrder);
targetRankTable = build_target_rank_table_r2015(targetPairMeta, seriesMeta, targetDoseRankMatrix, targetCountRankMatrix, targetAvailableCount, targetMean, targetMax);
writetable(targetRankTable, fullfile(outDir, [baseName '_target_dose_ranked.csv']));

refAllIdx = find_reference_series_index_by_alpha_r2015(seriesMeta, rawRatioReferenceAlphaAll);
if isempty(refAllIdx)
    refAllIdx = find_first_finite_series_index_r2015(rawMatrix);
    if ~isempty(refAllIdx)
        disp(['Requested reference alpha ', num2str(rawRatioReferenceAlphaAll), ' was not found for ', group.token, '. Using ', seriesMeta.labels{refAllIdx}, ' instead.']);
    end
end

subsetSeriesIdx = find_series_indices_by_alpha_r2015(seriesMeta, rawRatioSubsetAlphas);
subsetRefIdx = find_reference_series_index_by_alpha_r2015(seriesMeta, rawRatioSubsetReferenceAlpha);
plotTitles = resolve_plot_titles_r2015(group, seriesMeta, refAllIdx, subsetRefIdx, rawRatioSubsetAlphas, grau);

ratioOrderAll = [];
ratioAllPairMeta = pairMeta;
if ~isempty(refAllIdx)
    ratioOrderAll = sort_pair_order_by_reference_alpha_r2015(rawMatrix, refAllIdx, rawMean, pairMeta.theta, pairMeta.phi);
    ratioAllPairMeta = reorder_pair_metadata_r2015(pairMeta, ratioOrderAll);
    rawMatrixAllOrdered = rawMatrix(ratioOrderAll, :);
    rawErrMatrixAllOrdered = rawErrMatrix(ratioOrderAll, :);

    try
        plot_raw_ratio_horizontal_dots_r2015(group, ratioAllPairMeta.labels, seriesMeta.labels, rawMatrixAllOrdered, rawErrMatrixAllOrdered, ...
            1:numel(seriesMeta.labels), outDir, [baseName '_raw_ratio_ref_' alpha_token_r2015(seriesMeta.alphas(refAllIdx))], plotTitles.ratioAllTitle);
    catch ME
        error('All-alpha raw ratio plot failed: %s', ME.message);
    end
else
    disp(['No finite raw-ratio series were available for ', group.token, '. Skipping all-series raw ratio plot.']);
end

if numel(subsetSeriesIdx) >= 2 && ~isempty(subsetRefIdx)
    ratioOrderSubset = sort_pair_order_by_reference_alpha_r2015(rawMatrix, subsetRefIdx, rawMean, pairMeta.theta, pairMeta.phi);
    ratioSubsetPairMeta = reorder_pair_metadata_r2015(pairMeta, ratioOrderSubset);
    rawMatrixSubsetOrdered = rawMatrix(ratioOrderSubset, :);
    rawErrMatrixSubsetOrdered = rawErrMatrix(ratioOrderSubset, :);

    try
        plot_raw_ratio_horizontal_dots_r2015(group, ratioSubsetPairMeta.labels, seriesMeta.labels, rawMatrixSubsetOrdered, rawErrMatrixSubsetOrdered, ...
            subsetSeriesIdx, outDir, [baseName '_raw_ratio_subset_ref_' alpha_token_r2015(seriesMeta.alphas(subsetRefIdx))], plotTitles.ratioSubsetTitle);
    catch ME
        error('Subset raw ratio plot failed: %s', ME.message);
    end
else
    disp(['Skipping subset raw-ratio plot for ', group.token, ' because alpha 1 and alpha 0.49 were not both available.']);
end

try
    plot_target_dose_ranked_lines_r2015(group, targetPairMeta.labels, seriesMeta.labels, targetDoseRankMatrix, targetDosePlotLogScale, outDir, ...
        [baseName '_target_dose_ranked_desc'], plotTitles.doseRankedTitle, 'Theta/Phi pair');
catch ME
    error('Target-dose descending plot failed: %s', ME.message);
end

if ~isempty(ratioOrderAll)
    targetDoseRatioOrdered = targetDoseMatrix(ratioOrderAll, :);
    try
        plot_target_dose_ranked_lines_r2015(group, ratioAllPairMeta.labels, seriesMeta.labels, targetDoseRatioOrdered, targetDosePlotLogScale, outDir, ...
            [baseName '_target_dose_ratio_order_ref_' alpha_token_r2015(seriesMeta.alphas(refAllIdx))], plotTitles.doseRatioOrderTitle, 'Theta/Phi pair');
    catch ME
        error('Target-dose ratio-order plot failed: %s', ME.message);
    end
end

try
    plot_ratio_vs_target_dose_scatter_r2015(group, seriesMeta, rawMatrix, targetDoseMatrix, outDir, [baseName '_ratio_vs_target_dose_scatter'], plotTitles.scatterTitle);
catch ME
    error('Ratio-vs-dose scatter plot failed: %s', ME.message);
end

screeningTable = build_screening_table_r2015(pairMeta, seriesMeta, rawMatrix, targetDoseMatrix, ratioOrderAll, targetPairOrder, subsetSeriesIdx, subsetRefIdx);
writetable(screeningTable, fullfile(outDir, [baseName '_screening_table.csv']));
end

function T = load_ranking_csv_r2015(csvPath)
T = table();
try
    rawTable = readtable(csvPath, 'Delimiter', ',');
catch
    rawTable = readtable(csvPath);
end
if isempty(rawTable) || height(rawTable) == 0
    return;
end

caseVar = find_table_var_name_r2015(rawTable, {'Case'});
sourceVar = find_optional_table_var_name_r2015(rawTable, {'SourceType', 'Source_Type', 'Source'});
caseIdVar = find_optional_table_var_name_r2015(rawTable, {'CaseID', 'Case_ID'});
alphaVar = find_table_var_name_r2015(rawTable, {'Alpha'});
thetaVar = find_table_var_name_r2015(rawTable, {'THETA', 'Theta'});
phiVar = find_table_var_name_r2015(rawTable, {'PHI', 'Phi'});
targetDoseVar = find_optional_table_var_name_r2015(rawTable, {'TargetDose_eVg'});
dTargetDoseVar = find_optional_table_var_name_r2015(rawTable, {'dTargetDose_eVg'});
compareDoseVar = find_optional_table_var_name_r2015(rawTable, {'CompareDose_eVg'});
dCompareDoseVar = find_optional_table_var_name_r2015(rawTable, {'dCompareDose_eVg'});
ratioVar = find_table_var_name_r2015(rawTable, {'CompareTarget_pct'});
dRatioVar = find_optional_table_var_name_r2015(rawTable, {'dCompareTarget_pct'});

caseNames = table_column_to_strings_r2015(rawTable, caseVar);
sourceTypes = table_column_to_strings_r2015(rawTable, sourceVar);
sourceTypes = fill_empty_labels_r2015(sourceTypes, 'Unknown source');
for i = 1:numel(sourceTypes)
    sourceTypes{i} = normalize_source_type_label_r2015(sourceTypes{i});
end

T = table( ...
    caseNames, ...
    sourceTypes, ...
    table_column_to_numeric_r2015(rawTable, caseIdVar), ...
    table_column_to_numeric_r2015(rawTable, alphaVar), ...
    table_column_to_numeric_r2015(rawTable, thetaVar), ...
    table_column_to_numeric_r2015(rawTable, phiVar), ...
    table_column_to_numeric_r2015(rawTable, targetDoseVar), ...
    table_column_to_numeric_r2015(rawTable, dTargetDoseVar), ...
    table_column_to_numeric_r2015(rawTable, compareDoseVar), ...
    table_column_to_numeric_r2015(rawTable, dCompareDoseVar), ...
    table_column_to_numeric_r2015(rawTable, ratioVar), ...
    table_column_to_numeric_r2015(rawTable, dRatioVar), ...
    repmat({csvPath}, height(rawTable), 1), ...
    'VariableNames', { ...
        'Case', 'SourceType', 'CaseID', 'Alpha', 'THETA', 'PHI', ...
        'TargetDose_eVg', 'dTargetDose_eVg', 'CompareDose_eVg', 'dCompareDose_eVg', ...
        'CompareTarget_pct', 'dCompareTarget_pct', 'InputFile' ...
    });
end

function T = build_ranking_table_from_workbook_r2015(excelPath, compareName, targetName)
doseData = load_dose_sheet_r2015(excelPath);
T = table();
if isempty(doseData.case_names)
    return;
end

n = numel(doseData.case_names);
THETA = nan(n, 1);
PHI = nan(n, 1);
ALPHA = nan(n, 1);
CASEID = nan(n, 1);
for i = 1:n
    c = doseData.case_names{i};
    tok = regexp(c, 'SCONE-([\-0-9\.]+)_([\-0-9\.]+)_([\-0-9\.]+)', 'tokens', 'once');
    if ~isempty(tok)
        THETA(i) = str2double(tok{1});
        PHI(i) = str2double(tok{2});
        ALPHA(i) = str2double(tok{3});
    end
    tok2 = regexp(c, 'case(\d+)', 'tokens', 'once');
    if ~isempty(tok2)
        CASEID(i) = str2double(tok2{1});
    end
end

validMask = ~isnan(ALPHA);
caseNames = doseData.case_names(validMask);
sourceTypes = doseData.source_types(validMask);
sourceTypes = fill_empty_labels_r2015(sourceTypes, 'Unknown source');
componentNames = doseData.component_names(validMask);
doseEvg = doseData.dose_evg(validMask);
dDoseEvg = doseData.ddose_evg(validMask);
THETA = THETA(validMask);
PHI = PHI(validMask);
ALPHA = ALPHA(validMask);
CASEID = CASEID(validMask);

cases = unique(caseNames);
rankCase = {};
rankSourceType = {};
rankCaseID = [];
rankAlpha = [];
rankTheta = [];
rankPhi = [];
rankTargetDose = [];
rankdTargetDose = [];
rankCompareDose = [];
rankdCompareDose = [];
rankComparePct = [];
rankdComparePct = [];
rankInputFile = {};
rowCount = 0;

for i = 1:numel(cases)
    caseMask = strcmp(caseNames, cases{i});
    caseRows = find(caseMask);
    if isempty(caseRows)
        continue;
    end

    localComponents = componentNames(caseRows);
    targetLocalMask = build_component_match_mask_r2015(localComponents, {targetName});
    compareLocalMask = build_component_match_mask_r2015(localComponents, {compareName});
    targetLocalIdx = find(targetLocalMask, 1, 'first');
    compareLocalIdx = find(compareLocalMask, 1, 'first');
    if isempty(targetLocalIdx) || isempty(compareLocalIdx)
        continue;
    end

    targetIdx = caseRows(targetLocalIdx);
    compareIdx = caseRows(compareLocalIdx);
    targetDose = doseEvg(targetIdx);
    dTargetDose = dDoseEvg(targetIdx);
    compareDose = doseEvg(compareIdx);
    dCompareDose = dDoseEvg(compareIdx);
    [ratioPct, dRatioPct] = safe_ratio_pct_r2015(compareDose, dCompareDose, targetDose, dTargetDose);
    if ~isfinite(ratioPct)
        continue;
    end

    rowCount = rowCount + 1;
    rankCase{rowCount, 1} = cases{i}; %#ok<AGROW>
    rankSourceType{rowCount, 1} = normalize_source_type_label_r2015(sourceTypes{targetIdx}); %#ok<AGROW>
    rankCaseID(rowCount, 1) = CASEID(targetIdx); %#ok<AGROW>
    rankAlpha(rowCount, 1) = ALPHA(targetIdx); %#ok<AGROW>
    rankTheta(rowCount, 1) = THETA(targetIdx); %#ok<AGROW>
    rankPhi(rowCount, 1) = PHI(targetIdx); %#ok<AGROW>
    rankTargetDose(rowCount, 1) = targetDose; %#ok<AGROW>
    rankdTargetDose(rowCount, 1) = dTargetDose; %#ok<AGROW>
    rankCompareDose(rowCount, 1) = compareDose; %#ok<AGROW>
    rankdCompareDose(rowCount, 1) = dCompareDose; %#ok<AGROW>
    rankComparePct(rowCount, 1) = ratioPct; %#ok<AGROW>
    rankdComparePct(rowCount, 1) = dRatioPct; %#ok<AGROW>
    rankInputFile{rowCount, 1} = excelPath; %#ok<AGROW>
end

if rowCount == 0
    return;
end

T = table( ...
    rankCase, rankSourceType, rankCaseID, rankAlpha, rankTheta, rankPhi, ...
    rankTargetDose, rankdTargetDose, rankCompareDose, rankdCompareDose, rankComparePct, rankdComparePct, rankInputFile, ...
    'VariableNames', { ...
        'Case', 'SourceType', 'CaseID', 'Alpha', 'THETA', 'PHI', ...
        'TargetDose_eVg', 'dTargetDose_eVg', 'CompareDose_eVg', 'dCompareDose_eVg', ...
        'CompareTarget_pct', 'dCompareTarget_pct', 'InputFile' ...
    });
end

function seriesMeta = build_series_metadata_r2015(sourceTypes, alphaValues, grau)
seriesMeta = struct();
seriesMeta.keys = {};
seriesMeta.labels = {};
seriesMeta.tokens = {};
seriesMeta.sourceTypes = {};
seriesMeta.alphas = [];

sourceTypes = fill_empty_labels_r2015(sourceTypes, 'Unknown source');
for i = 1:numel(sourceTypes)
    sourceTypes{i} = normalize_source_type_label_r2015(sourceTypes{i});
end
uniqueSources = unique(sourceTypes);
showSourceInLegend = numel(uniqueSources) > 1;

for i = 1:numel(alphaValues)
    currentSource = sourceTypes{i};
    currentAlpha = alphaValues(i);
    currentKey = build_series_key_r2015(currentSource, currentAlpha);
    if isempty(find(strcmp(seriesMeta.keys, currentKey), 1))
        seriesMeta.keys{end + 1, 1} = currentKey; %#ok<AGROW>
        seriesMeta.sourceTypes{end + 1, 1} = currentSource; %#ok<AGROW>
        seriesMeta.alphas(end + 1, 1) = currentAlpha; %#ok<AGROW>
        if showSourceInLegend
            seriesMeta.labels{end + 1, 1} = sprintf('%s | alpha = %.4g%c', display_source_type_r2015(currentSource), currentAlpha, grau); %#ok<AGROW>
            seriesMeta.tokens{end + 1, 1} = [safe_file_token_r2015(currentSource) '_alpha_' alpha_token_r2015(currentAlpha)]; %#ok<AGROW>
        else
            seriesMeta.labels{end + 1, 1} = sprintf('alpha = %.4g%c', currentAlpha, grau); %#ok<AGROW>
            seriesMeta.tokens{end + 1, 1} = ['alpha_' alpha_token_r2015(currentAlpha)]; %#ok<AGROW>
        end
    end
end

seriesMeta = sort_series_metadata_r2015(seriesMeta);
end

function seriesMeta = sort_series_metadata_r2015(seriesMeta)
if isempty(seriesMeta.keys)
    return;
end

sortKeys = seriesMeta.tokens;
T = table(sortKeys, seriesMeta.labels, seriesMeta.tokens, seriesMeta.sourceTypes, seriesMeta.alphas, seriesMeta.keys, ...
    'VariableNames', {'SortKey', 'Label', 'Token', 'SourceType', 'Alpha', 'Key'});
T = sortrows(T, {'SortKey'});

seriesMeta.keys = T.Key;
seriesMeta.labels = T.Label;
seriesMeta.tokens = T.Token;
seriesMeta.sourceTypes = T.SourceType;
seriesMeta.alphas = T.Alpha;
end

function pairMeta = build_pair_metadata_r2015(thetaValues, phiValues)
pairMeta = struct();
pairMeta.keys = {};
pairMeta.labels = {};
pairMeta.theta = [];
pairMeta.phi = [];

for i = 1:numel(thetaValues)
    currentTheta = thetaValues(i);
    currentPhi = phiValues(i);
    currentKey = build_pair_key_r2015(currentTheta, currentPhi);
    if isempty(find(strcmp(pairMeta.keys, currentKey), 1))
        pairMeta.keys{end + 1, 1} = currentKey; %#ok<AGROW>
        pairMeta.theta(end + 1, 1) = currentTheta; %#ok<AGROW>
        pairMeta.phi(end + 1, 1) = currentPhi; %#ok<AGROW>
        pairMeta.labels{end + 1, 1} = sprintf('T%.0f P%.0f', currentTheta, currentPhi); %#ok<AGROW>
    end
end
end

function [rawMatrix, rawErrMatrix, targetDoseMatrix, compareDoseMatrix, countMatrix] = build_series_matrices_r2015(T, seriesMeta, pairMeta)
nPairs = numel(pairMeta.keys);
nSeries = numel(seriesMeta.keys);
rawMatrix = nan(nPairs, nSeries);
rawErrMatrix = nan(nPairs, nSeries);
targetDoseMatrix = nan(nPairs, nSeries);
compareDoseMatrix = nan(nPairs, nSeries);
countMatrix = zeros(nPairs, nSeries);

rowSeriesKeys = cell(height(T), 1);
rowPairKeys = cell(height(T), 1);
for i = 1:height(T)
    rowSeriesKeys{i} = build_series_key_r2015(T.SourceType{i}, T.Alpha(i));
    rowPairKeys{i} = build_pair_key_r2015(T.THETA(i), T.PHI(i));
end

for p = 1:nPairs
    for s = 1:nSeries
        matchMask = strcmp(rowPairKeys, pairMeta.keys{p}) & strcmp(rowSeriesKeys, seriesMeta.keys{s});
        if ~any(matchMask)
            continue;
        end
        rawVals = T.CompareTarget_pct(matchMask);
        rawVals = rawVals(isfinite(rawVals));
        if isempty(rawVals)
            continue;
        end
        rawMatrix(p, s) = mean(rawVals);

        rawErrVals = T.dCompareTarget_pct(matchMask);
        rawErrVals = rawErrVals(isfinite(rawErrVals));
        if ~isempty(rawErrVals)
            rawErrMatrix(p, s) = mean(rawErrVals);
        end

        targetVals = T.TargetDose_eVg(matchMask);
        targetVals = targetVals(isfinite(targetVals));
        if ~isempty(targetVals)
            targetDoseMatrix(p, s) = mean(targetVals);
        end

        compareVals = T.CompareDose_eVg(matchMask);
        compareVals = compareVals(isfinite(compareVals));
        if ~isempty(compareVals)
            compareDoseMatrix(p, s) = mean(compareVals);
        end

        countMatrix(p, s) = sum(matchMask);
    end
end
end

function [normMatrix, normErrMatrix, denominators] = normalize_series_matrix_r2015(rawMatrix, rawErrMatrix, normalizationMode, normalizedScale)
normMatrix = nan(size(rawMatrix));
normErrMatrix = nan(size(rawErrMatrix));
denominators = nan(1, size(rawMatrix, 2));
modeName = lower(strtrim(normalizationMode));

for s = 1:size(rawMatrix, 2)
    currentVals = rawMatrix(:, s);
    finiteMask = isfinite(currentVals);
    if ~any(finiteMask)
        continue;
    end

    switch modeName
        case 'sum'
            denom = sum(currentVals(finiteMask));
        case 'none'
            denom = 1;
        otherwise
            denom = max(currentVals(finiteMask));
    end

    if ~isfinite(denom) || denom == 0
        continue;
    end
    denominators(s) = denom;
    normMatrix(:, s) = normalizedScale * rawMatrix(:, s) / denom;
    normErrMatrix(:, s) = normalizedScale * rawErrMatrix(:, s) / denom;
end
end

function [availableCount, normMean, normRange, normStd] = compute_pair_statistics_r2015(normMatrix)
nPairs = size(normMatrix, 1);
availableCount = zeros(nPairs, 1);
normMean = nan(nPairs, 1);
normRange = nan(nPairs, 1);
normStd = nan(nPairs, 1);

for i = 1:nPairs
    currentVals = normMatrix(i, :);
    currentVals = currentVals(isfinite(currentVals));
    availableCount(i) = numel(currentVals);
    if isempty(currentVals)
        continue;
    end
    normMean(i) = mean(currentVals);
    normRange(i) = max(currentVals) - min(currentVals);
    if numel(currentVals) > 1
        normStd(i) = std(currentVals);
    else
        normStd(i) = 0;
    end
end
end

function [availableCount, targetMean, targetMax] = compute_target_statistics_r2015(targetDoseMatrix)
nPairs = size(targetDoseMatrix, 1);
availableCount = zeros(nPairs, 1);
targetMean = nan(nPairs, 1);
targetMax = nan(nPairs, 1);

for i = 1:nPairs
    currentVals = targetDoseMatrix(i, :);
    currentVals = currentVals(isfinite(currentVals));
    availableCount(i) = numel(currentVals);
    if isempty(currentVals)
        continue;
    end
    targetMean(i) = mean(currentVals);
    targetMax(i) = max(currentVals);
end
end

function idx = find_reference_series_index_by_alpha_r2015(seriesMeta, alphaValue)
idx = [];
if nargin < 2 || isempty(seriesMeta) || isempty(seriesMeta.alphas)
    return;
end
tol = max(1e-9, abs(alphaValue) * 1e-6);
match = find(abs(seriesMeta.alphas - alphaValue) <= tol);
if ~isempty(match)
    idx = match(1);
end
end

function idx = find_first_finite_series_index_r2015(valueMatrix)
idx = [];
if isempty(valueMatrix)
    return;
end
for s = 1:size(valueMatrix, 2)
    if any(isfinite(valueMatrix(:, s)))
        idx = s;
        return;
    end
end
end

function idx = find_series_indices_by_alpha_r2015(seriesMeta, alphaValues)
idx = [];
if nargin < 2 || isempty(alphaValues) || isempty(seriesMeta) || isempty(seriesMeta.alphas)
    return;
end
for i = 1:numel(alphaValues)
    currentIdx = find_reference_series_index_by_alpha_r2015(seriesMeta, alphaValues(i));
    if ~isempty(currentIdx)
        idx(end + 1) = currentIdx; %#ok<AGROW>
    end
end
idx = unique(idx, 'stable');
end

function pairMetaOut = reorder_pair_metadata_r2015(pairMetaIn, order)
pairMetaOut = pairMetaIn;
if isempty(order)
    return;
end
pairMetaOut.theta = pairMetaIn.theta(order);
pairMetaOut.phi = pairMetaIn.phi(order);
pairMetaOut.labels = pairMetaIn.labels(order);
pairMetaOut.keys = pairMetaIn.keys(order);
end

function order = sort_pair_order_r2015(normRange, normMean, thetaValues, phiValues)
sortRange = normRange;
sortMean = normMean;
sortRange(~isfinite(sortRange)) = -inf;
sortMean(~isfinite(sortMean)) = -inf;

sortMatrix = [ ...
    -sortRange(:), ...
    -sortMean(:), ...
    thetaValues(:), ...
    phiValues(:), ...
    (1:numel(thetaValues))' ...
];
sorted = sortrows(sortMatrix, [1 2 3 4]);
order = sorted(:, 5);
end

function order = sort_pair_order_by_reference_alpha_r2015(normMatrix, refIdx, fallbackMean, thetaValues, phiValues)
refVals = normMatrix(:, refIdx);
refSortVals = refVals;
refSortVals(~isfinite(refSortVals)) = -inf;
meanSortVals = fallbackMean;
meanSortVals(~isfinite(meanSortVals)) = -inf;

sortMatrix = [ ...
    -refSortVals(:), ...
    -meanSortVals(:), ...
    thetaValues(:), ...
    phiValues(:), ...
    (1:numel(thetaValues))' ...
];
sorted = sortrows(sortMatrix, [1 2 3 4]);
order = sorted(:, 5);
end

function order = sort_target_pair_order_r2015(targetMean, targetMax, thetaValues, phiValues)
sortMean = targetMean;
sortMax = targetMax;
sortMean(~isfinite(sortMean)) = -inf;
sortMax(~isfinite(sortMax)) = -inf;

sortMatrix = [ ...
    -sortMean(:), ...
    -sortMax(:), ...
    thetaValues(:), ...
    phiValues(:), ...
    (1:numel(thetaValues))' ...
];
sorted = sortrows(sortMatrix, [1 2 3 4]);
order = sorted(:, 5);
end

function longTable = build_long_output_table_r2015(group, pairMeta, seriesMeta, rawMatrix, rawErrMatrix, targetDoseMatrix, compareDoseMatrix, normMatrix, normErrMatrix, countMatrix, seriesDenominator)
nPairs = numel(pairMeta.labels);
nSeries = numel(seriesMeta.labels);
nRows = nPairs * nSeries;

compareLabelCol = cell(nRows, 1);
targetLabelCol = cell(nRows, 1);
anglePairCol = cell(nRows, 1);
thetaCol = nan(nRows, 1);
phiCol = nan(nRows, 1);
seriesLabelCol = cell(nRows, 1);
sourceTypeCol = cell(nRows, 1);
alphaCol = nan(nRows, 1);
rawPctCol = nan(nRows, 1);
dRawPctCol = nan(nRows, 1);
targetDoseCol = nan(nRows, 1);
compareDoseCol = nan(nRows, 1);
normValCol = nan(nRows, 1);
dNormValCol = nan(nRows, 1);
countCol = zeros(nRows, 1);
denomCol = nan(nRows, 1);

row = 0;
for p = 1:nPairs
    for s = 1:nSeries
        row = row + 1;
        compareLabelCol{row} = group.compareLabel;
        targetLabelCol{row} = group.targetLabel;
        anglePairCol{row} = pairMeta.labels{p};
        thetaCol(row) = pairMeta.theta(p);
        phiCol(row) = pairMeta.phi(p);
        seriesLabelCol{row} = seriesMeta.labels{s};
        sourceTypeCol{row} = seriesMeta.sourceTypes{s};
        alphaCol(row) = seriesMeta.alphas(s);
        rawPctCol(row) = rawMatrix(p, s);
        dRawPctCol(row) = rawErrMatrix(p, s);
        targetDoseCol(row) = targetDoseMatrix(p, s);
        compareDoseCol(row) = compareDoseMatrix(p, s);
        normValCol(row) = normMatrix(p, s);
        dNormValCol(row) = normErrMatrix(p, s);
        countCol(row) = countMatrix(p, s);
        denomCol(row) = seriesDenominator(s);
    end
end

longTable = table(compareLabelCol, targetLabelCol, anglePairCol, thetaCol, phiCol, ...
    seriesLabelCol, sourceTypeCol, alphaCol, targetDoseCol, compareDoseCol, ...
    rawPctCol, dRawPctCol, normValCol, dNormValCol, denomCol, countCol, ...
    'VariableNames', { ...
        'CompareLabel', 'TargetLabel', 'AnglePair', 'THETA', 'PHI', ...
        'SeriesLabel', 'SourceType', 'Alpha', 'TargetDose_eVg', 'CompareDose_eVg', ...
        'CompareTarget_pct', 'dCompareTarget_pct', 'NormalizedValue', 'dNormalizedValue', ...
        'NormalizationDenominator', 'NInputs' ...
    });
end

function matrixTable = build_matrix_output_table_r2015(pairMeta, seriesMeta, rawMatrix, rawErrMatrix, targetDoseMatrix, compareDoseMatrix, normMatrix, normErrMatrix, countMatrix, availableCount, normMean, normRange, normStd)
matrixTable = table(pairMeta.labels, pairMeta.theta, pairMeta.phi, availableCount, normMean, normRange, normStd, ...
    'VariableNames', {'AnglePair', 'THETA', 'PHI', 'AvailableSeriesCount', 'NormalizedMean', 'NormalizedRange', 'NormalizedStd'});

for s = 1:numel(seriesMeta.tokens)
    baseToken = make_valid_var_name_r2015(seriesMeta.tokens{s});
    matrixTable.(['Raw_' baseToken]) = rawMatrix(:, s);
    matrixTable.(['dRaw_' baseToken]) = rawErrMatrix(:, s);
    matrixTable.(['TargetDose_' baseToken]) = targetDoseMatrix(:, s);
    matrixTable.(['CompareDose_' baseToken]) = compareDoseMatrix(:, s);
    matrixTable.(['Norm_' baseToken]) = normMatrix(:, s);
    matrixTable.(['dNorm_' baseToken]) = normErrMatrix(:, s);
    matrixTable.(['Count_' baseToken]) = countMatrix(:, s);
end
end

function summaryTable = build_series_summary_table_r2015(seriesMeta, rawMatrix, countMatrix, seriesDenominator)
nSeries = numel(seriesMeta.labels);
sourceTypeCol = cell(nSeries, 1);
seriesLabelCol = cell(nSeries, 1);
alphaCol = nan(nSeries, 1);
nPairsCol = zeros(nSeries, 1);
rawMinCol = nan(nSeries, 1);
rawMaxCol = nan(nSeries, 1);
rawMeanCol = nan(nSeries, 1);
denomCol = nan(nSeries, 1);
countCol = zeros(nSeries, 1);

for s = 1:nSeries
    vals = rawMatrix(:, s);
    vals = vals(isfinite(vals));
    sourceTypeCol{s} = seriesMeta.sourceTypes{s};
    seriesLabelCol{s} = seriesMeta.labels{s};
    alphaCol(s) = seriesMeta.alphas(s);
    nPairsCol(s) = numel(vals);
    if ~isempty(vals)
        rawMinCol(s) = min(vals);
        rawMaxCol(s) = max(vals);
        rawMeanCol(s) = mean(vals);
    end
    denomCol(s) = seriesDenominator(s);
    countCol(s) = sum(countMatrix(:, s));
end

summaryTable = table(sourceTypeCol, seriesLabelCol, alphaCol, nPairsCol, rawMinCol, rawMaxCol, rawMeanCol, denomCol, countCol, ...
    'VariableNames', {'SourceType', 'SeriesLabel', 'Alpha', 'NAnglePairs', 'RawMin_pct', 'RawMax_pct', 'RawMean_pct', 'NormalizationDenominator', 'NContributingRows'});
end

function targetRankTable = build_target_rank_table_r2015(pairMeta, seriesMeta, targetDoseMatrix, countMatrix, availableCount, targetMean, targetMax)
targetRankTable = table(pairMeta.labels, pairMeta.theta, pairMeta.phi, availableCount, targetMean, targetMax, ...
    'VariableNames', {'AnglePair', 'THETA', 'PHI', 'AvailableSeriesCount', 'TargetDoseMean_eVg', 'TargetDoseMax_eVg'});

for s = 1:numel(seriesMeta.tokens)
    baseToken = make_valid_var_name_r2015(seriesMeta.tokens{s});
    targetRankTable.(['TargetDose_' baseToken]) = targetDoseMatrix(:, s);
    targetRankTable.(['Count_' baseToken]) = countMatrix(:, s);
end
end

function screeningTable = build_screening_table_r2015(pairMeta, seriesMeta, rawMatrix, targetDoseMatrix, ratioOrderAll, targetPairOrder, subsetSeriesIdx, subsetRefIdx)
nPairs = numel(pairMeta.labels);
ratioMean = nanmean_compat_r2015(rawMatrix, 2);
targetDoseMean = nanmean_compat_r2015(targetDoseMatrix, 2);
ratioMin = nanmin_compat_r2015(rawMatrix, 2);
ratioMax = nanmax_compat_r2015(rawMatrix, 2);
targetDoseMin = nanmin_compat_r2015(targetDoseMatrix, 2);
targetDoseMax = nanmax_compat_r2015(targetDoseMatrix, 2);

screeningTable = table(pairMeta.labels, pairMeta.theta, pairMeta.phi, ratioMean, ratioMin, ratioMax, targetDoseMean, targetDoseMin, targetDoseMax, ...
    'VariableNames', {'AnglePair', 'THETA', 'PHI', 'RatioMean_pct', 'RatioMin_pct', 'RatioMax_pct', 'TargetDoseMean_eVg', 'TargetDoseMin_eVg', 'TargetDoseMax_eVg'});

screeningTable.OrderRefAlpha2p86 = build_rank_vector_r2015(ratioOrderAll, nPairs);
screeningTable.OrderTargetDoseDesc = build_rank_vector_r2015(targetPairOrder, nPairs);

subsetOrder = [];
if ~isempty(subsetSeriesIdx) && ~isempty(subsetRefIdx)
    subsetOrder = sort_pair_order_by_reference_alpha_r2015(rawMatrix, subsetRefIdx, ratioMean, pairMeta.theta, pairMeta.phi);
end
screeningTable.OrderRefAlphaSubset = build_rank_vector_r2015(subsetOrder, nPairs);

for s = 1:numel(seriesMeta.tokens)
    baseToken = make_valid_var_name_r2015(seriesMeta.tokens{s});
    screeningTable.(['Ratio_' baseToken]) = rawMatrix(:, s);
    screeningTable.(['TargetDose_' baseToken]) = targetDoseMatrix(:, s);
end

sortRef = screeningTable.OrderRefAlpha2p86;
sortDose = screeningTable.OrderTargetDoseDesc;
sortRef(~isfinite(sortRef)) = inf;
sortDose(~isfinite(sortDose)) = inf;
screeningTable.SortRef = sortRef;
screeningTable.SortDose = sortDose;
screeningTable = sortrows(screeningTable, {'SortRef', 'SortDose', 'THETA', 'PHI'});
screeningTable.SortRef = [];
screeningTable.SortDose = [];
end

function ranks = build_rank_vector_r2015(order, nPairs)
ranks = nan(nPairs, 1);
if isempty(order)
    return;
end
for i = 1:numel(order)
    ranks(order(i)) = i;
end
end

function vals = nanmean_compat_r2015(M, dim)
if nargin < 2
    dim = 1;
end
if dim ~= 2
    error('nanmean_compat_r2015 currently supports dim = 2 only.');
end
vals = nan(size(M, 1), 1);
for i = 1:size(M, 1)
    row = M(i, :);
    row = row(isfinite(row));
    if ~isempty(row)
        vals(i) = mean(row);
    end
end
end

function vals = nanmin_compat_r2015(M, dim)
if nargin < 2
    dim = 1;
end
if dim ~= 2
    error('nanmin_compat_r2015 currently supports dim = 2 only.');
end
vals = nan(size(M, 1), 1);
for i = 1:size(M, 1)
    row = M(i, :);
    row = row(isfinite(row));
    if ~isempty(row)
        vals(i) = min(row);
    end
end
end

function vals = nanmax_compat_r2015(M, dim)
if nargin < 2
    dim = 1;
end
if dim ~= 2
    error('nanmax_compat_r2015 currently supports dim = 2 only.');
end
vals = nan(size(M, 1), 1);
for i = 1:size(M, 1)
    row = M(i, :);
    row = row(isfinite(row));
    if ~isempty(row)
        vals(i) = max(row);
    end
end
end

function plotCombined = resolve_plot_titles_r2015(group, seriesMeta, refAllIdx, subsetRefIdx, rawRatioSubsetAlphas, grau)
plotCombined = struct();

if nargin < 3 || isempty(refAllIdx) || refAllIdx < 1 || refAllIdx > numel(seriesMeta.labels)
    refAllLabel = ['alpha = ' strrep(num2str(2.86), '.', ',') grau];
else
    refAllLabel = seriesMeta.labels{refAllIdx};
end

if nargin < 4 || isempty(subsetRefIdx) || subsetRefIdx < 1 || subsetRefIdx > numel(seriesMeta.labels)
    refSubsetLabel = ['alpha = ' strrep(num2str(1), '.', ',') grau];
else
    refSubsetLabel = seriesMeta.labels{subsetRefIdx};
end

subsetAlphaText = '';
if nargin >= 5 && numel(rawRatioSubsetAlphas) >= 2
    subsetAlphaText = sprintf('alphas %s%s e %s%s', ...
        strrep(num2str(rawRatioSubsetAlphas(1)), '.', ','), grau, ...
        strrep(num2str(rawRatioSubsetAlphas(2)), '.', ','), grau);
else
    subsetAlphaText = 'subset de alphas';
end

defaultRatioAllTitle = sprintf('Comparacao bruta por angulo: %s / %s | ordem definida por %s', group.compareLabel, group.targetLabel, refAllLabel);
defaultRatioSubsetTitle = sprintf('Comparacao bruta por angulo: %s / %s | %s | ordem definida por %s', group.compareLabel, group.targetLabel, subsetAlphaText, refSubsetLabel);
defaultDoseRankedTitle = sprintf('Dose depositada em %s por par angular | ordem por dose media no alvo', group.targetLabel);
defaultDoseRatioOrderTitle = sprintf('Dose depositada em %s por par angular | ordem do grafico da razao (%s)', group.targetLabel, refAllLabel);
defaultScatterTitle = sprintf('Dispersao: dose em %s vs %s / %s', group.targetLabel, group.compareLabel, group.targetLabel);

try
    answers = prompt_plot_titles_dialog_r2015( ...
        {'Title for all-alpha raw ratio plot', ...
         'Title for subset raw ratio plot', ...
         'Title for target dose descending plot', ...
         'Title for target dose ratio-order plot', ...
         'Title for ratio-vs-dose scatter plot'}, ...
        'Angle ranking plot titles', ...
        {defaultRatioAllTitle, defaultRatioSubsetTitle, defaultDoseRankedTitle, defaultDoseRatioOrderTitle, defaultScatterTitle});
catch
    answers = inputdlg( ...
        {'Title for all-alpha raw ratio plot', ...
         'Title for subset raw ratio plot', ...
         'Title for target dose descending plot', ...
         'Title for target dose ratio-order plot', ...
         'Title for ratio-vs-dose scatter plot'}, ...
        'Angle ranking plot titles', ...
        [1 140; 1 140; 1 140; 1 140; 1 140], ...
        {defaultRatioAllTitle, defaultRatioSubsetTitle, defaultDoseRankedTitle, defaultDoseRatioOrderTitle, defaultScatterTitle});
end
if isempty(answers)
    plotCombined.ratioAllTitle = defaultRatioAllTitle;
    plotCombined.ratioSubsetTitle = defaultRatioSubsetTitle;
    plotCombined.doseRankedTitle = defaultDoseRankedTitle;
    plotCombined.doseRatioOrderTitle = defaultDoseRatioOrderTitle;
    plotCombined.scatterTitle = defaultScatterTitle;
else
    plotCombined.ratioAllTitle = strtrim(answers{1});
    plotCombined.ratioSubsetTitle = strtrim(answers{2});
    plotCombined.doseRankedTitle = strtrim(answers{3});
    plotCombined.doseRatioOrderTitle = strtrim(answers{4});
    plotCombined.scatterTitle = strtrim(answers{5});
    if isempty(plotCombined.ratioAllTitle)
        plotCombined.ratioAllTitle = defaultRatioAllTitle;
    end
    if isempty(plotCombined.ratioSubsetTitle)
        plotCombined.ratioSubsetTitle = defaultRatioSubsetTitle;
    end
    if isempty(plotCombined.doseRankedTitle)
        plotCombined.doseRankedTitle = defaultDoseRankedTitle;
    end
    if isempty(plotCombined.doseRatioOrderTitle)
        plotCombined.doseRatioOrderTitle = defaultDoseRatioOrderTitle;
    end
    if isempty(plotCombined.scatterTitle)
        plotCombined.scatterTitle = defaultScatterTitle;
    end
end
end

function answers = prompt_plot_titles_dialog_r2015(promptList, dialogTitle, defaultValues)
answers = {};
if nargin < 1 || isempty(promptList)
    return;
end
if nargin < 2 || isempty(dialogTitle)
    dialogTitle = 'Edit plot titles';
end
if nargin < 3 || isempty(defaultValues)
    defaultValues = cell(size(promptList));
end

nItems = numel(promptList);
dlgWidth = 1220;
rowHeight = 76;
dlgHeight = max(260, 120 + nItems * rowHeight);
dlg = dialog('Name', dialogTitle, ...
    'Units', 'pixels', ...
    'Position', [120 80 dlgWidth dlgHeight], ...
    'Resize', 'on', ...
    'WindowStyle', 'normal', ...
    'Visible', 'off');

editHandles = zeros(nItems, 1);
for i = 1:nItems
    yBase = dlgHeight - 38 - i * rowHeight;
    uicontrol('Parent', dlg, ...
        'Style', 'text', ...
        'String', promptList{i}, ...
        'Units', 'pixels', ...
        'Position', [22 yBase + 34 dlgWidth - 44 20], ...
        'HorizontalAlignment', 'left');
    editHandles(i) = uicontrol('Parent', dlg, ...
        'Style', 'edit', ...
        'String', defaultValues{i}, ...
        'Units', 'pixels', ...
        'Position', [22 yBase dlgWidth - 44 28], ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'white');
end

uicontrol('Parent', dlg, ...
    'Style', 'pushbutton', ...
    'String', 'OK', ...
    'Units', 'pixels', ...
    'Position', [dlgWidth - 208 18 82 30], ...
    'Callback', @confirm_dialog_r2015);
uicontrol('Parent', dlg, ...
    'Style', 'pushbutton', ...
    'String', 'Cancel', ...
    'Units', 'pixels', ...
    'Position', [dlgWidth - 112 18 82 30], ...
    'Callback', @cancel_dialog_r2015);

set(dlg, 'CloseRequestFcn', @cancel_dialog_r2015);
movegui(dlg, 'center');
set(dlg, 'Visible', 'on');
uiwait(dlg);

if ishandle(dlg)
    storedAnswers = getappdata(dlg, 'angle_ranking_plot_title_answers');
    if ~isempty(storedAnswers)
        answers = storedAnswers;
    end
    delete(dlg);
end

    function confirm_dialog_r2015(varargin)
        localAnswers = cell(nItems, 1);
        for j = 1:nItems
            localAnswers{j} = get(editHandles(j), 'String');
        end
        setappdata(dlg, 'angle_ranking_plot_title_answers', localAnswers);
        uiresume(dlg);
    end

    function cancel_dialog_r2015(varargin)
        uiresume(dlg);
    end
end

function plot_raw_ratio_horizontal_dots_r2015(group, pairLabels, seriesLabels, rawMatrix, rawErrMatrix, seriesIdx, outDir, baseName, plotTitle)
if isempty(pairLabels) || isempty(seriesIdx)
    return;
end

pairLabels = pairLabels(:);
seriesIdx = seriesIdx(:)';
nPairs = numel(pairLabels);
nShownSeries = numel(seriesIdx);
figHeight = max(1200, 38 * nPairs + 260);
fig = figure('Color', 'w', 'Position', [70, 40, 1900, figHeight]);
ax = axes('Parent', fig);
hold(ax, 'on');

colors = lines(numel(seriesLabels));
markerList = {'o', 's', 'd', '^', 'v', '>', '<', 'p', 'h', 'x', '+'};
offsets = compute_series_offsets_r2015(nShownSeries, 0.66);
plotHandles = [];
plotLegendLabels = {};
xMax = 0;

for k = 1:nShownSeries
    s = seriesIdx(k);
    currentVals = rawMatrix(:, s);
    currentErrs = rawErrMatrix(:, s);
    currentVals = currentVals(:);
    currentErrs = currentErrs(:);
    finiteMask = isfinite(currentVals);
    if ~any(finiteMask)
        continue;
    end

    yVals = (1:nPairs)' + offsets(k);
    yVals = yVals(:);
    markerValue = markerList{mod(k - 1, numel(markerList)) + 1};
    colorValue = colors(s, :);

    try
        errorMask = finiteMask & isfinite(currentErrs) & currentErrs > 0;
        errorRows = find(errorMask);
        for e = 1:numel(errorRows)
            rowIdx = errorRows(e);
            line( ...
                'Parent', ax, ...
                'XData', [currentVals(rowIdx) - currentErrs(rowIdx), currentVals(rowIdx) + currentErrs(rowIdx)], ...
                'YData', [yVals(rowIdx), yVals(rowIdx)], ...
                'Color', [0.25 0.25 0.25], ...
                'LineWidth', 0.8);
        end
    catch ME
        error('Error-bar stage failed for %s: %s', seriesLabels{s}, ME.message);
    end

    xPlot = currentVals(finiteMask);
    yPlot = yVals(finiteMask);
    xPlot = xPlot(:);
    yPlot = yPlot(:);
    if numel(xPlot) ~= numel(yPlot)
        error('Point-stage length mismatch for %s: x=%d, y=%d', seriesLabels{s}, numel(xPlot), numel(yPlot));
    end
    try
        h = line( ...
            'Parent', ax, ...
            'XData', xPlot(:)', ...
            'YData', yPlot(:)', ...
            'LineStyle', 'none', ...
            'Marker', markerValue, ...
            'MarkerSize', 7, ...
            'MarkerFaceColor', colorValue, ...
            'MarkerEdgeColor', [0.1 0.1 0.1], ...
            'DisplayName', seriesLabels{s});
    catch ME
        error('Point-stage failed for %s: %s', seriesLabels{s}, ME.message);
    end
    plotHandles(end + 1) = h; %#ok<AGROW>
    plotLegendLabels{end + 1, 1} = seriesLabels{s}; %#ok<AGROW>

    finiteVals = currentVals(finiteMask);
    finiteErrs = currentErrs(finiteMask);
    finiteErrs(~isfinite(finiteErrs)) = 0;
    xMax = max(xMax, max(finiteVals + finiteErrs));
end

hold(ax, 'off');

if isempty(plotHandles)
    close(fig);
    return;
end

try
    set(ax, 'YTick', 1:nPairs, 'YTickLabel', pairLabels, 'YDir', 'reverse', 'FontSize', 12);
catch ME
    error('Axis-label stage failed: nPairs=%d, nLabels=%d, %s', nPairs, numel(pairLabels), ME.message);
end
ylim(ax, [0.5, nPairs + 0.5]);
xlim(ax, [0, max(1, 1.05 * xMax)]);
grid(ax, 'on');
box(ax, 'on');
xlabel(ax, sprintf('%s / %s (%%)', group.compareLabel, group.targetLabel), 'FontSize', 13);
ylabel(ax, 'Theta/Phi pair', 'FontSize', 13);
title(ax, plotTitle, 'Interpreter', 'none', 'FontSize', 16, 'FontWeight', 'bold');
try
    legend(ax, plotHandles, plotLegendLabels, 'Location', 'EastOutside', 'Interpreter', 'none', 'FontSize', 12);
catch ME
    error('Legend stage failed: handles=%d, labels=%d, %s', numel(plotHandles), numel(plotLegendLabels), ME.message);
end
set(fig, 'PaperPositionMode', 'auto');
saveas(fig, fullfile(outDir, [baseName '.png']));
close(fig);
end

function offsets = compute_series_offsets_r2015(nSeries, totalSpread)
if nargin < 2 || ~isfinite(totalSpread) || totalSpread <= 0
    totalSpread = 0.66;
end
if nargin < 1 || isempty(nSeries) || nSeries <= 1
    offsets = 0;
    return;
end
offsets = linspace(-totalSpread / 2, totalSpread / 2, nSeries);
offsets = offsets(:)';
end

function plot_combined_normalized_bars_r2015(group, pairLabels, seriesLabels, normMatrix, normalizationMode, normalizedScale, outDir, baseName, plotTitles)
if isempty(pairLabels) || isempty(seriesLabels)
    return;
end

nPairs = numel(pairLabels);
figHeight = max(760, 26 * nPairs + 180);
fig = figure('Color', 'w', 'Position', [100, 80, 1500, figHeight]);
bh = barh(normMatrix, 'grouped', 'BarWidth', 0.85);
hold on;
colors = lines(numel(seriesLabels));
for i = 1:numel(bh)
    set(bh(i), 'FaceColor', colors(i, :), 'EdgeColor', [0.1 0.1 0.1]);
end
hold off;

ax = gca;
set(ax, 'YTick', 1:nPairs, 'YTickLabel', pairLabels, 'YDir', 'reverse');
grid on;
box on;

switch lower(strtrim(normalizationMode))
    case 'sum'
        xLabelText = sprintf('Valor normalizado (%% da soma da serie, escala %.0f)', normalizedScale);
    case 'none'
        xLabelText = 'Razao compare/target bruta (%)';
    otherwise
        xLabelText = sprintf('Valor normalizado (%% do maximo da serie, escala %.0f)', normalizedScale);
end

xlabel(xLabelText);
title(plotTitles.ratioTitle, 'Interpreter', 'none');
legend(seriesLabels, 'Location', 'EastOutside', 'Interpreter', 'none');
xlim([0 normalizedScale]);
set(fig, 'PaperPositionMode', 'auto');
saveas(fig, fullfile(outDir, [baseName '_normalized.png']));
close(fig);
end

function plot_reference_alpha_normalized_bars_r2015(group, pairMeta, seriesMeta, normMatrix, normalizationMode, normalizedScale, outDir, baseName, plotTitles, normMean)
if isempty(pairMeta.labels) || isempty(seriesMeta.labels)
    return;
end

for refIdx = 1:numel(seriesMeta.labels)
    currentOrder = sort_pair_order_by_reference_alpha_r2015(normMatrix, refIdx, normMean, pairMeta.theta, pairMeta.phi);
    orderedLabels = pairMeta.labels(currentOrder);
    orderedMatrix = normMatrix(currentOrder, :);
    refLabel = seriesMeta.labels{refIdx};
    refToken = make_valid_var_name_r2015(seriesMeta.tokens{refIdx});
    localTitles = plotTitles;
    localTitles.ratioTitle = sprintf('%s | ordem definida por %s', plotTitles.ratioTitle, refLabel);
    plot_combined_normalized_bars_single_r2015(group, orderedLabels, seriesMeta.labels, orderedMatrix, normalizationMode, normalizedScale, outDir, [baseName '_ref_' refToken], localTitles);
end
end

function plot_combined_normalized_bars_single_r2015(group, pairLabels, seriesLabels, normMatrix, normalizationMode, normalizedScale, outDir, baseName, plotTitles)
if isempty(pairLabels) || isempty(seriesLabels)
    return;
end

nPairs = numel(pairLabels);
figHeight = max(1200, 42 * nPairs + 260);
fig = figure('Color', 'w', 'Position', [80, 60, 1850, figHeight]);
bh = barh(normMatrix, 'grouped', 'BarWidth', 0.95);
hold on;
colors = lines(numel(seriesLabels));
for i = 1:numel(bh)
    set(bh(i), 'FaceColor', colors(i, :), 'EdgeColor', [0.1 0.1 0.1], 'LineWidth', 0.8);
end
hold off;

ax = gca;
set(ax, 'YTick', 1:nPairs, 'YTickLabel', pairLabels, 'YDir', 'reverse', 'FontSize', 12);
grid on;
box on;

switch lower(strtrim(normalizationMode))
    case 'sum'
        xLabelText = sprintf('Valor normalizado (%% da soma da serie, escala %.0f)', normalizedScale);
    case 'none'
        xLabelText = 'Razao compare/target bruta (%)';
    otherwise
        xLabelText = sprintf('Valor normalizado (%% do maximo da serie, escala %.0f)', normalizedScale);
end

xlabel(xLabelText, 'FontSize', 13);
title(plotTitles.ratioTitle, 'Interpreter', 'none', 'FontSize', 16, 'FontWeight', 'bold');
legend(seriesLabels, 'Location', 'EastOutside', 'Interpreter', 'none', 'FontSize', 12);
xlim([0 normalizedScale]);
set(fig, 'PaperPositionMode', 'auto');
saveas(fig, fullfile(outDir, [baseName '_normalized.png']));
close(fig);
end

function plot_target_dose_ranked_lines_r2015(group, pairLabels, seriesLabels, targetDoseMatrix, useLogScale, outDir, baseName, plotTitle, xLabelText)
if isempty(pairLabels) || isempty(seriesLabels)
    return;
end

nPairs = numel(pairLabels);
figWidth = max(1400, 34 * nPairs + 420);
fig = figure('Color', 'w', 'Position', [80, 80, figWidth, 780]);
ax = axes('Parent', fig);
hold(ax, 'on');

xVals = (1:nPairs)';
colors = lines(numel(seriesLabels));
markerList = {'o', 's', 'd', '^', 'v', '>', '<', 'p', 'h', 'x', '+'};
plotHandles = [];
plotLabels = {};
for s = 1:numel(seriesLabels)
    currentVals = targetDoseMatrix(:, s);
    currentVals = currentVals(:);
    finiteMask = isfinite(currentVals);
    if ~any(finiteMask)
        continue;
    end
    markerValue = markerList{mod(s - 1, numel(markerList)) + 1};
    h = plot(ax, xVals(finiteMask), currentVals(finiteMask), ...
        '-', 'Color', colors(s, :), 'LineWidth', 1.6, ...
        'Marker', markerValue, 'MarkerSize', 6, ...
        'MarkerFaceColor', colors(s, :), 'MarkerEdgeColor', [0.1 0.1 0.1], ...
        'DisplayName', seriesLabels{s});
    plotHandles(end + 1) = h; %#ok<AGROW>
    plotLabels{end + 1, 1} = seriesLabels{s}; %#ok<AGROW>
end
hold(ax, 'off');

if isempty(plotHandles)
    close(fig);
    return;
end

set(ax, 'XTick', 1:nPairs, 'XTickLabel', pairLabels);
try
    set(ax, 'XTickLabelRotation', 45);
catch
end
grid(ax, 'on');
box(ax, 'on');
if useLogScale
    set(ax, 'YScale', 'log');
else
    finiteVals = targetDoseMatrix(isfinite(targetDoseMatrix));
    if ~isempty(finiteVals)
        yMax = max(finiteVals);
        if isfinite(yMax) && yMax > 0
            ylim(ax, [0, 1.05 * yMax]);
        else
            ylim(ax, [0, 1]);
        end
    end
end

if nargin < 9 || isempty(xLabelText)
    xLabelText = sprintf('Par Theta/Phi (ordenado por dose em %s)', group.targetLabel);
end
xlabel(ax, xLabelText);
ylabel(ax, sprintf('Dose depositada em %s (eV/g)', group.targetLabel));
title(ax, plotTitle, 'Interpreter', 'none');
legend(ax, plotHandles, plotLabels, 'Location', 'EastOutside', 'Interpreter', 'none');
set(fig, 'PaperPositionMode', 'auto');
saveas(fig, fullfile(outDir, [baseName '.png']));
close(fig);
end

function plot_ratio_vs_target_dose_scatter_r2015(group, seriesMeta, rawMatrix, targetDoseMatrix, outDir, baseName, plotTitle)
if isempty(seriesMeta) || isempty(seriesMeta.labels) || isempty(rawMatrix) || isempty(targetDoseMatrix)
    return;
end

fig = figure('Color', 'w', 'Position', [90, 90, 1280, 820]);
ax = axes('Parent', fig);
hold(ax, 'on');

colors = lines(numel(seriesMeta.labels));
markerList = {'o', 's', 'd', '^', 'v', '>', '<', 'p', 'h', 'x', '+'};
plotHandles = [];
plotLabels = {};
xMax = 0;
yMax = 0;

for s = 1:numel(seriesMeta.labels)
    xVals = rawMatrix(:, s);
    yVals = targetDoseMatrix(:, s);
    xVals = xVals(:);
    yVals = yVals(:);
    finiteMask = isfinite(xVals) & isfinite(yVals);
    if ~any(finiteMask)
        continue;
    end

    xPlot = xVals(finiteMask);
    yPlot = yVals(finiteMask);
    markerValue = markerList{mod(s - 1, numel(markerList)) + 1};
    colorValue = colors(s, :);
    h = line( ...
        'Parent', ax, ...
        'XData', xPlot(:)', ...
        'YData', yPlot(:)', ...
        'LineStyle', 'none', ...
        'Marker', markerValue, ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', colorValue, ...
        'MarkerEdgeColor', [0.1 0.1 0.1], ...
        'LineWidth', 0.8, ...
        'DisplayName', seriesMeta.labels{s});
    plotHandles(end + 1) = h; %#ok<AGROW>
    plotLabels{end + 1, 1} = seriesMeta.labels{s}; %#ok<AGROW>

    xMax = max(xMax, max(xPlot));
    yMax = max(yMax, max(yPlot));
end

hold(ax, 'off');

if isempty(plotHandles)
    close(fig);
    return;
end

if ~isfinite(xMax) || xMax <= 0
    xMax = 1;
end
if ~isfinite(yMax) || yMax <= 0
    yMax = 1;
end

xlim(ax, [0, 1.05 * xMax]);
ylim(ax, [0, 1.05 * yMax]);
grid(ax, 'on');
box(ax, 'on');
xlabel(ax, sprintf('%s / %s (%%)', group.compareLabel, group.targetLabel), 'FontSize', 13);
ylabel(ax, sprintf('Dose em %s (eV/g)', group.targetLabel), 'FontSize', 13);
title(ax, plotTitle, 'Interpreter', 'none', 'FontSize', 16, 'FontWeight', 'bold');
text(0.03 * xMax, 0.98 * yMax, 'Regiao ideal: canto superior esquerdo', ...
    'Parent', ax, 'VerticalAlignment', 'top', 'FontSize', 11, 'Color', [0.2 0.2 0.2]);
legend(ax, plotHandles, plotLabels, 'Location', 'EastOutside', 'Interpreter', 'none', 'FontSize', 12);
set(fig, 'PaperPositionMode', 'auto');
saveas(fig, fullfile(outDir, [baseName '.png']));
close(fig);
end

function [compareToken, targetToken] = parse_ranking_group_tokens_r2015(pathValue)
compareToken = '';
targetToken = '';
[~, fileName, fileExt] = fileparts(pathValue);
cleanName = regexprep(fileName, '\s+\(\d+\)$', '');
match = regexp([cleanName fileExt], '^angle_ranking_(.+)_vs_(.+)\.csv$', 'tokens', 'once');
if isempty(match)
    return;
end
compareToken = match{1};
targetToken = match{2};
end

function name = display_label_from_token_r2015(token)
if nargin < 1 || isempty(token)
    name = '';
    return;
end
key = normalize_body_compare_key_r2015(token);
switch key
    case 'olhodireito'
        name = 'Olho direito';
    case 'olhoesquerdo'
        name = 'Olho esquerdo';
    case 'tumorolhodto'
        name = 'Tumor olho dto';
    case 'tumorouvidoesq'
        name = 'Tumor ouvido esq';
    case 'cerebro'
        name = 'Cerebro';
    otherwise
        name = strrep(token, '_', ' ');
end
end

function key = build_series_key_r2015(sourceType, alphaValue)
key = [safe_file_token_r2015(sourceType) '|' alpha_token_r2015(alphaValue)];
end

function key = build_pair_key_r2015(thetaValue, phiValue)
key = sprintf('T%.12g_P%.12g', thetaValue, phiValue);
end

function token = alpha_token_r2015(alphaValue)
if ~isfinite(alphaValue)
    token = 'nan';
    return;
end
token = num2str(alphaValue, '%.12g');
token = strrep(token, '.', 'p');
token = strrep(token, '-', 'm');
end

function T = load_dose_sheet_r2015(excelPath)
[~, ~, raw] = xlsread(excelPath, 'Dose');
if isempty(raw) || size(raw, 1) < 2
    error('Dose sheet is empty or missing usable rows.');
end

headers = raw(1, :);
rows = raw(2:end, :);

caseIdx = find_header_index_r2015(headers, {'Case'});
sourceTypeIdx = find_optional_header_index_r2015(headers, {'Spectrum Type', 'Source Type', 'SourceType'});
componentIdx = find_header_index_r2015(headers, {'Component'});
edepIdx = find_header_index_r2015(headers, {'Edep (eV)', 'Edep_eV'});
dedepIdx = find_header_index_r2015(headers, {'dE (eV)', 'dE_eV'});
doseEvgIdx = find_header_index_r2015(headers, {'Dose (eV/g)', 'Dose_eV_g'});
ddoseEvgIdx = find_header_index_r2015(headers, {'dDose (eV/g)', 'dDose_eV_g'});
doseGyIdx = find_optional_header_index_r2015(headers, {'Dose (Gy)', 'Dose_Gy'});
ddoseGyIdx = find_optional_header_index_r2015(headers, {'dDose (Gy)', 'dDose_Gy'});

T.case_names = cell_column_to_strings_r2015(rows(:, caseIdx));
if ~isnan(sourceTypeIdx)
    T.source_types = cell_column_to_strings_r2015(rows(:, sourceTypeIdx));
else
    T.source_types = repmat({''}, size(rows, 1), 1);
end
for i = 1:numel(T.source_types)
    T.source_types{i} = normalize_source_type_label_r2015(T.source_types{i});
end
T.component_names = cell_column_to_strings_r2015(rows(:, componentIdx));
T.edep_ev = cell_column_to_numeric_r2015(rows(:, edepIdx));
T.dedep_ev = cell_column_to_numeric_r2015(rows(:, dedepIdx));
T.dose_evg = cell_column_to_numeric_r2015(rows(:, doseEvgIdx));
T.ddose_evg = cell_column_to_numeric_r2015(rows(:, ddoseEvgIdx));
T.dose_gy = cell_column_to_numeric_r2015_by_index_r2015(rows, doseGyIdx);
T.ddose_gy = cell_column_to_numeric_r2015_by_index_r2015(rows, ddoseGyIdx);

keep = ~cellfun(@isempty, T.case_names) & ~cellfun(@isempty, T.component_names);
T.case_names = T.case_names(keep);
T.source_types = T.source_types(keep);
T.component_names = T.component_names(keep);
T.edep_ev = T.edep_ev(keep);
T.dedep_ev = T.dedep_ev(keep);
T.dose_evg = T.dose_evg(keep);
T.ddose_evg = T.ddose_evg(keep);
T.dose_gy = T.dose_gy(keep);
T.ddose_gy = T.ddose_gy(keep);
end

function idx = find_header_index_r2015(headers, candidates)
idx = [];
for i = 1:numel(headers)
    current = normalize_header_name_r2015(headers{i});
    for j = 1:numel(candidates)
        if strcmp(current, normalize_header_name_r2015(candidates{j}))
            idx = i;
            return;
        end
    end
end
error('Could not find expected Excel column header: ''%s''.', candidates{1});
end

function idx = find_optional_header_index_r2015(headers, candidates)
idx = NaN;
for i = 1:numel(headers)
    current = normalize_header_name_r2015(headers{i});
    for j = 1:numel(candidates)
        if strcmp(current, normalize_header_name_r2015(candidates{j}))
            idx = i;
            return;
        end
    end
end
end

function out = normalize_header_name_r2015(value)
if isnumeric(value)
    value = num2str(value);
elseif ~ischar(value)
    value = '';
end
out = regexprep(lower(strtrim(value)), '[^a-z0-9]+', '');
end

function values = cell_column_to_strings_r2015(col)
values = cell(size(col));
for i = 1:numel(col)
    if ischar(col{i})
        values{i} = strtrim(col{i});
    elseif isnumeric(col{i}) && isscalar(col{i}) && ~isnan(col{i})
        values{i} = num2str(col{i});
    else
        values{i} = '';
    end
end
values = values(:);
end

function values = cell_column_to_numeric_r2015(col)
values = nan(size(col));
for i = 1:numel(col)
    if isnumeric(col{i}) && isscalar(col{i})
        values(i) = col{i};
    elseif ischar(col{i})
        values(i) = str2double(strrep(col{i}, ',', '.'));
    end
end
values = values(:);
end

function values = cell_column_to_numeric_r2015_by_index_r2015(rows, idx)
if isnan(idx)
    values = nan(size(rows, 1), 1);
else
    values = cell_column_to_numeric_r2015(rows(:, idx));
end
end

function mask = build_component_match_mask_r2015(componentNames, desiredNames)
mask = false(numel(componentNames), 1);
desiredNames = normalize_body_name_list_r2015(desiredNames);
if isempty(desiredNames)
    return;
end
desiredKeys = cell(size(desiredNames));
for j = 1:numel(desiredNames)
    desiredKeys{j} = normalize_body_compare_key_r2015(desiredNames{j});
end
for i = 1:numel(componentNames)
    current = '';
    if ischar(componentNames{i})
        current = strtrim(componentNames{i});
    end
    currentKey = normalize_body_compare_key_r2015(current);
    for j = 1:numel(desiredKeys)
        if strcmp(currentKey, desiredKeys{j})
            mask(i) = true;
            break;
        end
    end
end
end

function names = normalize_body_name_list_r2015(rawNames)
names = {};
if nargin < 1 || isempty(rawNames)
    return;
end
if ischar(rawNames)
    rawNames = {rawNames};
elseif ~iscell(rawNames)
    return;
end
for i = 1:numel(rawNames)
    item = rawNames{i};
    label = '';
    if ischar(item)
        label = strtrim(item);
    elseif iscell(item) && ~isempty(item) && ischar(item{1})
        label = strtrim(item{1});
    end
    if isempty(label)
        continue;
    end
    labelKey = normalize_body_compare_key_r2015(label);
    if isempty(labelKey)
        continue;
    end
    duplicate = false;
    for j = 1:numel(names)
        if strcmp(normalize_body_compare_key_r2015(names{j}), labelKey)
            duplicate = true;
            break;
        end
    end
    if ~duplicate
        names{end + 1, 1} = label; %#ok<AGROW>
    end
end
end

function key = normalize_body_compare_key_r2015(value)
if nargin < 1 || isempty(value)
    key = '';
    return;
end
if isnumeric(value)
    value = num2str(value);
elseif ~ischar(value)
    try
        value = char(value);
    catch
        value = '';
    end
end
value = strip_portuguese_diacritics_r2015(strtrim(value));
key = regexprep(lower(value), '[^a-z0-9]+', '');
switch key
    case 'crebro'
        key = 'cerebro';
    case 'olhodto'
        key = 'olhodireito';
    case 'olhoesq'
        key = 'olhoesquerdo';
end
end

function out = strip_portuguese_diacritics_r2015(value)
out = char(value);
replacements = {
    char(193), 'A'; char(192), 'A'; char(195), 'A'; char(194), 'A'; char(196), 'A';
    char(225), 'a'; char(224), 'a'; char(227), 'a'; char(226), 'a'; char(228), 'a';
    char(201), 'E'; char(200), 'E'; char(202), 'E'; char(203), 'E';
    char(233), 'e'; char(232), 'e'; char(234), 'e'; char(235), 'e';
    char(205), 'I'; char(204), 'I'; char(206), 'I'; char(207), 'I';
    char(237), 'i'; char(236), 'i'; char(238), 'i'; char(239), 'i';
    char(211), 'O'; char(210), 'O'; char(213), 'O'; char(212), 'O'; char(214), 'O';
    char(243), 'o'; char(242), 'o'; char(245), 'o'; char(244), 'o'; char(246), 'o';
    char(218), 'U'; char(217), 'U'; char(219), 'U'; char(220), 'U';
    char(250), 'u'; char(249), 'u'; char(251), 'u'; char(252), 'u';
    char(199), 'C'; char(231), 'c'
};
for i = 1:size(replacements, 1)
    out = strrep(out, replacements{i, 1}, replacements{i, 2});
end
end

function labels = fill_empty_labels_r2015(labels, fallbackLabel)
labels = labels(:);
for i = 1:numel(labels)
    current = '';
    if ischar(labels{i})
        current = strtrim(labels{i});
    end
    if isempty(current)
        labels{i} = fallbackLabel;
    end
end
end

function out = display_source_type_r2015(label)
out = normalize_source_type_label_r2015(label);
if isempty(out)
    out = 'Unknown source';
end
end

function out = normalize_source_type_label_r2015(label)
if nargin < 1 || isempty(label)
    out = '';
    return;
end
if isnumeric(label)
    label = num2str(label);
elseif ~ischar(label)
    try
        label = char(label);
    catch
        label = '';
    end
end
text = strtrim(label);
text = strip_portuguese_diacritics_r2015(text);
text = regexprep(text, '[_]+', ' ');
text = regexprep(text, '\s+', ' ');
key = regexprep(lower(text), '[^a-z0-9]+', '');
switch key
    case 'linac6mev'
        out = 'LINAC 6MeV';
    case {'cobalt60source', 'cobalt60', 'co60', 'co60source'}
        out = 'Cobalt-60 source';
    otherwise
        out = text;
end
end

function token = safe_file_token_r2015(label)
token = regexprep(lower(display_source_type_r2015(label)), '[^a-z0-9]+', '_');
token = regexprep(token, '_+', '_');
token = regexprep(token, '^_|_$', '');
if isempty(token)
    token = 'unknown_source';
end
end

function token = safe_label_file_token_r2015(label)
if nargin < 1 || isempty(label)
    token = 'label';
    return;
end
if isnumeric(label)
    label = num2str(label);
elseif ~ischar(label)
    try
        label = char(label);
    catch
        label = '';
    end
end
key = normalize_body_compare_key_r2015(label);
switch key
    case 'olhodireito'
        token = 'olho_direito';
    case 'olhoesquerdo'
        token = 'olho_esquerdo';
    case 'tumorolhodto'
        token = 'tumor_olho_dto';
    case 'tumorouvidoesq'
        token = 'tumor_ouvido_esq';
    case 'cerebro'
        token = 'cerebro';
    otherwise
        text = strip_portuguese_diacritics_r2015(strtrim(label));
        token = regexprep(lower(text), '[^a-z0-9]+', '_');
        token = regexprep(token, '_+', '_');
        token = regexprep(token, '^_|_$', '');
        if isempty(token)
            token = 'label';
        end
end
end

function [ratioPct, dRatioPct] = safe_ratio_pct_r2015(numeratorDose, dNumeratorDose, denominatorDose, dDenominatorDose)
ratioPct = NaN;
dRatioPct = NaN;
if ~isfinite(numeratorDose) || ~isfinite(denominatorDose)
    return;
end
if numeratorDose <= 0 || denominatorDose <= 0
    return;
end
ratioPct = 100 * numeratorDose / denominatorDose;
if ~isfinite(dNumeratorDose) || ~isfinite(dDenominatorDose)
    return;
end
if dNumeratorDose < 0 || dDenominatorDose < 0
    return;
end
dRatioPct = abs(ratioPct) * sqrt((dNumeratorDose / numeratorDose)^2 + (dDenominatorDose / denominatorDose)^2);
if ~isfinite(dRatioPct)
    dRatioPct = NaN;
end
end

function varName = find_table_var_name_r2015(T, candidates)
varName = '';
vars = T.Properties.VariableNames;
for i = 1:numel(vars)
    current = normalize_header_name_r2015(vars{i});
    for j = 1:numel(candidates)
        if strcmp(current, normalize_header_name_r2015(candidates{j}))
            varName = vars{i};
            return;
        end
    end
end
error('Could not find expected table column: ''%s''.', candidates{1});
end

function varName = find_optional_table_var_name_r2015(T, candidates)
varName = '';
vars = T.Properties.VariableNames;
for i = 1:numel(vars)
    current = normalize_header_name_r2015(vars{i});
    for j = 1:numel(candidates)
        if strcmp(current, normalize_header_name_r2015(candidates{j}))
            varName = vars{i};
            return;
        end
    end
end
end

function values = table_column_to_strings_r2015(T, varName)
if isempty(varName)
    values = repmat({''}, height(T), 1);
    return;
end
raw = T.(varName);
values = cell(height(T), 1);
for i = 1:height(T)
    if iscell(raw)
        current = raw{i};
    else
        current = raw(i);
    end
    if ischar(current)
        values{i} = strtrim(current);
    elseif isnumeric(current) && isscalar(current) && ~isnan(current)
        values{i} = num2str(current);
    else
        values{i} = '';
    end
end
end

function values = table_column_to_numeric_r2015(T, varName)
if isempty(varName)
    values = nan(height(T), 1);
    return;
end
raw = T.(varName);
values = nan(height(T), 1);
for i = 1:height(T)
    if iscell(raw)
        current = raw{i};
    else
        current = raw(i);
    end
    if isnumeric(current) && isscalar(current)
        values(i) = current;
    elseif ischar(current)
        values(i) = str2double(strrep(current, ',', '.'));
    end
end
end

function out = make_valid_var_name_r2015(label)
out = regexprep(lower(strtrim(label)), '[^a-z0-9]+', '_');
out = regexprep(out, '_+', '_');
out = regexprep(out, '^_|_$', '');
if isempty(out)
    out = 'value';
end
if ~isempty(regexp(out(1), '[0-9]', 'once'))
    out = ['x_' out];
end
end
