function Global_Report
% Global_Report
% Bottom-up workbook combiner for grouped dose comparisons.
%
% Save this script in the master root you want to process. The script:
% 1) walks child folders bottom-up;
% 2) reuses child body_totals_by_alpha.csv or child Global_Report_body_totals.csv;
% 3) harmonizes BODY labels for cross-phantom comparisons;
% 4) writes grouped totals CSVs and plots at each level.
%
% This template is intentionally workbook-focused. It does not process
% 3d-dose.dat files.

close all;
clc;
disp(['Running Global_Report from: ' mfilename('fullpath')]);

%% ---------------- USER PARAMETERS ----------------
% selectedLabelSpecs was generated by PENELOPE Studio from user-selected SURFACE labels
%__STUDIO_SELECTED_LABELS_BEGIN__
xTumorOlhoDto = 4.0;  yTumorOlhoDto = 3.0;  zTumorOlhoDto = -2.2;
xOlhoDireito = 4.0;  yOlhoDireito = 6.5;  zOlhoDireito = -2.0;
xOlhoEsquerdo = -4.0;  yOlhoEsquerdo = 6.5;  zOlhoEsquerdo = -2.0;
selectedLabelSpecs = {
    'Tumor olho dto', 'target', xTumorOlhoDto, yTumorOlhoDto, zTumorOlhoDto;
    'Olho direito', 'body', xOlhoDireito, yOlhoDireito, zOlhoDireito;
    'Olho esquerdo', 'body', xOlhoEsquerdo, yOlhoEsquerdo, zOlhoEsquerdo
};
targetSurfaceLabel = 'Tumor olho dto';
targetBodyName = 'Tumor olho dto';
selectedBodyNames = {
    'Tumor olho dto';
    'Olho direito';
    'Olho esquerdo'
};
comparisonBodyNames = {
    'Olho direito';
    'Olho esquerdo'
};
targetIdx = [];
if ~isempty(targetSurfaceLabel) && ~isempty(selectedLabelSpecs)
    targetIdx = find(strcmpi(selectedLabelSpecs(:,1), targetSurfaceLabel), 1);
end
if isempty(targetIdx)
    xT = 0; %#ok<NASGU>
    yT = 0; %#ok<NASGU>
    zT = 0; %#ok<NASGU>
else
    xT = selectedLabelSpecs{targetIdx,3}; %#ok<NASGU>
    yT = selectedLabelSpecs{targetIdx,4}; %#ok<NASGU>
    zT = selectedLabelSpecs{targetIdx,5}; %#ok<NASGU>
end
%__STUDIO_SELECTED_LABELS_END__

% geometrySlicePoints is not used here, but the placeholder is kept so the
% template can be generated from the same Studio data model as the main
% report script.
%__STUDIO_GEOMETRY_SLICES_BEGIN__
geometrySlicePoints = struct(); %#ok<NASGU>
geometrySlicePoints.xy = zeros(0,2);
geometrySlicePoints.xz = zeros(0,2);
geometrySlicePoints.yz = zeros(0,2);
%__STUDIO_GEOMETRY_SLICES_END__

enableAliasReview = true;
maxSummarySeries = 10;

ced = [char(231) char(227)];
grau = char(176);
masterRoot = fileparts(mfilename('fullpath'));
if isempty(masterRoot) || ~exist(masterRoot, 'dir')
    chosenRoot = uigetdir(pwd, 'Select master root for Global_Report');
    if isequal(chosenRoot, 0)
        disp('No master root selected. Exiting Global_Report.');
        return;
    end
    masterRoot = chosenRoot;
end

process_global_report_root_r2015(masterRoot, masterRoot, targetBodyName, comparisonBodyNames, selectedBodyNames, enableAliasReview, maxSummarySeries, ced, grau);
disp('Global_Report finished.');
end

function T = process_global_report_root_r2015(currentRoot, masterRoot, targetBodyName, comparisonBodyNames, selectedBodyNames, enableAliasReview, maxSummarySeries, ced, grau)
disp(['Global_Report: processing root ' currentRoot]);

preparedTotalsPath = fullfile(currentRoot, 'Global_Report_prepared_totals.csv');
preparedContextsPath = fullfile(currentRoot, 'Global_Report_studio_contexts.csv');
if exist(preparedTotalsPath, 'file') && exist(preparedContextsPath, 'file')
    T = load_global_body_totals_csv_r2015(preparedTotalsPath);
    if isempty(T)
        return;
    end
    preferredNames = build_global_preferred_names_r2015(selectedBodyNames, targetBodyName, comparisonBodyNames);

    aliasPath = fullfile(currentRoot, 'Global_Report_component_aliases.csv');
    aliasMap = load_component_alias_map_r2015(aliasPath);
    if enableAliasReview
        aliasMap = prompt_component_aliases_r2015(currentRoot, T, preferredNames, aliasMap);
        write_component_alias_map_r2015(aliasPath, aliasMap);
    end
    archive_existing_global_report_outputs_r2015(currentRoot);
    rawTotals = aggregate_global_totals_r2015(T, {});
    rawTotals = sortrows(rawTotals, {'ContextLabel', 'SourceType', 'Alpha', 'Component'});
    writetable(rawTotals, fullfile(currentRoot, 'Global_Report_body_totals.csv'));

    plotTotals = T;
    if ~isempty(aliasMap)
        plotTotals.Component = apply_component_alias_map_r2015(plotTotals.Component, plotTotals.ContextLabel, aliasMap, preferredNames);
    end
    T = aggregate_global_totals_r2015(plotTotals, preferredNames);
    T = sortrows(T, {'ContextLabel', 'SourceType', 'Alpha', 'Component'});
    keyNames = build_plot_component_names_r2015(preferredNames, T.Component);
    keyTable = filter_key_components_r2015(T, keyNames);
    if ~isempty(keyTable)
        writetable(keyTable, fullfile(currentRoot, 'Global_Report_key_bodies.csv'));
        plot_global_summary_line_r2015(keyTable, keyNames, currentRoot, masterRoot, maxSummarySeries, grau);
        plot_global_component_bars_r2015(keyTable, keyNames, currentRoot, masterRoot, grau);
    end
    return;
end

childDirs = collect_candidate_child_dirs_r2015(currentRoot);
for i = 1:numel(childDirs)
    try
        process_global_report_root_r2015(childDirs{i}, masterRoot, targetBodyName, comparisonBodyNames, selectedBodyNames, enableAliasReview, maxSummarySeries, ced, grau);
    catch ME
        disp(['Global_Report: failed child root ' childDirs{i} ': ' ME.message]);
    end
end

childGlobalFiles = {};
childBatchFiles = {};
for i = 1:numel(childDirs)
    globalPath = fullfile(childDirs{i}, 'Global_Report_body_totals.csv');
    batchPath = fullfile(childDirs{i}, 'body_totals_by_alpha.csv');
    childName = folder_label_r2015(childDirs{i});
    if is_batch_folder_name_r2015(childName) && exist(batchPath, 'file')
        childBatchFiles{end + 1, 1} = batchPath; %#ok<AGROW>
    elseif exist(globalPath, 'file')
        childGlobalFiles{end + 1, 1} = globalPath; %#ok<AGROW>
    elseif exist(batchPath, 'file')
        childBatchFiles{end + 1, 1} = batchPath; %#ok<AGROW>
    end
end

T = empty_global_totals_table_r2015();

for i = 1:numel(childGlobalFiles)
    childTable = load_global_body_totals_csv_r2015(childGlobalFiles{i});
    if ~isempty(childTable)
        T = [T; childTable]; %#ok<AGROW>
    end
end

if ~isempty(childBatchFiles)
    batchTotals = aggregate_batch_children_totals_r2015(childBatchFiles, currentRoot, masterRoot, selectedBodyNames);
    if ~isempty(batchTotals)
        T = [T; batchTotals]; %#ok<AGROW>
    end
end

if isempty(T)
    return;
end

preferredNames = build_global_preferred_names_r2015(selectedBodyNames, targetBodyName, comparisonBodyNames);

aliasPath = fullfile(currentRoot, 'Global_Report_component_aliases.csv');
aliasMap = load_component_alias_map_r2015(aliasPath);
if enableAliasReview
    aliasMap = prompt_component_aliases_r2015(currentRoot, T, preferredNames, aliasMap);
    write_component_alias_map_r2015(aliasPath, aliasMap);
end
archive_existing_global_report_outputs_r2015(currentRoot);
bodyTotalsPath = fullfile(currentRoot, 'Global_Report_body_totals.csv');
rawTotals = aggregate_global_totals_r2015(T, {});
rawTotals = sortrows(rawTotals, {'ContextLabel', 'SourceType', 'Alpha', 'Component'});
writetable(rawTotals, bodyTotalsPath);

plotTotals = T;
if ~isempty(aliasMap)
    plotTotals.Component = apply_component_alias_map_r2015(plotTotals.Component, plotTotals.ContextLabel, aliasMap, preferredNames);
end

T = aggregate_global_totals_r2015(plotTotals, preferredNames);
T = sortrows(T, {'ContextLabel', 'SourceType', 'Alpha', 'Component'});

keyNames = build_plot_component_names_r2015(preferredNames, T.Component);
keyTable = filter_key_components_r2015(T, keyNames);
if ~isempty(keyTable)
    writetable(keyTable, fullfile(currentRoot, 'Global_Report_key_bodies.csv'));
    plot_global_summary_line_r2015(keyTable, keyNames, currentRoot, masterRoot, maxSummarySeries, grau);
    plot_global_component_bars_r2015(keyTable, keyNames, currentRoot, masterRoot, grau);
end
end

function T = aggregate_batch_children_totals_r2015(batchCsvFiles, currentRoot, masterRoot, preferredNames)
merged = empty_global_totals_table_r2015();
for i = 1:numel(batchCsvFiles)
    childTable = load_batch_body_totals_csv_r2015(batchCsvFiles{i});
    if isempty(childTable)
        continue;
    end
    merged = [merged; childTable]; %#ok<AGROW>
end
if isempty(merged)
    T = merged;
    return;
end

contextLabel = context_label_for_root_r2015(currentRoot, masterRoot);
contextCol = repmat({contextLabel}, height(merged), 1);
merged.ContextLabel = contextCol;
if nargin >= 4 && ~isempty(preferredNames)
    merged.Component = replace_component_labels_r2015(merged.Component, preferredNames);
end
T = aggregate_global_totals_r2015(merged, preferredNames);
end

function T = aggregate_global_totals_r2015(Tin, preferredNames)
if isempty(Tin)
    T = empty_global_totals_table_r2015();
    return;
end

contextLabels = cell_column_to_strings_r2015(Tin.ContextLabel);
sourceTypes = cell_column_to_strings_r2015(Tin.SourceType);
components = cell_column_to_strings_r2015(Tin.Component);
alphas = table_column_to_numeric_r2015(Tin.Alpha);
nFields = table_column_to_numeric_r2015(Tin.NFields);
edepEv = table_column_to_numeric_r2015(Tin.Edep_eV);
dEdepEv = table_column_to_numeric_r2015(Tin.dEdep_eV);
doseEvg = table_column_to_numeric_r2015(Tin.Dose_eVg);
dDoseEvg = table_column_to_numeric_r2015(Tin.dDose_eVg);
doseGy = table_column_to_numeric_r2015(Tin.Dose_Gy);
dDoseGy = table_column_to_numeric_r2015(Tin.dDose_Gy);

componentKeys = build_body_key_list_r2015(components);
sourceKeys = sourceTypes;
contextKeys = contextLabels;

 outContext = {};
 outSource = {};
 outAlpha = [];
 outComponent = {};
 outNFields = [];
 outEdepEv = [];
 outdEdepEv = [];
 outDoseEvg = [];
 outdDoseEvg = [];
 outErrPct = [];
 outDoseGy = [];
 outdDoseGy = [];
 uniqueContexts = unique_stable_strings_r2015(contextKeys);
for i = 1:numel(uniqueContexts)
    contextMask = strcmp(contextKeys, uniqueContexts{i});
    uniqueSources = unique_stable_strings_r2015(sourceKeys(contextMask));
    for s = 1:numel(uniqueSources)
        sourceMask = contextMask & strcmp(sourceKeys, uniqueSources{s});
        alphaList = unique(alphas(sourceMask));
        alphaList = alphaList(isfinite(alphaList));
        alphaList = sort(alphaList(:)');
        for a = 1:numel(alphaList)
            alphaMask = sourceMask & (alphas == alphaList(a));
            compKeys = unique_stable_strings_r2015(componentKeys(alphaMask));
            for c = 1:numel(compKeys)
                compMask = alphaMask & strcmp(componentKeys, compKeys{c});
                firstIdx = find(compMask, 1, 'first');
                if isempty(firstIdx)
                    continue;
                end
                doseEvgValue = sum(doseEvg(compMask));
                dDoseEvgValue = sqrt(sum(dDoseEvg(compMask).^2));
                if doseEvgValue ~= 0
                    errPctValue = 100 * dDoseEvgValue / doseEvgValue;
                else
                    errPctValue = NaN;
                end
                outContext{end + 1, 1} = contextLabels{firstIdx}; %#ok<AGROW>
                outSource{end + 1, 1} = normalize_source_type_label_r2015(sourceTypes{firstIdx}); %#ok<AGROW>
                outAlpha(end + 1, 1) = alphaList(a); %#ok<AGROW>
                outComponent{end + 1, 1} = preferred_body_display_label_r2015(components{firstIdx}, preferredNames); %#ok<AGROW>
                outNFields(end + 1, 1) = sum(nFields(compMask)); %#ok<AGROW>
                outEdepEv(end + 1, 1) = sum(edepEv(compMask)); %#ok<AGROW>
                outdEdepEv(end + 1, 1) = sqrt(sum(dEdepEv(compMask).^2)); %#ok<AGROW>
                outDoseEvg(end + 1, 1) = doseEvgValue; %#ok<AGROW>
                outdDoseEvg(end + 1, 1) = dDoseEvgValue; %#ok<AGROW>
                outErrPct(end + 1, 1) = errPctValue; %#ok<AGROW>
                outDoseGy(end + 1, 1) = sum(doseGy(compMask)); %#ok<AGROW>
                outdDoseGy(end + 1, 1) = sqrt(sum(dDoseGy(compMask).^2)); %#ok<AGROW>
            end
        end
    end
end
T = table( ...
    outContext, outSource, outAlpha, outComponent, outNFields, ...
    outEdepEv, outdEdepEv, outDoseEvg, outdDoseEvg, outErrPct, outDoseGy, outdDoseGy, ...
    'VariableNames', { ...
        'ContextLabel', 'SourceType', 'Alpha', 'Component', 'NFields', ...
        'Edep_eV', 'dEdep_eV', 'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy' ...
    });
end

function T = load_batch_body_totals_csv_r2015(path)
raw = readtable(path);
required = {'SourceType', 'Alpha', 'Component', 'NFields', 'Edep_eV', 'dEdep_eV', 'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy'};
assert_required_vars_r2015(path, raw, required);
rowCount = height(raw);
T = table( ...
    repmat({''}, rowCount, 1), ...
    cell_column_to_strings_r2015(raw.SourceType), ...
    table_column_to_numeric_r2015(raw.Alpha), ...
    cell_column_to_strings_r2015(raw.Component), ...
    table_column_to_numeric_r2015(raw.NFields), ...
    table_column_to_numeric_r2015(raw.Edep_eV), ...
    table_column_to_numeric_r2015(raw.dEdep_eV), ...
    table_column_to_numeric_r2015(raw.Dose_eVg), ...
    table_column_to_numeric_r2015(raw.dDose_eVg), ...
    table_column_to_numeric_r2015(raw.Error_pct), ...
    table_column_to_numeric_r2015(raw.Dose_Gy), ...
    table_column_to_numeric_r2015(raw.dDose_Gy), ...
    'VariableNames', { ...
        'ContextLabel', 'SourceType', 'Alpha', 'Component', 'NFields', ...
        'Edep_eV', 'dEdep_eV', 'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy' ...
    });
end

function T = load_global_body_totals_csv_r2015(path)
raw = readtable(path);
required = {'ContextLabel', 'SourceType', 'Alpha', 'Component', 'NFields', 'Edep_eV', 'dEdep_eV', 'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy'};
assert_required_vars_r2015(path, raw, required);
T = table( ...
    cell_column_to_strings_r2015(raw.ContextLabel), ...
    cell_column_to_strings_r2015(raw.SourceType), ...
    table_column_to_numeric_r2015(raw.Alpha), ...
    cell_column_to_strings_r2015(raw.Component), ...
    table_column_to_numeric_r2015(raw.NFields), ...
    table_column_to_numeric_r2015(raw.Edep_eV), ...
    table_column_to_numeric_r2015(raw.dEdep_eV), ...
    table_column_to_numeric_r2015(raw.Dose_eVg), ...
    table_column_to_numeric_r2015(raw.dDose_eVg), ...
    table_column_to_numeric_r2015(raw.Error_pct), ...
    table_column_to_numeric_r2015(raw.Dose_Gy), ...
    table_column_to_numeric_r2015(raw.dDose_Gy), ...
    'VariableNames', { ...
        'ContextLabel', 'SourceType', 'Alpha', 'Component', 'NFields', ...
        'Edep_eV', 'dEdep_eV', 'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy' ...
    });
end

function T = filter_key_components_r2015(Tin, keyNames)
if isempty(Tin)
    T = Tin;
    return;
end
keyKeys = build_body_key_list_r2015(keyNames);
componentKeys = build_body_key_list_r2015(Tin.Component);
keepMask = false(height(Tin), 1);
for i = 1:numel(keyKeys)
    keepMask = keepMask | strcmp(componentKeys, keyKeys{i});
end
T = Tin(keepMask, :);
if ~isempty(T)
    T.Component = replace_component_labels_r2015(T.Component, keyNames);
end
end

function plot_global_summary_line_r2015(K, keyNames, currentRoot, masterRoot, maxSummarySeries, grau)
seriesInfo = unique_context_source_alpha_rows_r2015(K, currentRoot, masterRoot);
if height(seriesInfo) > maxSummarySeries
    disp(['Global_Report: skipping summary line plot in ', currentRoot, ' because there are ', num2str(height(seriesInfo)), ' series.']);
    return;
end

legendSeed = cell(height(seriesInfo), 1);
for i = 1:height(seriesInfo)
    legendSeed{i} = sprintf('%s | alpha = %.4g%c', seriesInfo.DisplayLabel{i}, seriesInfo.Alpha(i), grau);
end
plotWidth = max(860, 150 * numel(keyNames));
legendWidth = max(460, 7 * max_cell_string_length_r2015(legendSeed) + 120);
figWidth = plotWidth + legendWidth + 140;
fig = figure('Color', 'w', 'Position', [100, 100, figWidth, 580]);
ax = axes('Parent', fig, 'Position', [0.08 0.14 0.60 0.78]);
hold(ax, 'on');
legendLabels = {};

for i = 1:height(seriesInfo)
    rowMask = strcmp(K.ContextLabel, seriesInfo.ContextLabel{i}) & ...
              strcmp(K.SourceType, seriesInfo.SourceType{i}) & ...
              K.Alpha == seriesInfo.Alpha(i);
    Ka = K(rowMask, :);
    orderedIdx = zeros(numel(keyNames), 1);
    for j = 1:numel(keyNames)
        matchIdx = find_component_row_r2015(Ka.Component, keyNames{j});
        if ~isempty(matchIdx)
            orderedIdx(j) = matchIdx;
        end
    end
    xVals = find(orderedIdx > 0);
    if isempty(xVals)
        continue;
    end
    Ka = Ka(orderedIdx(xVals), :);
    errorbar(ax, xVals, Ka.Dose_eVg, Ka.dDose_eVg, 'o-');
    legendLabels{end + 1, 1} = sprintf('%s | alpha = %.4g%c', seriesInfo.DisplayLabel{i}, seriesInfo.Alpha(i), grau); %#ok<AGROW>
end

set(ax, 'YScale', 'log', 'XTick', 1:numel(keyNames), 'XTickLabel', keyNames);
try
    set(ax, 'XTickLabelRotation', 25);
catch
end
xlim([0.5, numel(keyNames) + 0.5]);
ylabel('Dose total somada (eV/g)');
title(sprintf('Global_Report: dose total por corpo selecionado (%s)', folder_label_r2015(currentRoot)), 'Interpreter', 'none');
grid on;
if ~isempty(legendLabels)
    lgd = legend(ax, legendLabels, 'Location', 'eastoutside', 'Interpreter', 'none');
    apply_global_right_legend_layout_r2015(ax, lgd, [0.08 0.14 0.60 0.78], 0.72);
end
drawnow;
saveas(fig, fullfile(currentRoot, 'Global_Report_key_bodies_by_series.png'));
close(fig);
end

function plot_global_component_bars_r2015(K, keyNames, currentRoot, masterRoot, grau)
alphaList = unique(K.Alpha);
alphaList = alphaList(isfinite(alphaList));
alphaList = sort(alphaList(:)');
if isempty(K) || isempty(alphaList)
    return;
end

keyNames = build_plot_component_names_r2015(keyNames, K.Component);
if isempty(keyNames)
    return;
end

componentKeysAll = build_body_key_list_r2015(K.Component);
familyLabels = cell(numel(keyNames), 1);
for i = 1:numel(keyNames)
    familyLabels{i} = component_family_label_r2015(keyNames{i});
end
uniqueFamilies = unique_stable_strings_r2015(familyLabels);

for f = 1:numel(uniqueFamilies)
    memberMask = strcmp(familyLabels, uniqueFamilies{f});
    memberNames = keyNames(memberMask);
    if isempty(memberNames)
        continue;
    end

    if numel(memberNames) > 1
        memberKeys = build_body_key_list_r2015(memberNames);
        familyMask = false(height(K), 1);
        for m = 1:numel(memberKeys)
            familyMask = familyMask | strcmp(componentKeysAll, memberKeys{m});
        end
        Kfamily = K(familyMask, :);
        plot_global_component_family_r2015(Kfamily, memberNames, uniqueFamilies{f}, currentRoot, masterRoot, grau);
        continue;
    end

    compName = memberNames{1};
    compKey = normalize_body_compare_key_r2015(compName);
    compMask = strcmp(componentKeysAll, compKey);
    Kc = K(compMask, :);
    if isempty(Kc)
        continue;
    end

    seriesInfo = unique_context_source_rows_r2015(Kc, currentRoot, masterRoot);
    if isempty(seriesInfo)
        continue;
    end

    y = nan(height(seriesInfo), numel(alphaList));
    e = nan(height(seriesInfo), numel(alphaList));
    for i = 1:height(seriesInfo)
        for a = 1:numel(alphaList)
            rowMask = strcmp(Kc.ContextLabel, seriesInfo.ContextLabel{i}) & ...
                      strcmp(Kc.SourceType, seriesInfo.SourceType{i}) & ...
                      Kc.Alpha == alphaList(a);
            idx = find(rowMask, 1, 'first');
            if isempty(idx)
                continue;
            end
            y(i, a) = Kc.Dose_eVg(idx);
            e(i, a) = Kc.dDose_eVg(idx);
        end
    end

    validRows = any(isfinite(y), 2);
    if ~any(validRows)
        continue;
    end
    y = y(validRows, :);
    e = e(validRows, :);
    seriesInfo = seriesInfo(validRows, :);

    if height(seriesInfo) == 1
        plot_global_component_single_context_r2015(compName, y(1, :), e(1, :), alphaList, seriesInfo.DisplayLabel{1}, currentRoot, grau);
        continue;
    end

    if numel(alphaList) == 1
        plot_global_component_single_alpha_r2015(compName, y(:, 1), e(:, 1), seriesInfo.DisplayLabel, alphaList(1), currentRoot, grau);
        continue;
    end

    plotWidth = max(900, 140 * height(seriesInfo));
    legendWidth = max(260, 150 * numel(alphaList));
    figWidth = plotWidth + legendWidth + 140;
    fig = figure('Color', 'w', 'Position', [100, 100, figWidth, 620]);
    ax = axes('Parent', fig, 'Position', [0.08 0.14 0.64 0.78]);
    bar(ax, y, 'grouped');
    hold(ax, 'on');
    groupWidth = min(0.8, numel(alphaList) / (numel(alphaList) + 1.5));
    for a = 1:numel(alphaList)
        x = (1:height(seriesInfo)) - groupWidth/2 + (2 * a - 1) * groupWidth / (2 * numel(alphaList));
        valid = isfinite(y(:, a)) & isfinite(e(:, a));
        if any(valid)
            errorbar(ax, x(valid), y(valid, a), e(valid, a), 'k', 'LineStyle', 'none', 'LineWidth', 1.1);
        end
    end
    hold(ax, 'off');
    set(ax, 'XTick', 1:height(seriesInfo), 'XTickLabel', seriesInfo.DisplayLabel);
    try
        set(ax, 'XTickLabelRotation', 25);
    catch
    end
    apply_global_component_axis_scale_r2015(ax, y(:), e(:));
    ylabel('Dose total somada (eV/g)');
    xlabel('Contexto / fonte');
    title(sprintf('Global_Report: %s por contexto (%s)', compName, folder_label_r2015(currentRoot)), 'Interpreter', 'none');
    lgd = legend(ax, build_alpha_legend_r2015(alphaList, grau), 'Location', 'eastoutside');
    apply_global_right_legend_layout_r2015(ax, lgd, [0.08 0.14 0.64 0.78], 0.76);
    grid on;
    drawnow;
    saveas(fig, fullfile(currentRoot, ['Global_Report_component_' safe_label_file_token_r2015(compName) '_by_context.png']));
    close(fig);
end
end

function plot_global_component_family_r2015(Kf, memberNames, familyLabel, currentRoot, masterRoot, grau)
if isempty(Kf) || isempty(memberNames)
    return;
end

seriesInfo = unique_context_source_alpha_rows_r2015(Kf, currentRoot, masterRoot);
if isempty(seriesInfo)
    return;
end

memberNames = build_plot_component_names_r2015(memberNames, Kf.Component);
if numel(memberNames) < 2
    return;
end

componentKeys = build_body_key_list_r2015(Kf.Component);
y = nan(numel(memberNames), height(seriesInfo));
e = nan(numel(memberNames), height(seriesInfo));

for m = 1:numel(memberNames)
    memberKey = normalize_body_compare_key_r2015(memberNames{m});
    for s = 1:height(seriesInfo)
        rowMask = strcmp(componentKeys, memberKey) & ...
                  strcmp(Kf.ContextLabel, seriesInfo.ContextLabel{s}) & ...
                  strcmp(Kf.SourceType, seriesInfo.SourceType{s}) & ...
                  Kf.Alpha == seriesInfo.Alpha(s);
        idx = find(rowMask, 1, 'first');
        if isempty(idx)
            continue;
        end
        y(m, s) = Kf.Dose_eVg(idx);
        e(m, s) = Kf.dDose_eVg(idx);
    end
end

validMembers = any(isfinite(y), 2);
validSeries = any(isfinite(y), 1);
if ~any(validMembers) || ~any(validSeries)
    return;
end

memberNames = memberNames(validMembers);
y = y(validMembers, validSeries);
e = e(validMembers, validSeries);
seriesInfo = seriesInfo(validSeries, :);

legendLabels = build_context_source_alpha_legend_r2015(seriesInfo, grau);
plotWidth = max(940, 180 * numel(memberNames));
legendWidth = max(460, 7 * max_cell_string_length_r2015(legendLabels) + 120);
figWidth = plotWidth + legendWidth + 140;
fig = figure('Color', 'w', 'Position', [100, 100, figWidth, 620]);
ax = axes('Parent', fig, 'Position', [0.08 0.14 0.60 0.78]);
bar(ax, y, 'grouped');
hold(ax, 'on');
groupWidth = min(0.8, height(seriesInfo) / (height(seriesInfo) + 1.5));
for s = 1:height(seriesInfo)
    x = (1:numel(memberNames)) - groupWidth/2 + (2 * s - 1) * groupWidth / (2 * height(seriesInfo));
    valid = isfinite(y(:, s)) & isfinite(e(:, s));
    if any(valid)
        errorbar(ax, x(valid), y(valid, s), e(valid, s), 'k', 'LineStyle', 'none', 'LineWidth', 1.1);
    end
end
hold(ax, 'off');
set(ax, 'XTick', 1:numel(memberNames), 'XTickLabel', memberNames);
try
    set(ax, 'XTickLabelRotation', 20);
catch
end
apply_global_component_axis_scale_r2015(ax, y(:), e(:));
ylabel('Dose total somada (eV/g)');
xlabel('Componente');
title(sprintf('Global_Report: %s por contexto (%s)', familyLabel, folder_label_r2015(currentRoot)), 'Interpreter', 'none');
lgd = legend(ax, legendLabels, 'Location', 'eastoutside', 'Interpreter', 'none');
apply_global_right_legend_layout_r2015(ax, lgd, [0.08 0.14 0.60 0.78], 0.72);
grid on;
drawnow;
saveas(fig, fullfile(currentRoot, ['Global_Report_component_' safe_label_file_token_r2015(familyLabel) '_by_context.png']));
close(fig);
end


function plot_global_component_single_context_r2015(compName, yRow, eRow, alphaList, displayLabel, currentRoot, grau)
valid = isfinite(yRow);
if ~any(valid)
    return;
end

alphaVals = alphaList(valid);
yVals = yRow(valid);
eVals = eRow(valid);
figWidth = max(980, 180 * numel(alphaVals) + 260);
fig = figure('Color', 'w', 'Position', [100, 100, figWidth, 620]);
bar(1:numel(alphaVals), yVals, 0.6, 'FaceColor', [0.26, 0.20, 0.60], 'EdgeColor', [0.10, 0.10, 0.10], 'LineWidth', 1.0);
hold on;
validErr = isfinite(eVals);
if any(validErr)
    errorbar(find(validErr), yVals(validErr), eVals(validErr), 'k', 'LineStyle', 'none', 'LineWidth', 1.1);
end
hold off;
set(gca, 'XTick', 1:numel(alphaVals), 'XTickLabel', build_alpha_legend_r2015(alphaVals, grau));
apply_global_component_axis_scale_r2015(gca, yVals(:), eVals(:));
ylabel('Dose total somada (eV/g)');
xlabel('Alpha');
title(sprintf('Global_Report: %s por alpha (%s)', compName, displayLabel), 'Interpreter', 'none');
grid on;
saveas(fig, fullfile(currentRoot, ['Global_Report_component_' safe_label_file_token_r2015(compName) '_by_context.png']));
close(fig);
end

function plot_global_component_single_alpha_r2015(compName, yCol, eCol, displayLabels, alphaValue, currentRoot, grau)
valid = isfinite(yCol);
if ~any(valid)
    return;
end

displayLabels = displayLabels(valid);
yVals = yCol(valid);
eVals = eCol(valid);
figWidth = max(1220, 140 * numel(yVals) + 260);
fig = figure('Color', 'w', 'Position', [100, 100, figWidth, 620]);
bar(1:numel(yVals), yVals, 0.6, 'FaceColor', [0.26, 0.20, 0.60], 'EdgeColor', [0.10, 0.10, 0.10], 'LineWidth', 1.0);
hold on;
validErr = isfinite(eVals);
if any(validErr)
    errorbar(find(validErr), yVals(validErr), eVals(validErr), 'k', 'LineStyle', 'none', 'LineWidth', 1.1);
end
hold off;
set(gca, 'XTick', 1:numel(yVals), 'XTickLabel', displayLabels);
try
    set(gca, 'XTickLabelRotation', 25);
catch
end
apply_global_component_axis_scale_r2015(gca, yVals(:), eVals(:));
ylabel('Dose total somada (eV/g)');
xlabel('Contexto / fonte');
title(sprintf('Global_Report: %s por contexto (alpha = %.4g%c, %s)', compName, alphaValue, grau, folder_label_r2015(currentRoot)), 'Interpreter', 'none');
grid on;
saveas(fig, fullfile(currentRoot, ['Global_Report_component_' safe_label_file_token_r2015(compName) '_by_context.png']));
close(fig);
end

function apply_global_component_axis_scale_r2015(ax, yVals, eVals)
if nargin < 3
    eVals = zeros(size(yVals));
end

yVals = yVals(:);
eVals = eVals(:);
valid = isfinite(yVals) & yVals > 0;
if ~any(valid)
    return;
end

yVals = yVals(valid);
eVals = eVals(valid);
if isempty(eVals)
    eVals = zeros(size(yVals));
elseif numel(eVals) ~= numel(yVals)
    eVals = zeros(size(yVals));
end

positiveVals = yVals(yVals > 0);
if isempty(positiveVals)
    return;
end

spreadRatio = max(positiveVals) / max(min(positiveVals), eps);
if spreadRatio >= 50
    set(ax, 'YScale', 'log');
    return;
end

set(ax, 'YScale', 'linear');
lowVals = yVals - eVals;
highVals = yVals + eVals;
yMin = min(lowVals);
yMax = max(highVals);
if ~isfinite(yMin) || ~isfinite(yMax)
    return;
end
if yMin == yMax
    pad = max(abs(yMax) * 0.08, 1);
else
    pad = 0.08 * (yMax - yMin);
end
ylim(ax, [max(0, yMin - pad), yMax + pad]);
end

function out = build_alpha_legend_r2015(alphaList, grau)
out = cell(numel(alphaList), 1);
for i = 1:numel(alphaList)
    out{i} = sprintf('alpha = %.4g%c', alphaList(i), grau);
end
end

function apply_global_right_legend_layout_r2015(ax, lgd, axPos, legendLeft)
if nargin < 4
    legendLeft = 0.74;
end
if nargin < 3 || isempty(axPos)
    axPos = [0.08 0.14 0.62 0.78];
end
if ~ishandle(ax) || ~ishandle(lgd)
    return;
end
set(ax, 'Units', 'normalized');
set(ax, 'Position', axPos);
drawnow;
set(lgd, 'Units', 'normalized');
lgdPos = get(lgd, 'Position');
legendWidth = min(0.26, max(0.18, lgdPos(3)));
legendHeight = min(0.70, max(0.12, lgdPos(4)));
if legendHeight > 0.42
    bottomLegendHeight = min(0.22, max(0.10, lgdPos(4)));
    set(ax, 'Position', [axPos(1) 0.28 axPos(3) + 0.14 0.62]);
    set(lgd, 'Position', [0.10 0.04 0.80 bottomLegendHeight]);
    return;
end
legendBottom = max(0.14, min(0.90 - legendHeight, axPos(2) + 0.5 * (axPos(4) - legendHeight)));
set(lgd, 'Position', [legendLeft legendBottom legendWidth legendHeight]);
end

function out = max_cell_string_length_r2015(values)
values = cell_column_to_strings_r2015(values);
out = 0;
for i = 1:numel(values)
    out = max(out, numel(values{i}));
end
end

function info = unique_context_source_alpha_rows_r2015(K, currentRoot, masterRoot)
contextLabels = K.ContextLabel;
sourceTypes = K.SourceType;
alphas = K.Alpha;
outContext = {};
outSource = {};
outAlpha = [];
outDisplay = {};
uniqueContexts = unique_stable_strings_r2015(contextLabels);
for i = 1:numel(uniqueContexts)
    contextMask = strcmp(contextLabels, uniqueContexts{i});
    uniqueSources = unique_stable_strings_r2015(sourceTypes(contextMask));
    for s = 1:numel(uniqueSources)
        sourceMask = contextMask & strcmp(sourceTypes, uniqueSources{s});
        alphaList = unique(alphas(sourceMask));
        alphaList = alphaList(isfinite(alphaList));
        alphaList = sort(alphaList(:)');
        for a = 1:numel(alphaList)
            outContext{end + 1, 1} = uniqueContexts{i}; %#ok<AGROW>
            outSource{end + 1, 1} = uniqueSources{s}; %#ok<AGROW>
            outAlpha(end + 1, 1) = alphaList(a); %#ok<AGROW>
            outDisplay{end + 1, 1} = display_context_source_label_r2015(uniqueContexts{i}, uniqueSources{s}, currentRoot, masterRoot); %#ok<AGROW>
        end
    end
end
info = table(outContext, outSource, outAlpha, outDisplay, 'VariableNames', {'ContextLabel', 'SourceType', 'Alpha', 'DisplayLabel'});
end

function info = unique_context_source_rows_r2015(K, currentRoot, masterRoot)
contextLabels = K.ContextLabel;
sourceTypes = K.SourceType;
outContext = {};
outSource = {};
outDisplay = {};
uniqueContexts = unique_stable_strings_r2015(contextLabels);
for i = 1:numel(uniqueContexts)
    contextMask = strcmp(contextLabels, uniqueContexts{i});
    uniqueSources = unique_stable_strings_r2015(sourceTypes(contextMask));
    for s = 1:numel(uniqueSources)
        outContext{end + 1, 1} = uniqueContexts{i}; %#ok<AGROW>
        outSource{end + 1, 1} = uniqueSources{s}; %#ok<AGROW>
        outDisplay{end + 1, 1} = display_context_source_label_r2015(uniqueContexts{i}, uniqueSources{s}, currentRoot, masterRoot); %#ok<AGROW>
    end
end
info = table(outContext, outSource, outDisplay, 'VariableNames', {'ContextLabel', 'SourceType', 'DisplayLabel'});
end

function label = display_context_source_label_r2015(contextLabel, sourceType, currentRoot, masterRoot)
contextDisplay = display_context_label_r2015(contextLabel, currentRoot, masterRoot);
sourceDisplay = display_source_type_r2015(sourceType);
contextKey = normalize_body_compare_key_r2015(contextDisplay);
sourceKey = normalize_body_compare_key_r2015(sourceDisplay);
if isempty(contextDisplay)
    label = sourceDisplay;
elseif isempty(sourceDisplay)
    label = contextDisplay;
elseif ~isempty(strfind(contextKey, sourceKey))
    label = contextDisplay;
else
    label = [contextDisplay ' | ' sourceDisplay];
end
end

function label = display_context_label_r2015(contextLabel, currentRoot, masterRoot)
contextLabel = strtrim(contextLabel);
currentLabel = context_label_for_root_r2015(currentRoot, masterRoot);
if strcmp(contextLabel, currentLabel)
    label = folder_label_r2015(currentRoot);
    return;
end
prefix = [currentLabel ' | '];
if numel(contextLabel) > numel(prefix) && strcmp(contextLabel(1:numel(prefix)), prefix)
    label = contextLabel(numel(prefix) + 1:end);
else
    label = contextLabel;
end
end

function label = context_label_for_root_r2015(currentRoot, masterRoot)
currentRoot = char(currentRoot);
masterRoot = char(masterRoot);
if strcmpi(currentRoot, masterRoot)
    label = folder_label_r2015(currentRoot);
    return;
end
prefix = [masterRoot filesep];
if numel(currentRoot) >= numel(prefix) && strcmpi(currentRoot(1:numel(prefix)), prefix)
    relPath = currentRoot(numel(prefix) + 1:end);
else
    relPath = currentRoot;
end
parts = regexp(relPath, '[\\/]', 'split');
parts = parts(~cellfun(@isempty, parts));
if isempty(parts)
    label = folder_label_r2015(currentRoot);
else
    label = strjoin(parts, ' | ');
end
end

function label = folder_label_r2015(pathValue)
[~, label] = fileparts(pathValue);
if isempty(label)
    label = pathValue;
end
end

function aliasMap = prompt_component_aliases_r2015(currentRoot, totalsTable, preferredNames, existingAliasMap)
if isempty(totalsTable) || ~ismember('ContextLabel', totalsTable.Properties.VariableNames) || ~ismember('Component', totalsTable.Properties.VariableNames)
    aliasMap = {};
    return;
end
if nargin < 4
    existingAliasMap = {};
end

contextLabels = cell_column_to_strings_r2015(totalsTable.ContextLabel);
components = cell_column_to_strings_r2015(totalsTable.Component);
contextGroups = alias_group_for_context_r2015(contextLabels, currentRoot);
rowPairs = unique_context_component_pairs_r2015(contextGroups, components);
if isempty(rowPairs)
    aliasMap = {};
    return;
end

tableData = cell(size(rowPairs, 1), 3);
for r = 1:size(rowPairs, 1)
    groupLabel = rowPairs{r, 1};
    detectedLabel = rowPairs{r, 2};
    overrideLabel = lookup_alias_override_r2015(existingAliasMap, groupLabel, detectedLabel);
    if strcmp(normalize_body_compare_key_r2015(detectedLabel), normalize_body_compare_key_r2015(overrideLabel))
        overrideLabel = '';
    end
    tableData{r, 1} = groupLabel;
    tableData{r, 2} = detectedLabel;
    tableData{r, 3} = overrideLabel;
end

result.accepted = false;
result.data = tableData;

columnNames = {'Geometry / context', 'Detected component', 'Override label (optional)'};
columnEditable = [false false true];
columnWidths = {180 220 240};

figWidth = 900;
figHeight = 560;
margin = 20;
buttonGap = 10;
okWidth = 90;
skipWidth = 90;
buttonHeight = 34;
buttonY = 20;
skipX = figWidth - margin - skipWidth;
okX = skipX - buttonGap - okWidth;
tableY = 80;
tableHeight = 430;
tableWidth = figWidth - 2 * margin;
instructionHeight = 36;
instructionY = figHeight - margin - instructionHeight;

fig = figure( ...
    'Name', ['Global_Report BODY labels - ' folder_label_r2015(currentRoot)], ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', 'w', ...
    'WindowStyle', 'modal', ...
    'Position', [120 120 figWidth figHeight], ...
    'CloseRequestFcn', @onCancel);

uicontrol( ...
    'Parent', fig, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w', ...
    'Position', [margin instructionY tableWidth instructionHeight], ...
    'String', sprintf(['Review BODY labels for this level. Leave Override label empty to keep the original name.\n' ...
                       'Use the same Override label for matching organs across geometries, for example Mioleira -> C%c rebro.'], char(233)));

tbl = uitable( ...
    'Parent', fig, ...
    'Data', tableData, ...
    'ColumnName', columnNames, ...
    'ColumnEditable', columnEditable, ...
    'ColumnWidth', columnWidths, ...
    'RowName', [], ...
    'Position', [margin tableY tableWidth tableHeight]);

uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'OK', ...
    'Position', [okX buttonY okWidth buttonHeight], ...
    'Callback', @onOk);

uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Skip', ...
    'Position', [skipX buttonY skipWidth buttonHeight], ...
    'Callback', @onCancel);

uiwait(fig);

if ishandle(fig)
    delete(fig);
end

if result.accepted
    aliasMap = alias_map_from_review_table_r2015(result.data);
else
    aliasMap = existingAliasMap;
end

    function onOk(~, ~)
        result.data = get(tbl, 'Data');
        result.accepted = true;
        uiresume(fig);
    end

    function onCancel(~, ~)
        result.accepted = false;
        uiresume(fig);
    end
end

function aliasMap = alias_map_from_review_table_r2015(tableData)
aliasMap = {};
if nargin < 1 || isempty(tableData)
    return;
end
for r = 1:size(tableData, 1)
    groupLabel = strtrim(char(tableData{r, 1}));
    detected = strtrim(char(tableData{r, 2}));
    canonical = strtrim(char(tableData{r, 3}));
    if isempty(groupLabel) || isempty(detected) || isempty(canonical)
        continue;
    end
    if strcmp(detected, canonical)
        continue;
    end
    aliasMap(end + 1, :) = {groupLabel, detected, canonical}; %#ok<AGROW>
end
end

function canonical = lookup_alias_override_r2015(aliasMap, groupLabel, detectedLabel)
canonical = '';
if isempty(aliasMap) || nargin < 3 || isempty(detectedLabel)
    return;
end
detectedKey = normalize_body_compare_key_r2015(detectedLabel);
groupKey = normalize_body_compare_key_r2015(groupLabel);
for i = 1:size(aliasMap, 1)
    aliasGroupKey = '';
    if size(aliasMap, 2) >= 3
        aliasGroupKey = normalize_body_compare_key_r2015(aliasMap{i, 1});
        aliasDetected = aliasMap{i, 2};
        aliasCanonical = aliasMap{i, 3};
    else
        aliasDetected = aliasMap{i, 1};
        aliasCanonical = aliasMap{i, 2};
    end
    if strcmp(normalize_body_compare_key_r2015(aliasDetected), detectedKey) && strcmp(aliasGroupKey, groupKey)
        canonical = strtrim(char(aliasCanonical));
        return;
    end
end
for i = 1:size(aliasMap, 1)
    if size(aliasMap, 2) >= 3
        aliasGroupKey = normalize_body_compare_key_r2015(aliasMap{i, 1});
        aliasDetected = aliasMap{i, 2};
        aliasCanonical = aliasMap{i, 3};
        if ~isempty(aliasGroupKey)
            continue;
        end
    else
        aliasDetected = aliasMap{i, 1};
        aliasCanonical = aliasMap{i, 2};
    end
    if strcmp(normalize_body_compare_key_r2015(aliasDetected), detectedKey)
        canonical = strtrim(char(aliasCanonical));
        return;
    end
end
end

function out = unique_alias_group_labels_r2015(contextLabels, currentRoot)
groupLabels = alias_group_for_context_r2015(contextLabels, currentRoot);
out = unique_stable_strings_r2015(groupLabels);
end

function groups = alias_group_for_context_r2015(contextLabels, currentRoot)
contextLabels = cell_column_to_strings_r2015(contextLabels);
groups = cell(size(contextLabels));
defaultLabel = folder_label_r2015(currentRoot);
for i = 1:numel(contextLabels)
    label = strtrim(contextLabels{i});
    if isempty(label)
        groups{i} = defaultLabel;
        continue;
    end
    parts = regexp(label, '\s+\|\s+', 'split');
    if isempty(parts)
        groups{i} = label;
    else
        groups{i} = strtrim(parts{1});
        if isempty(groups{i})
            groups{i} = defaultLabel;
        end
    end
end
groups = groups(:);
end

function aliasMap = load_component_alias_map_r2015(path)
aliasMap = {};
if nargin < 1 || isempty(path) || ~exist(path, 'file')
    return;
end
try
    raw = readtable(path);
    if all(ismember({'ContextGroup', 'DetectedComponent', 'OverrideLabel'}, raw.Properties.VariableNames))
        groups = cell_column_to_strings_r2015(raw.ContextGroup);
        detected = cell_column_to_strings_r2015(raw.DetectedComponent);
        canonical = cell_column_to_strings_r2015(raw.OverrideLabel);
        aliasMap = [groups(:), detected(:), canonical(:)];
        return;
    end
    if ~all(ismember({'DetectedComponent', 'CanonicalComponent'}, raw.Properties.VariableNames))
        return;
    end
    detected = cell_column_to_strings_r2015(raw.DetectedComponent);
    canonical = cell_column_to_strings_r2015(raw.CanonicalComponent);
    aliasMap = [repmat({''}, numel(detected), 1), detected(:), canonical(:)];
catch
    aliasMap = {};
end
end

function write_component_alias_map_r2015(path, aliasMap)
if nargin < 2 || isempty(path)
    return;
end
if isempty(aliasMap)
    groups = cell(0, 1);
    detected = cell(0, 1);
    canonical = cell(0, 1);
else
    groups = aliasMap(:, 1);
    detected = aliasMap(:, 2);
    canonical = aliasMap(:, 3);
end
T = table(groups, detected, canonical, 'VariableNames', {'ContextGroup', 'DetectedComponent', 'OverrideLabel'});
writetable(T, path);
end

function components = apply_component_alias_map_r2015(components, contextLabels, aliasMap, preferredNames)
components = cell_column_to_strings_r2015(components);
contextLabels = cell_column_to_strings_r2015(contextLabels);
if isempty(aliasMap)
    return;
end
contextGroups = alias_group_for_context_r2015(contextLabels, '');
for i = 1:numel(components)
    overrideLabel = lookup_alias_override_r2015(aliasMap, contextGroups{i}, components{i});
    if ~isempty(overrideLabel)
        components{i} = overrideLabel;
    end
    components{i} = preferred_body_display_label_r2015(components{i}, preferredNames);
end
end

function pairs = unique_context_component_pairs_r2015(contextGroups, components)
contextGroups = cell_column_to_strings_r2015(contextGroups);
components = cell_column_to_strings_r2015(components);
pairs = cell(0, 2);
seen = {};
for i = 1:numel(components)
    groupLabel = strtrim(contextGroups{i});
    detectedLabel = strtrim(components{i});
    if isempty(detectedLabel)
        continue;
    end
    pairKey = [normalize_body_compare_key_r2015(groupLabel) '|' normalize_body_compare_key_r2015(detectedLabel)];
    if any(strcmp(seen, pairKey))
        continue;
    end
    seen{end + 1, 1} = pairKey; %#ok<AGROW>
    pairs(end + 1, :) = {groupLabel, detectedLabel}; %#ok<AGROW>
end
end

function assert_required_vars_r2015(path, T, required)
missing = {};
for i = 1:numel(required)
    if ~ismember(required{i}, T.Properties.VariableNames)
        missing{end + 1, 1} = required{i}; %#ok<AGROW>
    end
end
if ~isempty(missing)
    error('Missing required columns in %s: %s', path, strjoin(missing, ', '));
end
end

function values = table_column_to_numeric_r2015(col)
if isnumeric(col)
    values = col(:);
    return;
end
if iscell(col)
    values = cell_column_to_numeric_r2015(col);
    return;
end
values = nan(numel(col), 1);
for i = 1:numel(col)
    values(i) = str2double(strtrim(char(col(i))));
end
values = values(:);
end

function values = cell_column_to_numeric_r2015(col)
values = nan(numel(col), 1);
for i = 1:numel(col)
    item = col{i};
    if isnumeric(item)
        if ~isempty(item)
            values(i) = item(1);
        end
    elseif ischar(item)
        temp = str2double(strrep(strrep(strtrim(item), 'D', 'E'), 'd', 'e'));
        if ~isnan(temp)
            values(i) = temp;
        end
    end
end
end

function values = cell_column_to_strings_r2015(col)
if ischar(col)
    if size(col, 1) <= 1
        values = {repair_mojibake_text_r2015(strtrim(col))};
    else
        values = cellstr(col);
        for idx = 1:numel(values)
            values{idx} = repair_mojibake_text_r2015(strtrim(values{idx}));
        end
        values = values(:);
    end
    return;
end
if ~iscell(col)
    col = num2cell(col);
end
values = cell(size(col));
for i = 1:numel(col)
    item = col{i};
    if ischar(item)
        values{i} = repair_mojibake_text_r2015(strtrim(item));
    elseif isnumeric(item)
        if isempty(item) || isnan(item)
            values{i} = '';
        else
            values{i} = repair_mojibake_text_r2015(strtrim(num2str(item)));
        end
    else
        values{i} = '';
    end
end
values = values(:);
end

function values = repair_mojibake_cellstrs_r2015(values)
values = cell_column_to_strings_r2015(values);
for i = 1:numel(values)
    values{i} = repair_mojibake_text_r2015(values{i});
end
end

function text = repair_mojibake_text_r2015(text)
if nargin < 1 || isempty(text) || ~ischar(text)
    return;
end
replacements = { ...
    'ÃƒÂ§', char(231); ...
    'ÃƒÂ£', char(227); ...
    'ÃƒÂ¡', char(225); ...
    'ÃƒÂ©', char(233); ...
    'ÃƒÂª', char(234); ...
    'ÃƒÂ­', char(237); ...
    'ÃƒÂ³', char(243); ...
    'ÃƒÂµ', char(245); ...
    'ÃƒÂº', char(250); ...
    'Ã§', char(231); ...
    'Ã£', char(227); ...
    'Ã¡', char(225); ...
    'Ã©', char(233); ...
    'Ãª', char(234); ...
    'Ã­', char(237); ...
    'Ã³', char(243); ...
    'Ãµ', char(245); ...
    'Ãº', char(250); ...
    'Ã‡', char(199); ...
    'Ãƒâ€¡', char(199); ...
    'Ãƒâ€°', char(201); ...
    'Ã‰', char(201) ...
};
for i = 1:size(replacements, 1)
    text = strrep(text, replacements{i, 1}, replacements{i, 2});
end
end

function out = unique_stable_strings_r2015(values)
values = cell_column_to_strings_r2015(values);
out = {};
seenKeys = {};
for i = 1:numel(values)
    current = values{i};
    currentKey = ['__' strtrim(current)];
    duplicate = false;
    for j = 1:numel(seenKeys)
        if strcmp(seenKeys{j}, currentKey)
            duplicate = true;
            break;
        end
    end
    if ~duplicate
        out{end + 1, 1} = current; %#ok<AGROW>
        seenKeys{end + 1, 1} = currentKey; %#ok<AGROW>
    end
end
end

function T = empty_global_totals_table_r2015()
T = table( ...
    cell(0,1), cell(0,1), [], cell(0,1), [], [], [], [], [], [], [], [], ...
    'VariableNames', { ...
        'ContextLabel', 'SourceType', 'Alpha', 'Component', 'NFields', ...
        'Edep_eV', 'dEdep_eV', 'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy' ...
    });
end

function dirs = collect_candidate_child_dirs_r2015(rootDir)
entries = dir(rootDir);
dirs = {};
for i = 1:numel(entries)
    entry = entries(i);
    if ~entry.isdir
        continue;
    end
    name = strtrim(entry.name);
    if strcmp(name, '.') || strcmp(name, '..')
        continue;
    end
    if should_skip_folder_r2015(name)
        continue;
    end
    dirs{end + 1, 1} = fullfile(rootDir, name); %#ok<AGROW>
end
if ~isempty(dirs)
    dirs = sort(dirs);
end
end

function tf = should_skip_folder_r2015(name)
nameKey = lower(strtrim(name));
tf = strcmp(nameKey, 'old') || ...
     strcmp(nameKey, 'old appends') || ...
     strcmp(nameKey, '3d-dose_group') || ...
     strcmp(nameKey, 'dmps') || ...
     strcmp(nameKey, 'previous_runs');
end

function tf = is_batch_folder_name_r2015(name)
nameKey = lower(strtrim(name));
tf = ~isempty(strfind(nameKey, 'batch'));
end

function archive_existing_global_report_outputs_r2015(folderPath)
if nargin < 1 || isempty(folderPath) || ~exist(folderPath, 'dir')
    return;
end
patterns = { ...
    'Global_Report_body_totals.csv', ...
    'Global_Report_key_bodies.csv', ...
    'Global_Report*.png' ...
};
files = [];
for i = 1:numel(patterns)
    matches = dir(fullfile(folderPath, patterns{i}));
    if isempty(matches)
        continue;
    end
    files = [files; matches(:)]; %#ok<AGROW>
end
if isempty(files)
    return;
end
archiveRoot = fullfile(folderPath, 'old');
if ~exist(archiveRoot, 'dir')
    mkdir(archiveRoot);
end
archiveDir = fullfile(archiveRoot, ['Global_Report_' datestr(now, 'yyyymmdd_HHMMSS')]);
if ~exist(archiveDir, 'dir')
    mkdir(archiveDir);
end
seen = {};
for i = 1:numel(files)
    name = files(i).name;
    if any(strcmpi(seen, name))
        continue;
    end
    if strcmpi(name, 'Global_Report_prepared_totals.csv') || strcmpi(name, 'Global_Report_studio_contexts.csv')
        continue;
    end
    seen{end + 1, 1} = name; %#ok<AGROW>
    src = fullfile(folderPath, name);
    if ~exist(src, 'file')
        continue;
    end
    dst = fullfile(archiveDir, name);
    if exist(dst, 'file')
        [~, base, ext] = fileparts(name);
        dst = fullfile(archiveDir, [base '_' datestr(now, 'HHMMSSFFF') ext]);
    end
    movefile(src, dst);
end
end


function names = build_global_preferred_names_r2015(selectedBodyNames, targetBodyName, comparisonBodyNames)
names = normalize_body_name_list_r2015([ ...
    normalize_body_name_list_r2015(selectedBodyNames); ...
    normalize_body_name_list_r2015(targetBodyName); ...
    normalize_body_name_list_r2015(comparisonBodyNames); ...
    {['C' char(233) 'rebro']; 'Olho esquerdo'; 'Olho direito'; 'Tumor'; 'Tumor olho dto'; 'Tumor ouvido esq'} ...
]);
names = repair_mojibake_cellstrs_r2015(names);
end

function names = build_plot_component_names_r2015(preferredNames, currentNames)
preferredNames = normalize_body_name_list_r2015(preferredNames);
currentNames = normalize_body_name_list_r2015(currentNames);
currentKeys = build_body_key_list_r2015(currentNames);
preferredFamilyKeys = cell(numel(preferredNames), 1);
names = {};
for i = 1:numel(preferredNames)
    preferredKey = normalize_body_compare_key_r2015(preferredNames{i});
    preferredFamilyKeys{i} = normalize_body_compare_key_r2015(component_family_label_r2015(preferredNames{i}));
    if any(strcmp(currentKeys, preferredKey))
        names{end + 1, 1} = preferredNames{i}; %#ok<AGROW>
    end
end
names = normalize_body_name_list_r2015(names);
existingKeys = build_body_key_list_r2015(names);
for i = 1:numel(currentNames)
    currentKey = currentKeys{i};
    if isempty(currentKey) || any(strcmp(existingKeys, currentKey))
        continue;
    end
    currentFamilyKey = normalize_body_compare_key_r2015(component_family_label_r2015(currentNames{i}));
    if any(strcmp(preferredFamilyKeys, currentFamilyKey))
        names{end + 1, 1} = currentNames{i}; %#ok<AGROW>
        existingKeys{end + 1, 1} = currentKey; %#ok<AGROW>
    end
end
names = normalize_body_name_list_r2015(names);
end

function label = component_family_label_r2015(label)
label = strtrim(char(label));
family = regexprep(label, '\s+[0-9]+\s*$', '');
family = strtrim(family);
if isempty(family)
    family = label;
end
label = family;
end

function labels = build_context_source_alpha_legend_r2015(seriesInfo, grau)
labels = cell(height(seriesInfo), 1);
for i = 1:height(seriesInfo)
    labels{i} = sprintf('%s | alpha = %.4g%c', seriesInfo.DisplayLabel{i}, seriesInfo.Alpha(i), grau);
end
end

function names = normalize_body_name_list_r2015(rawNames)
names = {};
if nargin < 1 || isempty(rawNames)
    return;
end
if ischar(rawNames)
    rawNames = {rawNames};
elseif ~iscell(rawNames)
    return;
end
for i = 1:numel(rawNames)
    item = rawNames{i};
    label = '';
    if ischar(item)
        label = strtrim(item);
    elseif iscell(item) && ~isempty(item) && ischar(item{1})
        label = strtrim(item{1});
    end
    if isempty(label)
        continue;
    end
    labelKey = normalize_body_compare_key_r2015(label);
    if isempty(labelKey)
        continue;
    end
    duplicate = false;
    for j = 1:numel(names)
        if strcmp(normalize_body_compare_key_r2015(names{j}), labelKey)
            duplicate = true;
            break;
        end
    end
    if ~duplicate
        names{end + 1, 1} = label; %#ok<AGROW>
    end
end
end

function labels = replace_component_labels_r2015(labels, preferredNames)
labels = cell_column_to_strings_r2015(labels);
preferredNames = normalize_body_name_list_r2015(preferredNames);
if isempty(preferredNames)
    return;
end
preferredKeys = build_body_key_list_r2015(preferredNames);
for i = 1:numel(labels)
    currentKey = normalize_body_compare_key_r2015(labels{i});
    for j = 1:numel(preferredKeys)
        if strcmp(currentKey, preferredKeys{j})
            labels{i} = preferredNames{j};
            break;
        end
    end
end
end

function names = ensure_key_components_present_r2015(desiredNames, currentNames, totalNames)
names = normalize_body_name_list_r2015(desiredNames);
desiredKeys = build_body_key_list_r2015(names);
totalNames = normalize_body_name_list_r2015(totalNames);
totalKeys = build_body_key_list_r2015(totalNames);
for i = 1:numel(totalNames)
    totalKey = totalKeys{i};
    if isempty(totalKey)
        continue;
    end
    if ~isempty(strfind(totalKey, 'tumor')) && ~any(strcmp(desiredKeys, totalKey))
        names = normalize_body_name_list_r2015([names; totalNames(i)]);
        desiredKeys{end + 1, 1} = totalKey; %#ok<AGROW>
    end
end
end

function label = preferred_body_display_label_r2015(rawLabel, preferredNames)
label = strtrim(rawLabel);
preferredNames = normalize_body_name_list_r2015(preferredNames);
if isempty(preferredNames)
    return;
end
rawKey = normalize_body_compare_key_r2015(label);
preferredKeys = build_body_key_list_r2015(preferredNames);
for i = 1:numel(preferredKeys)
    if strcmp(rawKey, preferredKeys{i})
        label = preferredNames{i};
        return;
    end
end
end

function idx = find_component_row_r2015(componentNames, desiredName)
idx = [];
desiredKey = normalize_body_compare_key_r2015(desiredName);
for i = 1:numel(componentNames)
    current = '';
    if ischar(componentNames{i})
        current = strtrim(componentNames{i});
    end
    if strcmp(normalize_body_compare_key_r2015(current), desiredKey)
        idx = i;
        return;
    end
end
end

function keys = build_body_key_list_r2015(names)
names = cell_column_to_strings_r2015(names);
keys = cell(size(names));
for i = 1:numel(names)
    keys{i} = normalize_body_compare_key_r2015(names{i});
end
keys = keys(:);
end

function key = normalize_body_compare_key_r2015(value)
if nargin < 1 || isempty(value)
    key = '';
    return;
end
if isnumeric(value)
    value = num2str(value);
elseif ~ischar(value)
    try
        value = char(value);
    catch
        value = '';
    end
end
value = strip_portuguese_diacritics_r2015(strtrim(value));
key = regexprep(lower(value), '[^a-z0-9]+', '');
switch key
    case 'crebro'
        key = 'cerebro';
    case 'olhodto'
        key = 'olhodireito';
    case 'olhoesq'
        key = 'olhoesquerdo';
end
end

function out = strip_portuguese_diacritics_r2015(value)
out = char(value);
replacements = {
    char(193), 'A'; char(192), 'A'; char(195), 'A'; char(194), 'A'; char(196), 'A';
    char(225), 'a'; char(224), 'a'; char(227), 'a'; char(226), 'a'; char(228), 'a';
    char(201), 'E'; char(200), 'E'; char(202), 'E'; char(203), 'E';
    char(233), 'e'; char(232), 'e'; char(234), 'e'; char(235), 'e';
    char(205), 'I'; char(204), 'I'; char(206), 'I'; char(207), 'I';
    char(237), 'i'; char(236), 'i'; char(238), 'i'; char(239), 'i';
    char(211), 'O'; char(210), 'O'; char(213), 'O'; char(212), 'O'; char(214), 'O';
    char(243), 'o'; char(242), 'o'; char(245), 'o'; char(244), 'o'; char(246), 'o';
    char(218), 'U'; char(217), 'U'; char(219), 'U'; char(220), 'U';
    char(250), 'u'; char(249), 'u'; char(251), 'u'; char(252), 'u';
    char(199), 'C'; char(231), 'c'
};
for i = 1:size(replacements, 1)
    out = strrep(out, replacements{i, 1}, replacements{i, 2});
end
end

function out = normalize_source_type_label_r2015(label)
if nargin < 1 || isempty(label)
    out = '';
    return;
end
if isnumeric(label)
    label = num2str(label);
elseif ~ischar(label)
    try
        label = char(label);
    catch
        label = '';
    end
end
text = strtrim(label);
text = strip_portuguese_diacritics_r2015(text);
text = regexprep(text, '[_]+', ' ');
text = regexprep(text, '\s+', ' ');
key = regexprep(lower(text), '[^a-z0-9]+', '');
switch key
    case 'linac6mev'
        out = 'LINAC 6MeV';
    case {'cobalt60source', 'cobalt60', 'co60', 'co60source'}
        out = 'Cobalt-60 source';
    otherwise
        out = text;
end
end

function out = display_source_type_r2015(label)
out = normalize_source_type_label_r2015(label);
if isempty(out)
    out = 'Unknown source';
end
end

function token = safe_label_file_token_r2015(label)
if nargin < 1 || isempty(label)
    token = 'label';
    return;
end
if isnumeric(label)
    label = num2str(label);
elseif ~ischar(label)
    try
        label = char(label);
    catch
        label = '';
    end
end
key = normalize_body_compare_key_r2015(label);
switch key
    case 'olhodireito'
        token = 'olho_direito';
    case 'olhoesquerdo'
        token = 'olho_esquerdo';
    case 'tumorolhodto'
        token = 'tumor_olho_dto';
    case 'tumorouvidoesq'
        token = 'tumor_ouvido_esq';
    case 'cerebro'
        token = 'cerebro';
    otherwise
        text = strip_portuguese_diacritics_r2015(strtrim(label));
        token = regexprep(lower(text), '[^a-z0-9]+', '_');
        token = regexprep(token, '_+', '_');
        token = regexprep(token, '^_|_$', '');
        if isempty(token)
            token = 'label';
        end
end
end
