function penelope_report_dose_analysis
% PENELOPE report dose analysis helper (MATLAB R2015 compatible)
% 1) Reads body-dose tables exported from penmain-res.dat / Excel body energy deposition.
% 2) Computes total dose per body and per ALPHA using quadrature errors.
% 3) Ranks angles by selected comparison-body / target-body ratios.
% 4) Reads 3d-dose.dat data and exports profiles, dose planes, and uncertainty maps.
%
% selectedLabelSpecs stores SURFACE labels and centers for spatial plots.
% targetBodyName/selectedBodyNames/comparisonBodyNames store BODY labels for workbook analysis.
% The MATLAB script is self-contained and does not parse the .geo file at runtime.

close all;
clc;
disp(['Running penelope_report_dose_analysis from: ' mfilename('fullpath')]);

%% ---------------- USER PARAMETERS ----------------
% selectedLabelSpecs was generated by PENELOPE Studio from user-selected SURFACE labels
%__STUDIO_SELECTED_LABELS_BEGIN__
xTumorOlhoDto = 4.0;  yTumorOlhoDto = 3.0;  zTumorOlhoDto = -2.2;
xOlhoDireito = 4.0;  yOlhoDireito = 6.5;  zOlhoDireito = -2.0;
xOlhoEsquerdo = -4.0;  yOlhoEsquerdo = 6.5;  zOlhoEsquerdo = -2.0;
selectedLabelSpecs = {
    'Tumor olho dto', 'target', xTumorOlhoDto, yTumorOlhoDto, zTumorOlhoDto;
    'Olho direito', 'body', xOlhoDireito, yOlhoDireito, zOlhoDireito;
    'Olho esquerdo', 'body', xOlhoEsquerdo, yOlhoEsquerdo, zOlhoEsquerdo
};
targetSurfaceLabel = 'Tumor olho dto';
targetBodyName = 'Tumor olho dto';
selectedBodyNames = {
    'Tumor olho dto';
    'Olho direito';
    'Olho esquerdo'
};
comparisonBodyNames = {
    'Olho direito';
    'Olho esquerdo'
};
targetIdx = find(strcmpi(selectedLabelSpecs(:,1), targetSurfaceLabel), 1);
if isempty(targetIdx)
    error('No target coordinates were provided by PENELOPE Studio.');
end
xT = selectedLabelSpecs{targetIdx,3};  yT = selectedLabelSpecs{targetIdx,4};  zT = selectedLabelSpecs{targetIdx,5};
%__STUDIO_SELECTED_LABELS_END__

% geometrySlicePoints was generated by PENELOPE Studio from the selected .geo file
% and encodes occupied XY/XZ/YZ slice points for the selected target center.
%__STUDIO_GEOMETRY_SLICES_BEGIN__
geometrySlicePoints = struct();
geometrySlicePoints.xy = zeros(0,2);
geometrySlicePoints.xz = zeros(0,2);
geometrySlicePoints.yz = zeros(0,2);
%__STUDIO_GEOMETRY_SLICES_END__

% Files. Leave empty to choose interactively.
excelPath = '';
excelRoot = '';
dose3dPath = '';
dose3dRoot = '';

% Output folder. Leave empty to use the file folder.
outDir = '';

ced = [char(231) char(227)];
grau = char(176);
scriptRoot = fileparts(mfilename('fullpath'));

batchRootsAuto = collect_batch_analysis_roots_r2015(scriptRoot);
if isempty(excelPath) && isempty(excelRoot) && isempty(dose3dPath) && isempty(dose3dRoot) && ~isempty(batchRootsAuto)
    rootWorkbooks = collect_dose_workbooks_here_r2015(scriptRoot);
    useRootWorkbooks = false;
    if ~isempty(rootWorkbooks)
        rootChoice = menu('Use root xlsx?', 'Yes', 'No');
        useRootWorkbooks = (rootChoice == 1);
    end
    batchWorkbookChoice = menu('Process batch xlsx?', 'Yes', 'No');
    batchCaseDoseChoice = menu('Process batch individual 3d dose?', 'Yes', 'No');
    batchGroupDoseChoice = menu('Process 3d dose group?', 'Yes', 'No');
    doBatchWorkbooks = (batchWorkbookChoice == 1);
    doBatchCaseDoses = (batchCaseDoseChoice == 1);
    doBatchGroupDoses = (batchGroupDoseChoice == 1);
    if ~useRootWorkbooks && ~doBatchWorkbooks && ~doBatchCaseDoses && ~doBatchGroupDoses
        disp('No root or batch analysis steps selected. Exiting.');
        return;
    end
    if useRootWorkbooks
        for i = 1:numel(rootWorkbooks)
            try
                process_excel_dose_workbook_r2015(rootWorkbooks{i}, fileparts(rootWorkbooks{i}), ced, grau, targetBodyName, comparisonBodyNames, selectedBodyNames);
                disp(['Processed root dose workbook: ' rootWorkbooks{i}]);
            catch ME
                disp(['Failed to process root dose workbook ', rootWorkbooks{i}, ': ' ME.message]);
            end
        end
    end
    processedBatches = 0;
    for i = 1:numel(batchRootsAuto)
        try
            process_batch_analysis_root_r2015(batchRootsAuto{i}, xT, yT, zT, selectedLabelSpecs, targetBodyName, comparisonBodyNames, selectedBodyNames, geometrySlicePoints, ced, grau, doBatchWorkbooks, doBatchCaseDoses, doBatchGroupDoses);
            processedBatches = processedBatches + 1;
        catch ME
            disp(['Failed to process batch root ', batchRootsAuto{i}, ': ' ME.message]);
        end
    end
    disp(['Processed batch folders: ' num2str(processedBatches)]);
    return;
end

%% ---------------- PART A: BODY DOSE TOTALS FROM EXCEL ----------------
if isempty(excelPath) && isempty(excelRoot)
    excelMode = menu('Excel dose mode', 'One dose workbook', 'Scan root folder recursively', 'Skip');
    if excelMode == 1
        [f, p] = uigetfile({'*.xlsx;*.xls', 'Excel files'}, 'Select dose Excel file');
        if isequal(f, 0)
            disp('No Excel file selected; skipping body dose analysis.');
        else
            excelPath = fullfile(p, f);
        end
    elseif excelMode == 2
        rootChosen = uigetdir(pwd, 'Select root folder to scan recursively for dose workbooks');
        if isequal(rootChosen, 0)
            disp('No root folder selected; skipping recursive body dose analysis.');
        else
            excelRoot = rootChosen;
        end
    else
        disp('Skipping body dose analysis.');
    end
end

if ~isempty(excelRoot)
    excelFiles = collect_dose_workbooks_r2015(excelRoot);
    if isempty(excelFiles)
        disp(['No valid dose workbooks found under: ' excelRoot]);
    else
        processedExcel = 0;
        for i = 1:numel(excelFiles)
            currentExcel = excelFiles{i};
            try
                process_excel_dose_workbook_r2015(currentExcel, fileparts(currentExcel), ced, grau, targetBodyName, comparisonBodyNames, selectedBodyNames);
                processedExcel = processedExcel + 1;
                disp(['Processed dose workbook: ' currentExcel]);
            catch ME
                disp(['Failed to process dose workbook ', currentExcel, ': ' ME.message]);
            end
        end
        disp(['Processed dose workbooks: ' num2str(processedExcel)]);
    end
elseif ~isempty(excelPath)
    if isempty(outDir)
        outDir = fileparts(excelPath);
    end
    process_excel_dose_workbook_r2015(excelPath, outDir, ced, grau, targetBodyName, comparisonBodyNames, selectedBodyNames);
end

%% ---------------- PART B: 3D DOSE PROFILES AND PLANES ----------------
if isempty(dose3dPath) && isempty(dose3dRoot)
    modeChoice = menu('3D dose mode', 'One 3d-dose.dat file', 'Scan root folder recursively', 'Skip');
    if modeChoice == 1
        [f, p] = uigetfile({'3d-dose*.dat;*.dat', 'PENELOPE 3D dose files'}, 'Select 3d-dose.dat file');
        if isequal(f, 0)
            disp('No 3D dose file selected; skipping 3D dose plots.');
        else
            dose3dPath = fullfile(p, f);
        end
    elseif modeChoice == 2
        rootChosen = uigetdir(pwd, 'Select root folder to scan recursively for 3d-dose files');
        if isequal(rootChosen, 0)
            disp('No root folder selected; skipping recursive 3D dose plots.');
        else
            dose3dRoot = rootChosen;
        end
    else
        disp('Skipping 3D dose plots.');
    end
end

if ~isempty(dose3dRoot)
    doseFiles = collect_3d_dose_files_r2015(dose3dRoot);
    if isempty(doseFiles)
        disp(['No 3d-dose files found under: ' dose3dRoot]);
    else
        doseFiles = choose_path_subset_r2015(doseFiles, '3D-dose files found under root', dose3dRoot);
        if isempty(doseFiles)
            disp('No 3D-dose files selected; skipping recursive 3D dose plots.');
            return;
        end
        processed = 0;
        for i = 1:numel(doseFiles)
            try
                process_single_3d_dose_r2015(doseFiles{i}, fileparts(doseFiles{i}), xT, yT, zT, selectedLabelSpecs, geometrySlicePoints, '');
                processed = processed + 1;
                disp(['Processed 3d-dose file: ' doseFiles{i}]);
            catch ME
                disp(['Failed to process ' doseFiles{i} ': ' ME.message]);
            end
        end
        disp(['Processed 3d-dose files: ' num2str(processed)]);
    end
elseif ~isempty(dose3dPath)
    if isempty(outDir)
        outDir = fileparts(dose3dPath);
    end
    process_single_3d_dose_r2015(dose3dPath, outDir, xT, yT, zT, selectedLabelSpecs, geometrySlicePoints, '');
end

end

function process_excel_dose_workbook_r2015(excelPath, outDir, ced, grau, targetBodyName, comparisonBodyNames, selectedBodyNames)
archive_existing_workbook_outputs_r2015(outDir);
doseData = load_dose_sheet_r2015(excelPath);
n = numel(doseData.case_names);
THETA = nan(n, 1);
PHI = nan(n, 1);
ALPHA = nan(n, 1);
CASEID = nan(n, 1);

for i = 1:n
    c = doseData.case_names{i};
    tok = regexp(c, 'SCONE-([\-0-9\.]+)_([\-0-9\.]+)_([\-0-9\.]+)', 'tokens', 'once');
    if ~isempty(tok)
        THETA(i) = str2double(tok{1});
        PHI(i) = str2double(tok{2});
        ALPHA(i) = str2double(tok{3});
    end
    tok2 = regexp(c, 'case(\d+)', 'tokens', 'once');
    if ~isempty(tok2)
        CASEID(i) = str2double(tok2{1});
    end
end

validMask = ~isnan(ALPHA);
caseNames = doseData.case_names(validMask);
sourceTypes = doseData.source_types(validMask);
componentNames = doseData.component_names(validMask);
componentKeys = build_body_key_list_r2015(componentNames);
edepEv = doseData.edep_ev(validMask);
dEdepEv = doseData.dedep_ev(validMask);
doseEvg = doseData.dose_evg(validMask);
dDoseEvg = doseData.ddose_evg(validMask);
doseGy = doseData.dose_gy(validMask);
dDoseGy = doseData.ddose_gy(validMask);
THETA = THETA(validMask);
PHI = PHI(validMask);
ALPHA = ALPHA(validMask);
CASEID = CASEID(validMask);
sourceTypes = fill_empty_labels_r2015(sourceTypes, 'Unknown source');

alphas = unique(ALPHA);

totalSourceType = {};
totalAlpha = [];
totalComponent = {};
totalNFields = [];
totalEdepEv = [];
totaldEdepEv = [];
totalDoseEvg = [];
totaldDoseEvg = [];
totalErrPct = [];
totalDoseGy = [];
totaldDoseGy = [];

row = 0;
for a = 1:numel(alphas)
    alphaMask = (ALPHA == alphas(a));
    sourceList = unique(sourceTypes(alphaMask));
    for s = 1:numel(sourceList)
        sourceMask = alphaMask & strcmp(sourceTypes, sourceList{s});
        compKeys = unique(componentKeys(sourceMask));
        for c = 1:numel(compKeys)
            compMask = sourceMask & strcmp(componentKeys, compKeys{c});
            firstCompIdx = find(compMask, 1, 'first');
            row = row + 1;
            totalSourceType{row, 1} = sourceList{s}; %#ok<AGROW>
            totalAlpha(row, 1) = alphas(a); %#ok<AGROW>
            totalComponent{row, 1} = preferred_body_display_label_r2015(componentNames{firstCompIdx}, selectedBodyNames); %#ok<AGROW>
            totalNFields(row, 1) = sum(compMask); %#ok<AGROW>
            totalEdepEv(row, 1) = sum(edepEv(compMask)); %#ok<AGROW>
            totaldEdepEv(row, 1) = sqrt(sum(dEdepEv(compMask).^2)); %#ok<AGROW>
            totalDoseEvg(row, 1) = sum(doseEvg(compMask)); %#ok<AGROW>
            totaldDoseEvg(row, 1) = sqrt(sum(dDoseEvg(compMask).^2)); %#ok<AGROW>
            if totalDoseEvg(row, 1) ~= 0
                totalErrPct(row, 1) = 100 * totaldDoseEvg(row, 1) / totalDoseEvg(row, 1); %#ok<AGROW>
            else
                totalErrPct(row, 1) = NaN; %#ok<AGROW>
            end
            totalDoseGy(row, 1) = sum(doseGy(compMask)); %#ok<AGROW>
            totaldDoseGy(row, 1) = sqrt(sum(dDoseGy(compMask).^2)); %#ok<AGROW>
        end
    end
end

Totals = table( ...
    totalSourceType, totalAlpha, totalComponent, totalNFields, totalEdepEv, totaldEdepEv, ...
    totalDoseEvg, totaldDoseEvg, totalErrPct, totalDoseGy, totaldDoseGy, ...
    'VariableNames', { ...
        'SourceType', 'Alpha', 'Component', 'NFields', 'Edep_eV', 'dEdep_eV', ...
        'Dose_eVg', 'dDose_eVg', 'Error_pct', 'Dose_Gy', 'dDose_Gy' ...
    });
writetable(Totals, fullfile(outDir, 'body_totals_by_alpha.csv'));

keyNames = normalize_body_name_list_r2015(selectedBodyNames);
keyNames = normalize_body_name_list_r2015([ ...
    keyNames; ...
    normalize_body_name_list_r2015(targetBodyName); ...
    normalize_body_name_list_r2015(comparisonBodyNames) ...
]);
if isempty(keyNames)
    keyNames = {'tumor olho dto'; 'Olho direito'; 'Olho esquerdo'};
end
keyKeys = build_body_key_list_r2015(keyNames);
totalComponentKeys = build_body_key_list_r2015(Totals.Component);
keepMask = false(height(Totals), 1);
for j = 1:numel(keyKeys)
    keepMask = keepMask | strcmp(totalComponentKeys, keyKeys{j});
end
K = Totals(keepMask, :);
if ~isempty(K)
    K.Component = replace_component_labels_r2015(K.Component, keyNames);
end
keyNames = ensure_key_components_present_r2015(keyNames, K.Component, Totals.Component);
keyKeys = build_body_key_list_r2015(keyNames);
keepMask = false(height(Totals), 1);
for j = 1:numel(keyKeys)
    keepMask = keepMask | strcmp(totalComponentKeys, keyKeys{j});
end
K = Totals(keepMask, :);
if ~isempty(K)
    K.Component = replace_component_labels_r2015(K.Component, keyNames);
end
writetable(K, fullfile(outDir, 'key_bodies_by_alpha.csv'));

plotSources = unique(K.SourceType);
multiSourceBodies = numel(plotSources) > 1;
for s = 1:numel(plotSources)
    Ks = K(strcmp(K.SourceType, plotSources{s}), :);
    if isempty(Ks)
        continue;
    end
    figWidth = max(880, 140 * numel(keyNames));
    fig = figure('Color', 'w', 'Position', [100, 100, figWidth, 560]);
    hold on;
    legendLabels = {};
    alphaList = unique(Ks.Alpha);
    for a = 1:numel(alphaList)
        Ka = Ks(Ks.Alpha == alphaList(a), :);
        orderedIdx = zeros(numel(keyNames), 1);
        for j = 1:numel(keyNames)
            matchIdx = find_component_row_r2015(Ka.Component, keyNames{j});
            if ~isempty(matchIdx)
                orderedIdx(j) = matchIdx;
            end
        end
        xVals = find(orderedIdx > 0);
        if isempty(xVals)
            continue;
        end
        Ka = Ka(orderedIdx(xVals), :);
        errorbar(xVals, Ka.Dose_eVg, Ka.dDose_eVg, 'o-');
        legendLabels{end + 1} = sprintf('alpha = %.4g%c', alphaList(a), grau); %#ok<AGROW>
    end
    set(gca, 'YScale', 'log', 'XTick', 1:numel(keyNames), 'XTickLabel', keyNames);
    try
        set(gca, 'XTickLabelRotation', 25);
    catch
    end
    xlim([0.5, numel(keyNames) + 0.5]);
    ylabel('Dose total somada (eV/g)');
    title(sprintf('Dose total somada por corpo selecionado: %s', display_source_type_r2015(plotSources{s})), 'Interpreter', 'none');
    grid on;
    if ~isempty(legendLabels)
        legend(legendLabels, 'Location', 'best');
    end
    if multiSourceBodies
        outName = ['bar_key_bodies_by_alpha_', safe_file_token_r2015(plotSources{s}), '.png'];
    else
        outName = 'bar_key_bodies_by_alpha.png';
    end
    saveas(fig, fullfile(outDir, outName));
    close(fig);
end

cases = unique(caseNames);
targetNames = normalize_body_name_list_r2015(targetBodyName);
if isempty(targetNames)
    targetNames = {'tumor olho dto'};
end
targetName = targetNames{1};
targetKey = normalize_body_compare_key_r2015(targetName);

compareNames = normalize_body_name_list_r2015(comparisonBodyNames);
if isempty(compareNames)
    compareNames = resolve_default_comparison_body_names_r2015(selectedBodyNames, targetName);
end

for cmpIdx = 1:numel(compareNames)
    compareName = compareNames{cmpIdx};
    compareKey = normalize_body_compare_key_r2015(compareName);
    rankCase = {};
    rankSourceType = {};
    rankCaseID = [];
    rankAlpha = [];
    rankTheta = [];
    rankPhi = [];
    rankTargetDose = [];
    rankCompareDose = [];
    rankComparePct = [];
    r = 0;

    for i = 1:numel(cases)
        caseMask = strcmp(caseNames, cases{i});
        caseRows = find(caseMask);
        if isempty(caseRows)
            continue;
        end
        localComponents = componentNames(caseRows);
        targetLocalMask = build_component_match_mask_r2015(localComponents, {targetName});
        compareLocalMask = build_component_match_mask_r2015(localComponents, {compareName});
        targetLocalIdx = find(targetLocalMask, 1, 'first');
        compareLocalIdx = find(compareLocalMask, 1, 'first');
        if isempty(targetLocalIdx) || isempty(compareLocalIdx)
            continue;
        end
        targetIdx = caseRows(targetLocalIdx);
        compareIdx = caseRows(compareLocalIdx);
        if ~isempty(targetIdx) && ~isempty(compareIdx)
            targetDose = doseEvg(targetIdx);
            compareDose = doseEvg(compareIdx);
            if isnan(targetDose) || targetDose == 0 || isnan(compareDose)
                continue;
            end
            r = r + 1;
            rankCase{r, 1} = cases{i}; %#ok<AGROW>
            rankSourceType{r, 1} = sourceTypes{targetIdx}; %#ok<AGROW>
            rankCaseID(r, 1) = CASEID(targetIdx); %#ok<AGROW>
            rankAlpha(r, 1) = ALPHA(targetIdx); %#ok<AGROW>
            rankTheta(r, 1) = THETA(targetIdx); %#ok<AGROW>
            rankPhi(r, 1) = PHI(targetIdx); %#ok<AGROW>
            rankTargetDose(r, 1) = targetDose; %#ok<AGROW>
            rankCompareDose(r, 1) = compareDose; %#ok<AGROW>
            rankComparePct(r, 1) = 100 * compareDose / targetDose; %#ok<AGROW>
        end
    end

    R = table( ...
        rankCase, rankSourceType, rankCaseID, rankAlpha, rankTheta, rankPhi, ...
        rankTargetDose, rankCompareDose, rankComparePct, ...
        'VariableNames', { ...
            'Case', 'SourceType', 'CaseID', 'Alpha', 'THETA', 'PHI', ...
            'TargetDose_eVg', 'CompareDose_eVg', 'CompareTarget_pct' ...
        });
    if ~isempty(R)
        R = sortrows(R, {'Alpha', 'SourceType', 'CompareTarget_pct'});
    end
    compareToken = safe_label_file_token_r2015(compareName);
    targetToken = safe_label_file_token_r2015(targetName);
    writetable(R, fullfile(outDir, ['angle_ranking_' compareToken '_vs_' targetToken '.csv']));
    if isempty(R)
        disp(['No ranking rows matched for ' compareName ' vs ' targetName ' in ' excelPath]);
    end

    alphaRankList = unique(R.Alpha);
    for a = 1:numel(alphaRankList)
        sourceList = unique(R.SourceType(R.Alpha == alphaRankList(a)));
        for s = 1:numel(sourceList)
            Ra = R(R.Alpha == alphaRankList(a) & strcmp(R.SourceType, sourceList{s}), :);
            if isempty(Ra)
                continue;
            end
            labels = cell(height(Ra), 1);
            for j = 1:height(Ra)
                labels{j} = sprintf('T%.0f P%.0f', Ra.THETA(j), Ra.PHI(j));
            end
            figHeight = max(560, 24 * height(Ra));
            fig = figure('Color', 'w', 'Position', [100, 100, 860, figHeight]);
            barh(Ra.CompareTarget_pct);
            set(gca, 'YTick', 1:height(Ra), 'YTickLabel', labels);
            xlabel(sprintf('%s / %s (%%)', compareName, targetName));
            title(sprintf(['Ordena' ced 'o angular, alfa = %.4g%c, fonte = %s, compara' ced 'o = %s / %s'], alphaRankList(a), grau, display_source_type_r2015(sourceList{s}), compareName, targetName), 'Interpreter', 'none');
            grid on;
            outName = ['angle_ranking_' compareToken '_vs_' targetToken '_alpha_' strrep(num2str(alphaRankList(a)), '.', 'p') '_' safe_file_token_r2015(sourceList{s}) '.png'];
            saveas(fig, fullfile(outDir, outName));
            close(fig);
        end
    end
end
end

function files = collect_dose_workbooks_r2015(rootDir)
paths = regexp(genpath(rootDir), pathsep, 'split');
files = {};
for i = 1:numel(paths)
    currentDir = paths{i};
    if isempty(currentDir)
        continue;
    end
    lowerDir = lower(currentDir);
    if ~isempty(strfind(lowerDir, [filesep 'previous_runs'])) || ...
       ~isempty(strfind(lowerDir, [filesep 'dmps'])) || ...
       ~isempty(strfind(lowerDir, [filesep '3d-dose_group'])) || ...
       ~isempty(strfind(lowerDir, [filesep 'old appends']))
        continue;
    end
    matches = [dir(fullfile(currentDir, '*.xlsx')); dir(fullfile(currentDir, '*.xls'))];
    for j = 1:numel(matches)
        if matches(j).isdir
            continue;
        end
        candidate = fullfile(currentDir, matches(j).name);
        try
            if is_penelope_dose_workbook_r2015(candidate)
                files{end + 1, 1} = candidate; %#ok<AGROW>
            end
        catch
        end
    end
end
if ~isempty(files)
    files = sort(files);
end
end

function files = collect_dose_workbooks_here_r2015(rootDir)
matches = [dir(fullfile(rootDir, '*.xlsx')); dir(fullfile(rootDir, '*.xls'))];
files = {};
for i = 1:numel(matches)
    if matches(i).isdir
        continue;
    end
    candidate = fullfile(rootDir, matches(i).name);
    try
        if is_penelope_dose_workbook_r2015(candidate)
            files{end + 1, 1} = candidate; %#ok<AGROW>
        end
    catch
    end
end
if ~isempty(files)
    files = sort(files);
end
end

function roots = collect_batch_analysis_roots_r2015(rootDir)
entries = dir(rootDir);
roots = {};
for i = 1:numel(entries)
    entry = entries(i);
    if ~entry.isdir
        continue;
    end
    name = strtrim(entry.name);
    if strcmp(name, '.') || strcmp(name, '..')
        continue;
    end
    lowerName = lower(name);
    if strcmp(lowerName, 'previous_runs') || strcmp(lowerName, 'dmps') || strcmp(lowerName, '3d-dose_group') || strcmp(lowerName, 'old appends')
        continue;
    end
    if isempty(strfind(lowerName, 'batch'))
        continue;
    end
    child = fullfile(rootDir, name);
    if ~isempty(collect_dose_workbooks_r2015(child)) || ...
       ~isempty(collect_3d_dose_files_r2015(child)) || ...
       ~isempty(collect_group_3d_dose_folders_r2015(child))
        roots{end + 1, 1} = child; %#ok<AGROW>
    end
end
if ~isempty(roots)
    roots = sort(roots);
end
end

function folders = collect_group_3d_dose_folders_r2015(rootDir)
paths = regexp(genpath(rootDir), pathsep, 'split');
folders = {};
for i = 1:numel(paths)
    currentDir = paths{i};
    if isempty(currentDir)
        continue;
    end
    lowerDir = lower(currentDir);
    [~, baseName] = fileparts(currentDir);
    if ~strcmpi(baseName, '3d-dose_group')
        continue;
    end
    if isempty(dir(fullfile(currentDir, '3d-dose*.dat')))
        continue;
    end
    if ~isempty(strfind(lowerDir, [filesep 'previous_runs'])) || ...
       ~isempty(strfind(lowerDir, [filesep 'dmps']))
        continue;
    end
    folders{end + 1, 1} = currentDir; %#ok<AGROW>
end
if ~isempty(folders)
    folders = sort(folders);
end
end

function process_batch_analysis_root_r2015(batchRoot, xT, yT, zT, labelSpecs, targetBodyName, comparisonBodyNames, selectedBodyNames, geometrySlicePoints, ced, grau, doExcel, doSingle3d, doGroup3d)
disp(['Processing batch root: ' batchRoot]);
if nargin < 12 || isempty(doExcel)
    doExcel = true;
end
if nargin < 13 || isempty(doSingle3d)
    doSingle3d = true;
end
if nargin < 14 || isempty(doGroup3d)
    doGroup3d = true;
end

if doExcel
    excelFiles = collect_dose_workbooks_here_r2015(batchRoot);
    for i = 1:numel(excelFiles)
        try
            process_excel_dose_workbook_r2015(excelFiles{i}, fileparts(excelFiles{i}), ced, grau, targetBodyName, comparisonBodyNames, selectedBodyNames);
            disp(['Processed batch workbook: ' excelFiles{i}]);
        catch ME
            disp(['Failed batch workbook ', excelFiles{i}, ': ' ME.message]);
        end
    end
end

if doSingle3d
    doseFiles = collect_3d_dose_files_r2015(batchRoot);
    for i = 1:numel(doseFiles)
        try
            process_single_3d_dose_r2015(doseFiles{i}, fileparts(doseFiles{i}), xT, yT, zT, labelSpecs, geometrySlicePoints, '');
            disp(['Processed batch 3d-dose: ' doseFiles{i}]);
        catch ME
            disp(['Failed batch 3d-dose ', doseFiles{i}, ': ' ME.message]);
        end
    end
end

if doGroup3d
    groupFolders = collect_group_3d_dose_folders_r2015(batchRoot);
    for i = 1:numel(groupFolders)
        try
            process_grouped_3d_dose_folder_r2015(groupFolders{i}, xT, yT, zT, labelSpecs, geometrySlicePoints, ced);
            disp(['Processed grouped 3d-dose folder: ' groupFolders{i}]);
        catch ME
            disp(['Failed grouped 3d-dose folder ', groupFolders{i}, ': ' ME.message]);
        end
    end
end
end

function ok = is_penelope_dose_workbook_r2015(path)
ok = false;
try
    [~, ~, raw] = xlsread(path, 'Dose');
catch
    return;
end
if isempty(raw) || size(raw, 1) < 1
    return;
end
headers = raw(1, :);
required = { ...
    {'Case'}, ...
    {'Component'}, ...
    {'Edep (eV)', 'Edep_eV'}, ...
    {'dE (eV)', 'dE_eV'}, ...
    {'Dose (eV/g)', 'Dose_eV_g'}, ...
    {'dDose (eV/g)', 'dDose_eV_g'}, ...
    {'Dose (Gy)', 'Dose_Gy'}, ...
    {'dDose (Gy)', 'dDose_Gy'} ...
};
for i = 1:numel(required)
    if isnan(find_header_index(headers, required{i}))
        return;
    end
end
ok = true;
end

function data = load_dose_sheet_r2015(excelPath)
[~, ~, raw] = xlsread(excelPath, 'Dose');
if isempty(raw) || size(raw, 1) < 2
    error('Dose sheet is empty or missing usable rows.');
end

headers = raw(1, :);
rows = raw(2:end, :);

caseIdx = find_header_index(headers, {'Case'});
sourceTypeIdx = find_optional_header_index(headers, {'Spectrum Type', 'Source Type', 'SourceType'});
componentIdx = find_header_index(headers, {'Component'});
edepIdx = find_header_index(headers, {'Edep (eV)', 'Edep_eV'});
dedepIdx = find_header_index(headers, {'dE (eV)', 'dE_eV'});
doseEvgIdx = find_header_index(headers, {'Dose (eV/g)', 'Dose_eV_g'});
ddoseEvgIdx = find_header_index(headers, {'dDose (eV/g)', 'dDose_eV_g'});
doseGyIdx = find_header_index(headers, {'Dose (Gy)', 'Dose_Gy'});
ddoseGyIdx = find_header_index(headers, {'dDose (Gy)', 'dDose_Gy'});

data.case_names = cell_column_to_strings(rows(:, caseIdx));
if ~isnan(sourceTypeIdx)
    data.source_types = cell_column_to_strings(rows(:, sourceTypeIdx));
else
    data.source_types = repmat({''}, size(rows, 1), 1);
end
for i = 1:numel(data.source_types)
    data.source_types{i} = normalize_source_type_label_r2015(data.source_types{i});
end
data.component_names = cell_column_to_strings(rows(:, componentIdx));
data.edep_ev = cell_column_to_numeric(rows(:, edepIdx));
data.dedep_ev = cell_column_to_numeric(rows(:, dedepIdx));
data.dose_evg = cell_column_to_numeric(rows(:, doseEvgIdx));
data.ddose_evg = cell_column_to_numeric(rows(:, ddoseEvgIdx));
data.dose_gy = cell_column_to_numeric(rows(:, doseGyIdx));
data.ddose_gy = cell_column_to_numeric(rows(:, ddoseGyIdx));

keep = ~cellfun(@isempty, data.case_names) & ~cellfun(@isempty, data.component_names);
data.case_names = data.case_names(keep);
data.source_types = data.source_types(keep);
data.component_names = data.component_names(keep);
data.edep_ev = data.edep_ev(keep);
data.dedep_ev = data.dedep_ev(keep);
data.dose_evg = data.dose_evg(keep);
data.ddose_evg = data.ddose_evg(keep);
data.dose_gy = data.dose_gy(keep);
data.ddose_gy = data.ddose_gy(keep);
end

function idx = find_header_index(headers, candidates)
idx = [];
for i = 1:numel(headers)
    current = normalize_header_name(headers{i});
    for j = 1:numel(candidates)
        if strcmp(current, normalize_header_name(candidates{j}))
            idx = i;
            return;
        end
    end
end
error('Could not find expected Excel column header: ''%s''.', candidates{1});
end

function idx = find_optional_header_index(headers, candidates)
idx = NaN;
for i = 1:numel(headers)
    current = normalize_header_name(headers{i});
    for j = 1:numel(candidates)
        if strcmp(current, normalize_header_name(candidates{j}))
            idx = i;
            return;
        end
    end
end
end

function out = normalize_header_name(value)
if isnumeric(value)
    value = num2str(value);
elseif ~ischar(value)
    value = '';
end
out = regexprep(lower(strtrim(value)), '[^a-z0-9]+', '');
end

function values = cell_column_to_strings(col)
values = cell(size(col));
for i = 1:numel(col)
    item = col{i};
    if ischar(item)
        values{i} = strtrim(item);
    elseif isnumeric(item)
        if isempty(item) || isnan(item)
            values{i} = '';
        else
            values{i} = strtrim(num2str(item));
        end
    else
        values{i} = '';
    end
end
values = values(:);
end

function values = cell_column_to_numeric(col)
values = nan(numel(col), 1);
for i = 1:numel(col)
    item = col{i};
    if isnumeric(item)
        if ~isempty(item)
            values(i) = item(1);
        end
    elseif ischar(item)
        temp = str2double(strrep(strrep(strtrim(item), 'D', 'E'), 'd', 'e'));
        if ~isnan(temp)
            values(i) = temp;
        end
    end
end
end

function labels = fill_empty_labels_r2015(labels, fallbackLabel)
labels = labels(:);
for i = 1:numel(labels)
    current = '';
    if ischar(labels{i})
        current = strtrim(labels{i});
    end
    if isempty(current)
        labels{i} = fallbackLabel;
    end
end
end

function names = normalize_body_name_list_r2015(rawNames)
names = {};
if nargin < 1 || isempty(rawNames)
    return;
end
if ischar(rawNames)
    rawNames = {rawNames};
elseif ~iscell(rawNames)
    return;
end
for i = 1:numel(rawNames)
    item = rawNames{i};
    label = '';
    if ischar(item)
        label = strtrim(item);
    elseif iscell(item) && ~isempty(item) && ischar(item{1})
        label = strtrim(item{1});
    end
    if isempty(label)
        continue;
    end
    labelKey = normalize_body_compare_key_r2015(label);
    if isempty(labelKey)
        continue;
    end
    duplicate = false;
    for j = 1:numel(names)
        if strcmp(normalize_body_compare_key_r2015(names{j}), labelKey)
            duplicate = true;
            break;
        end
    end
    if ~duplicate
        names{end + 1, 1} = label; %#ok<AGROW>
    end
end
end

function names = resolve_selected_body_names_r2015(labelSpecs)
names = {};
if nargin < 1 || isempty(labelSpecs) || ~iscell(labelSpecs)
    return;
end
for i = 1:size(labelSpecs, 1)
    row = labelSpecs(i, :);
    if numel(row) == 1 && iscell(row{1})
        row = row{1};
    end
    if isempty(row)
        continue;
    end
    label = row{1};
    if iscell(label) && ~isempty(label)
        label = label{1};
    end
    names = normalize_body_name_list_r2015([names; {label}]);
end
end

function names = resolve_target_body_name_r2015(labelSpecs)
names = {};
if nargin < 1 || isempty(labelSpecs) || ~iscell(labelSpecs)
    return;
end
for i = 1:size(labelSpecs, 1)
    row = labelSpecs(i, :);
    if numel(row) == 1 && iscell(row{1})
        row = row{1};
    end
    if numel(row) < 2
        continue;
    end
    label = row{1};
    marker = lower(strtrim(char(row{2})));
    if strcmp(marker, 'target') || strcmp(marker, 'o')
        names = normalize_body_name_list_r2015({label});
        return;
    end
end
end

function names = resolve_default_comparison_body_names_r2015(selectedNames, targetName)
names = normalize_body_name_list_r2015(selectedNames);
targetNorm = normalize_body_name_list_r2015({targetName});
if isempty(names)
    return;
end
filtered = {};
targetKey = '';
if ~isempty(targetNorm)
    targetKey = normalize_body_compare_key_r2015(targetNorm{1});
end
for i = 1:numel(names)
    if ~strcmp(normalize_body_compare_key_r2015(names{i}), targetKey)
        filtered{end + 1, 1} = names{i}; %#ok<AGROW>
    end
end
names = filtered;
end

function mask = build_component_match_mask_r2015(componentNames, desiredNames)
mask = false(numel(componentNames), 1);
desiredNames = normalize_body_name_list_r2015(desiredNames);
if isempty(desiredNames)
    return;
end
desiredKeys = cell(size(desiredNames));
for j = 1:numel(desiredNames)
    desiredKeys{j} = normalize_body_compare_key_r2015(desiredNames{j});
end
for i = 1:numel(componentNames)
    current = '';
    if ischar(componentNames{i})
        current = strtrim(componentNames{i});
    end
    currentKey = normalize_body_compare_key_r2015(current);
    for j = 1:numel(desiredKeys)
        if strcmp(currentKey, desiredKeys{j})
            mask(i) = true;
            break;
        end
    end
end
end

function keys = build_body_key_list_r2015(names)
keys = cell(size(names));
for i = 1:numel(names)
    current = '';
    if ischar(names{i})
        current = names{i};
    elseif iscell(names{i}) && ~isempty(names{i}) && ischar(names{i}{1})
        current = names{i}{1};
    end
    keys{i} = normalize_body_compare_key_r2015(current);
end
end

function labels = replace_component_labels_r2015(componentNames, preferredNames)
labels = componentNames;
preferredNames = normalize_body_name_list_r2015(preferredNames);
if isempty(preferredNames)
    return;
end
preferredKeys = build_body_key_list_r2015(preferredNames);
for i = 1:numel(labels)
    currentKey = normalize_body_compare_key_r2015(labels{i});
    for j = 1:numel(preferredKeys)
        if strcmp(currentKey, preferredKeys{j})
            labels{i} = preferredNames{j};
            break;
        end
    end
end
end

function names = ensure_key_components_present_r2015(desiredNames, currentNames, totalNames)
names = normalize_body_name_list_r2015(desiredNames);
currentKeys = build_body_key_list_r2015(currentNames);
totalNames = normalize_body_name_list_r2015(totalNames);
totalKeys = build_body_key_list_r2015(totalNames);
for i = 1:numel(totalNames)
    totalKey = totalKeys{i};
    if isempty(totalKey)
        continue;
    end
    if ~isempty(strfind(totalKey, 'tumor')) && ~any(strcmp(currentKeys, totalKey))
        names = normalize_body_name_list_r2015([names; totalNames(i)]);
        currentKeys{end + 1, 1} = totalKey; %#ok<AGROW>
    end
end
end

function label = preferred_body_display_label_r2015(rawLabel, preferredNames)
label = strtrim(rawLabel);
preferredNames = normalize_body_name_list_r2015(preferredNames);
if isempty(preferredNames)
    return;
end
rawKey = normalize_body_compare_key_r2015(label);
preferredKeys = build_body_key_list_r2015(preferredNames);
for i = 1:numel(preferredKeys)
    if strcmp(rawKey, preferredKeys{i})
        label = preferredNames{i};
        return;
    end
end
end

function idx = find_component_row_r2015(componentNames, desiredName)
idx = [];
desiredKey = normalize_body_compare_key_r2015(desiredName);
for i = 1:numel(componentNames)
    current = '';
    if ischar(componentNames{i})
        current = strtrim(componentNames{i});
    end
    if strcmp(normalize_body_compare_key_r2015(current), desiredKey)
        idx = i;
        return;
    end
end
end

function key = normalize_body_compare_key_r2015(value)
if nargin < 1 || isempty(value)
    key = '';
    return;
end
if isnumeric(value)
    value = num2str(value);
elseif ~ischar(value)
    try
        value = char(value);
    catch
        value = '';
    end
end
value = strip_portuguese_diacritics_r2015(strtrim(value));
key = regexprep(lower(value), '[^a-z0-9]+', '');
switch key
    case 'crebro'
        key = 'cerebro';
    case 'olhodto'
        key = 'olhodireito';
    case 'olhoesq'
        key = 'olhoesquerdo';
end
end

function out = strip_portuguese_diacritics_r2015(value)
out = char(value);
replacements = {
    char(193), 'A'; char(192), 'A'; char(195), 'A'; char(194), 'A'; char(196), 'A';
    char(225), 'a'; char(224), 'a'; char(227), 'a'; char(226), 'a'; char(228), 'a';
    char(201), 'E'; char(200), 'E'; char(202), 'E'; char(203), 'E';
    char(233), 'e'; char(232), 'e'; char(234), 'e'; char(235), 'e';
    char(205), 'I'; char(204), 'I'; char(206), 'I'; char(207), 'I';
    char(237), 'i'; char(236), 'i'; char(238), 'i'; char(239), 'i';
    char(211), 'O'; char(210), 'O'; char(213), 'O'; char(212), 'O'; char(214), 'O';
    char(243), 'o'; char(242), 'o'; char(245), 'o'; char(244), 'o'; char(246), 'o';
    char(218), 'U'; char(217), 'U'; char(219), 'U'; char(220), 'U';
    char(250), 'u'; char(249), 'u'; char(251), 'u'; char(252), 'u';
    char(199), 'C'; char(231), 'c'
};
for i = 1:size(replacements, 1)
    out = strrep(out, replacements{i, 1}, replacements{i, 2});
end
end

function out = display_source_type_r2015(label)
out = normalize_source_type_label_r2015(label);
if isempty(out)
    out = 'Unknown source';
end
end

function token = safe_file_token_r2015(label)
token = regexprep(lower(display_source_type_r2015(label)), '[^a-z0-9]+', '_');
token = regexprep(token, '_+', '_');
token = regexprep(token, '^_|_$', '');
if isempty(token)
    token = 'unknown_source';
end
end

function token = safe_label_file_token_r2015(label)
if nargin < 1 || isempty(label)
    token = 'label';
    return;
end
if isnumeric(label)
    label = num2str(label);
elseif ~ischar(label)
    try
        label = char(label);
    catch
        label = '';
    end
end
key = normalize_body_compare_key_r2015(label);
switch key
    case 'olhodireito'
        token = 'olho_direito';
    case 'olhoesquerdo'
        token = 'olho_esquerdo';
    case 'tumorolhodto'
        token = 'tumor_olho_dto';
    case 'tumorouvidoesq'
        token = 'tumor_ouvido_esq';
    case 'cerebro'
        token = 'cerebro';
    otherwise
        text = strip_portuguese_diacritics_r2015(strtrim(label));
        token = regexprep(lower(text), '[^a-z0-9]+', '_');
        token = regexprep(token, '_+', '_');
        token = regexprep(token, '^_|_$', '');
        if isempty(token)
            token = 'label';
        end
end
end

function out = normalize_source_type_label_r2015(label)
if nargin < 1 || isempty(label)
    out = '';
    return;
end
if isnumeric(label)
    label = num2str(label);
elseif ~ischar(label)
    try
        label = char(label);
    catch
        label = '';
    end
end
text = strtrim(label);
text = strip_portuguese_diacritics_r2015(text);
text = regexprep(text, '[_]+', ' ');
text = regexprep(text, '\s+', ' ');
key = regexprep(lower(text), '[^a-z0-9]+', '');
switch key
    case 'linac6mev'
        out = 'LINAC 6MeV';
    case {'cobalt60source', 'cobalt60', 'co60', 'co60source'}
        out = 'Cobalt-60 source';
    otherwise
        out = text;
end
end

function S = load_3d_dose_r2015(path)
fid = fopen(path, 'rt');
if fid < 0
    error('Could not open 3d-dose file.');
end
cleanup = onCleanup(@() fclose(fid));
cols = textscan(fid, '%f%f%f%f%f%f%f%f', 'CommentStyle', '#', ...
    'CollectOutput', true, 'MultipleDelimsAsOne', true, 'Delimiter', {' ', '\t'});
S = cols{1};
if isempty(S) || size(S, 2) < 8
    error('No valid numeric 3D dose rows were found.');
end
end

function archive_existing_pngs_r2015(folderPath)
if nargin < 1 || isempty(folderPath) || ~exist(folderPath, 'dir')
    return;
end
folderPath = char(folderPath);
persistent archivedFolders;
if isempty(archivedFolders)
    archivedFolders = {};
end
if any(strcmpi(archivedFolders, folderPath))
    return;
end
pngFiles = dir(fullfile(folderPath, '*.png'));
if isempty(pngFiles)
    archivedFolders{end + 1, 1} = folderPath; %#ok<AGROW>
    return;
end
archiveRoot = fullfile(folderPath, 'old');
if ~exist(archiveRoot, 'dir')
    mkdir(archiveRoot);
end
archiveDir = fullfile(archiveRoot, datestr(now, 'yyyymmdd_HHMMSS'));
if ~exist(archiveDir, 'dir')
    mkdir(archiveDir);
end
for i = 1:numel(pngFiles)
    src = fullfile(folderPath, pngFiles(i).name);
    dst = fullfile(archiveDir, pngFiles(i).name);
    if exist(dst, 'file')
        [~, base, ext] = fileparts(pngFiles(i).name);
        dst = fullfile(archiveDir, [base '_' datestr(now, 'HHMMSSFFF') ext]);
    end
    movefile(src, dst);
end
archivedFolders{end + 1, 1} = folderPath; %#ok<AGROW>
end

function archive_existing_workbook_outputs_r2015(folderPath)
if nargin < 1 || isempty(folderPath) || ~exist(folderPath, 'dir')
    return;
end
folderPath = char(folderPath);
persistent archivedWorkbookFolders;
if isempty(archivedWorkbookFolders)
    archivedWorkbookFolders = {};
end
if any(strcmpi(archivedWorkbookFolders, folderPath))
    return;
end
patterns = { ...
    'body_totals_by_alpha.csv', ...
    'key_bodies_by_alpha.csv', ...
    'bar_key_bodies_by_alpha*.png', ...
    'angle_ranking*.csv', ...
    'angle_ranking*.png' ...
};
files = [];
for i = 1:numel(patterns)
    matches = dir(fullfile(folderPath, patterns{i}));
    if isempty(matches)
        continue;
    end
    files = [files; matches(:)]; %#ok<AGROW>
end
if isempty(files)
    archivedWorkbookFolders{end + 1, 1} = folderPath; %#ok<AGROW>
    return;
end
archiveRoot = fullfile(folderPath, 'old');
if ~exist(archiveRoot, 'dir')
    mkdir(archiveRoot);
end
archiveDir = fullfile(archiveRoot, datestr(now, 'yyyymmdd_HHMMSS'));
if ~exist(archiveDir, 'dir')
    mkdir(archiveDir);
end
seen = {};
for i = 1:numel(files)
    name = files(i).name;
    if any(strcmpi(seen, name))
        continue;
    end
    seen{end + 1, 1} = name; %#ok<AGROW>
    src = fullfile(folderPath, name);
    if ~exist(src, 'file')
        continue;
    end
    dst = fullfile(archiveDir, name);
    if exist(dst, 'file')
        [~, base, ext] = fileparts(name);
        dst = fullfile(archiveDir, [base '_' datestr(now, 'HHMMSSFFF') ext]);
    end
    movefile(src, dst);
end
archivedWorkbookFolders{end + 1, 1} = folderPath; %#ok<AGROW>
end

function write_geometry_labels_csv_r2015(folderPath, labelSpecs)
if nargin < 2 || isempty(folderPath) || isempty(labelSpecs)
    return;
end
csvPath = fullfile(folderPath, 'geometry_labels_used.csv');
fid = fopen(csvPath, 'wt');
if fid < 0
    return;
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'label,role,x_cm,y_cm,z_cm\n');
for idx = 1:size(labelSpecs, 1)
    row = labelSpecs(idx, :);
    if numel(row) == 1 && iscell(row{1})
        row = row{1};
    end
    if numel(row) < 5
        continue;
    end
    fprintf(fid, '"%s","%s",%.12g,%.12g,%.12g\n', ...
        csv_escape_r2015(row{1}), csv_escape_r2015(row{2}), row{3}, row{4}, row{5});
end
end

function textOut = csv_escape_r2015(value)
textOut = strrep(char(value), '"', '""');
end

function process_grouped_3d_dose_folder_r2015(groupDir, xT, yT, zT, labelSpecs, geometrySlicePoints, ced)
files = dir(fullfile(groupDir, '3d-dose_case*.dat'));
if isempty(files)
    files = dir(fullfile(groupDir, '3d-dose*.dat'));
end
if isempty(files)
    return;
end
[~, order] = sort({files.name});
files = files(order);

d = 0.5;
totalDoseUnitLabel = 'Dose total (eV/g)';

for k = 1:numel(files)
    dosePath = fullfile(groupDir, files(k).name);
    Scur = load_3d_dose_r2015(dosePath);
    if k == 1
        x = Scur(:,1);
        y = Scur(:,2);
        z = Scur(:,3);
        ix = round(Scur(:,6));
        iy = round(Scur(:,7));
        iz = round(Scur(:,8));
        doseT = zeros(size(x));
        uTotal2 = zeros(size(x));
    else
        if size(Scur, 1) ~= numel(x)
            error('Grid size mismatch in "%s": expected %d voxel rows (from first file), got %d. All grouped 3d-dose files must share the same grid.', ...
                files(k).name, numel(x), size(Scur, 1));
        end
    end
    doseT = doseT + Scur(:,4);
    if size(Scur, 2) >= 5
        uTotal2 = uTotal2 + (Scur(:,5) .^ 2);
    end
end
uTotal = sqrt(uTotal2);
nx = max(ix);
ny = max(iy);
nz = max(iz);
D = nan(nx, ny, nz);
U = nan(nx, ny, nz);
lin = sub2ind([nx, ny, nz], ix, iy, iz);
D(lin) = doseT;
U(lin) = uTotal;
xVec = accumarray(ix, x, [nx 1], @mean);
yVec = accumarray(iy, y, [ny 1], @mean);
zVec = accumarray(iz, z, [nz 1], @mean);
[~, ixt] = min(abs(xVec - xT));
[~, iyt] = min(abs(yVec - yT));
[~, izt] = min(abs(zVec - zT));

archive_existing_pngs_r2015(groupDir);
write_geometry_labels_csv_r2015(groupDir, labelSpecs);

raw_ix = find((abs(y - yT) <= d) .* (abs(z - zT) <= d));
raw_iy = find((abs(x - xT) <= d) .* (abs(z - zT) <= d));
raw_iz = find((abs(x - xT) <= d) .* (abs(y - yT) <= d));

plot_slab_profile_r2015(x(raw_ix), doseT(raw_ix), uTotal(raw_ix), 'x (cm)', 'Perfil de dose total ao longo de X', ...
    fullfile(groupDir, '3d-dose_total_profile_x.png'), fullfile(groupDir, '3d-dose_total_profile_x_slab.csv'), labelSpecs, 'x');
plot_slab_profile_r2015(y(raw_iy), doseT(raw_iy), uTotal(raw_iy), 'y (cm)', 'Perfil de dose total ao longo de Y', ...
    fullfile(groupDir, '3d-dose_total_profile_y.png'), fullfile(groupDir, '3d-dose_total_profile_y_slab.csv'), labelSpecs, 'y');
plot_slab_profile_r2015(z(raw_iz), doseT(raw_iz), uTotal(raw_iz), 'z (cm)', 'Perfil de dose total ao longo de Z', ...
    fullfile(groupDir, '3d-dose_total_profile_z.png'), fullfile(groupDir, '3d-dose_total_profile_z_slab.csv'), labelSpecs, 'z');

plot_central_profile_r2015(xVec, squeeze(D(:, iyt, izt)), squeeze(U(:, iyt, izt)), 'x (cm)', 'Perfil de dose total na linha central ao longo de X', ...
    fullfile(groupDir, '3d-dose_total_profile_x_central.png'), fullfile(groupDir, '3d-dose_total_profile_x_central.csv'), labelSpecs, 'x');
plot_central_profile_r2015(yVec, squeeze(D(ixt, :, izt))', squeeze(U(ixt, :, izt))', 'y (cm)', 'Perfil de dose total na linha central ao longo de Y', ...
    fullfile(groupDir, '3d-dose_total_profile_y_central.png'), fullfile(groupDir, '3d-dose_total_profile_y_central.csv'), labelSpecs, 'y');
plot_central_profile_r2015(zVec, squeeze(D(ixt, iyt, :)), squeeze(U(ixt, iyt, :)), 'z (cm)', 'Perfil de dose total na linha central ao longo de Z', ...
    fullfile(groupDir, '3d-dose_total_profile_z_central.png'), fullfile(groupDir, '3d-dose_total_profile_z_central.csv'), labelSpecs, 'z');

slab_xy = find(abs(z - zT) <= 0.5 & isfinite(doseT) & doseT > 1e-10);
slab_xz = find(abs(y - yT) <= 0.3 & isfinite(doseT) & doseT > 1e-10);
slab_yz = find(abs(x - xT) <= 0.3 & isfinite(doseT) & doseT > 1e-10);
plot_geometry_slice_r2015(x(slab_xy), y(slab_xy), doseT(slab_xy), labelSpecs, 'xy', 'x (cm)', 'y (cm)', ...
    ['Distribui' ced 'o total no plano XY (z = ', num2str(zT), ' cm)'], fullfile(groupDir, '3d-dose_total_xy.png'), totalDoseUnitLabel, geometrySlicePoints.xy);
plot_geometry_slice_r2015(x(slab_xz), z(slab_xz), doseT(slab_xz), labelSpecs, 'xz', 'x (cm)', 'z (cm)', ...
    ['Distribui' ced 'o total no plano XZ (y = ', num2str(yT), ' cm)'], fullfile(groupDir, '3d-dose_total_xz.png'), totalDoseUnitLabel, geometrySlicePoints.xz);
plot_geometry_slice_r2015(y(slab_yz), z(slab_yz), doseT(slab_yz), labelSpecs, 'yz', 'y (cm)', 'z (cm)', ...
    ['Distribui' ced 'o total no plano YZ (x = ', num2str(xT), ' cm)'], fullfile(groupDir, '3d-dose_total_yz.png'), totalDoseUnitLabel, geometrySlicePoints.yz);
plot_plane_r2015(xVec, yVec, squeeze(D(:, :, izt))', labelSpecs, 'xy', 'x (cm)', 'y (cm)', ...
    ['Distribui' ced 'o total na fatia exata XY (z = ', num2str(zT), ' cm)'], fullfile(groupDir, '3d-dose_total_plane_xy.png'), totalDoseUnitLabel);
plot_plane_r2015(xVec, zVec, squeeze(D(:, iyt, :))', labelSpecs, 'xz', 'x (cm)', 'z (cm)', ...
    ['Distribui' ced 'o total na fatia exata XZ (y = ', num2str(yT), ' cm)'], fullfile(groupDir, '3d-dose_total_plane_xz.png'), totalDoseUnitLabel);
plot_plane_r2015(yVec, zVec, squeeze(D(ixt, :, :))', labelSpecs, 'yz', 'y (cm)', 'z (cm)', ...
    ['Distribui' ced 'o total na fatia exata YZ (x = ', num2str(xT), ' cm)'], fullfile(groupDir, '3d-dose_total_plane_yz.png'), totalDoseUnitLabel);

plot_uncertainty_plane_r2015(xVec, yVec, squeeze(D(:, :, izt))', squeeze(U(:, :, izt))', labelSpecs, 'xy', ...
    'x (cm)', 'y (cm)', 'Incerteza relativa 3sigma (%) no plano XY', fullfile(groupDir, '3d-dose_total_uncertainty_xy_3sigma_pct.png'));
plot_uncertainty_plane_r2015(xVec, zVec, squeeze(D(:, iyt, :))', squeeze(U(:, iyt, :))', labelSpecs, 'xz', ...
    'x (cm)', 'z (cm)', 'Incerteza relativa 3sigma (%) no plano XZ', fullfile(groupDir, '3d-dose_total_uncertainty_xz_3sigma_pct.png'));
plot_uncertainty_plane_r2015(yVec, zVec, squeeze(D(ixt, :, :))', squeeze(U(ixt, :, :))', labelSpecs, 'yz', ...
    'y (cm)', 'z (cm)', 'Incerteza relativa 3sigma (%) no plano YZ', fullfile(groupDir, '3d-dose_total_uncertainty_yz_3sigma_pct.png'));
end

function process_single_3d_dose_r2015(dose3dPath, outDir, xT, yT, zT, labelSpecs, geometrySlicePoints, prefix)
if nargin < 8
    prefix = '';
end

[~, stem, ~] = fileparts(dose3dPath);
S = load_3d_dose_r2015(dose3dPath);
x = S(:, 1);
y = S(:, 2);
z = S(:, 3);
dose = S(:, 4);
u3sig = S(:, 5);
ix = round(S(:, 6));
iy = round(S(:, 7));
iz = round(S(:, 8));
nx = max(ix);
ny = max(iy);
nz = max(iz);

D = nan(nx, ny, nz);
U = nan(nx, ny, nz);
lin = sub2ind([nx, ny, nz], ix, iy, iz);
D(lin) = dose;
U(lin) = u3sig;

xVec = accumarray(ix, x, [nx 1], @mean);
yVec = accumarray(iy, y, [ny 1], @mean);
zVec = accumarray(iz, z, [nz 1], @mean);

[~, ixt] = min(abs(xVec - xT));
[~, iyt] = min(abs(yVec - yT));
[~, izt] = min(abs(zVec - zT));

ced = [char(231) char(227)];

filePrefix = prefix;
if isempty(filePrefix)
    if ~strcmpi(stem, '3d-dose')
        filePrefix = [stem '_'];
    end
end

archive_existing_pngs_r2015(outDir);
write_geometry_labels_csv_r2015(outDir, labelSpecs);

plotStem = stem;
d = 0.5;
doseUnitLabel = 'Dose (eV/g)';
doseT = dose;
raw_ix = find((abs(y - yT) <= d) .* (abs(z - zT) <= d));
raw_iy = find((abs(x - xT) <= d) .* (abs(z - zT) <= d));
raw_iz = find((abs(x - xT) <= d) .* (abs(y - yT) <= d));

plot_slab_profile_r2015(x(raw_ix), doseT(raw_ix), u3sig(raw_ix), 'x (cm)', 'Perfil de dose ao longo de X', ...
    fullfile(outDir, [plotStem '_profile_x.png']), fullfile(outDir, [plotStem '_profile_x_slab.csv']), labelSpecs, 'x');
plot_slab_profile_r2015(y(raw_iy), doseT(raw_iy), u3sig(raw_iy), 'y (cm)', 'Perfil de dose ao longo de Y', ...
    fullfile(outDir, [plotStem '_profile_y.png']), fullfile(outDir, [plotStem '_profile_y_slab.csv']), labelSpecs, 'y');
plot_slab_profile_r2015(z(raw_iz), doseT(raw_iz), u3sig(raw_iz), 'z (cm)', 'Perfil de dose ao longo de Z', ...
    fullfile(outDir, [plotStem '_profile_z.png']), fullfile(outDir, [plotStem '_profile_z_slab.csv']), labelSpecs, 'z');

plot_central_profile_r2015(xVec, squeeze(D(:, iyt, izt)), squeeze(U(:, iyt, izt)), 'x (cm)', 'Perfil de dose na linha central ao longo de X', ...
    fullfile(outDir, [plotStem '_profile_x_central.png']), fullfile(outDir, [plotStem '_profile_x_central.csv']), labelSpecs, 'x');
plot_central_profile_r2015(yVec, squeeze(D(ixt, :, izt))', squeeze(U(ixt, :, izt))', 'y (cm)', 'Perfil de dose na linha central ao longo de Y', ...
    fullfile(outDir, [plotStem '_profile_y_central.png']), fullfile(outDir, [plotStem '_profile_y_central.csv']), labelSpecs, 'y');
plot_central_profile_r2015(zVec, squeeze(D(ixt, iyt, :)), squeeze(U(ixt, iyt, :)), 'z (cm)', 'Perfil de dose na linha central ao longo de Z', ...
    fullfile(outDir, [plotStem '_profile_z_central.png']), fullfile(outDir, [plotStem '_profile_z_central.csv']), labelSpecs, 'z');

slab_xy = find(abs(z - zT) <= 0.5 & isfinite(doseT) & doseT > 1e-10);
slab_xz = find(abs(y - yT) <= 0.3 & isfinite(doseT) & doseT > 1e-10);
slab_yz = find(abs(x - xT) <= 0.3 & isfinite(doseT) & doseT > 1e-10);
plot_geometry_slice_r2015(x(slab_xy), y(slab_xy), doseT(slab_xy), labelSpecs, 'xy', 'x (cm)', 'y (cm)', ...
    ['Distribui' ced 'o de dose no plano XY (z = ', num2str(zT), ' cm)'], fullfile(outDir, [plotStem '_xy.png']), doseUnitLabel, geometrySlicePoints.xy);
plot_geometry_slice_r2015(x(slab_xz), z(slab_xz), doseT(slab_xz), labelSpecs, 'xz', 'x (cm)', 'z (cm)', ...
    ['Distribui' ced 'o de dose no plano XZ (y = ', num2str(yT), ' cm)'], fullfile(outDir, [plotStem '_xz.png']), doseUnitLabel, geometrySlicePoints.xz);
plot_geometry_slice_r2015(y(slab_yz), z(slab_yz), doseT(slab_yz), labelSpecs, 'yz', 'y (cm)', 'z (cm)', ...
    ['Distribui' ced 'o de dose no plano YZ (x = ', num2str(xT), ' cm)'], fullfile(outDir, [plotStem '_yz.png']), doseUnitLabel, geometrySlicePoints.yz);
plot_plane_r2015(xVec, yVec, squeeze(D(:, :, izt))', labelSpecs, 'xy', 'x (cm)', 'y (cm)', ...
    ['Distribui' ced 'o de dose na fatia exata XY (z = ', num2str(zT), ' cm)'], fullfile(outDir, [plotStem '_plane_xy.png']), doseUnitLabel);
plot_plane_r2015(xVec, zVec, squeeze(D(:, iyt, :))', labelSpecs, 'xz', 'x (cm)', 'z (cm)', ...
    ['Distribui' ced 'o de dose na fatia exata XZ (y = ', num2str(yT), ' cm)'], fullfile(outDir, [plotStem '_plane_xz.png']), doseUnitLabel);
plot_plane_r2015(yVec, zVec, squeeze(D(ixt, :, :))', labelSpecs, 'yz', 'y (cm)', 'z (cm)', ...
    ['Distribui' ced 'o de dose na fatia exata YZ (x = ', num2str(xT), ' cm)'], fullfile(outDir, [plotStem '_plane_yz.png']), doseUnitLabel);

plot_uncertainty_plane_r2015(xVec, yVec, squeeze(D(:, :, izt))', squeeze(U(:, :, izt))', labelSpecs, 'xy', ...
    'x (cm)', 'y (cm)', 'Incerteza relativa 3sigma (%) no plano XY', fullfile(outDir, [plotStem '_uncertainty_xy_3sigma_pct.png']));
plot_uncertainty_plane_r2015(xVec, zVec, squeeze(D(:, iyt, :))', squeeze(U(:, iyt, :))', labelSpecs, 'xz', ...
    'x (cm)', 'z (cm)', 'Incerteza relativa 3sigma (%) no plano XZ', fullfile(outDir, [plotStem '_uncertainty_xz_3sigma_pct.png']));
plot_uncertainty_plane_r2015(yVec, zVec, squeeze(D(ixt, :, :))', squeeze(U(ixt, :, :))', labelSpecs, 'yz', ...
    'y (cm)', 'z (cm)', 'Incerteza relativa 3sigma (%) no plano YZ', fullfile(outDir, [plotStem '_uncertainty_yz_3sigma_pct.png']));
end

function files = collect_3d_dose_files_r2015(rootDir)
paths = regexp(genpath(rootDir), pathsep, 'split');
files = {};
for i = 1:numel(paths)
    currentDir = paths{i};
    if isempty(currentDir)
        continue;
    end
    lowerDir = lower(currentDir);
    if ~isempty(strfind(lowerDir, [filesep 'previous_runs'])) || ...
       ~isempty(strfind(lowerDir, [filesep 'dmps'])) || ...
       ~isempty(strfind(lowerDir, [filesep '3d-dose_group'])) || ...
       ~isempty(strfind(lowerDir, '_3d_dose_header_backup_'))
        continue;
    end
    [~, baseName] = fileparts(currentDir);
    if isempty(strfind(lower(baseName), 'case'))
        continue;
    end
    matches = dir(fullfile(currentDir, '3d-dose*.dat'));
    for j = 1:numel(matches)
        if ~matches(j).isdir
            files{end + 1, 1} = fullfile(currentDir, matches(j).name); %#ok<AGROW>
        end
    end
end
end

function plot_plane_r2015(aVec, bVec, M, labelSpecs, planeMode, xlab, ylab, ttl, outPath, cbLabel)
fig = figure('Color', 'w');
imagesc(aVec, bVec, M);
axis xy equal tight;
cb = colorbar;
ylabel(cb, cbLabel);
hold on;
[markerHandles, markerNames] = plot_selected_geometry_labels_r2015(labelSpecs, planeMode);
xlabel(xlab);
ylabel(ylab);
title(ttl);
grid on;
if ~isempty(markerHandles)
    legend(markerHandles, markerNames, 'Location', 'northeastoutside');
end
saveas(fig, outPath);
close(fig);
end

function plot_geometry_slice_r2015(aVals, bVals, doseVals, labelSpecs, planeMode, xlab, ylab, ttl, outPath, cbLabel, backgroundPoints)
if nargin < 11
    backgroundPoints = zeros(0,2);
end
validMask = isfinite(aVals) & isfinite(bVals) & isfinite(doseVals);
aVals = aVals(validMask);
bVals = bVals(validMask);
doseVals = doseVals(validMask);
if isempty(aVals) || isempty(bVals) || isempty(doseVals)
    return;
end
fig = figure('Color', 'w');
% Draw geometry outline first so dose scatter renders on top.
if ~isempty(backgroundPoints) && size(backgroundPoints, 2) >= 2
    scatter(backgroundPoints(:,1), backgroundPoints(:,2), 4, [0.82 0.82 0.82], '.', 'HandleVisibility', 'off');
    hold on;
end
scatter(aVals, bVals, 20, doseVals, 'filled');
axis equal tight;
cb = colorbar;
ylabel(cb, cbLabel);
hold on;
[markerHandles, markerNames] = plot_selected_geometry_labels_r2015(labelSpecs, planeMode);
xlabel(xlab);
ylabel(ylab);
title(ttl);
grid on;
if ~isempty(markerHandles)
    legend(markerHandles, markerNames, 'Location', 'northeastoutside');
end
saveas(fig, outPath);
close(fig);
end

function plot_uncertainty_plane_r2015(aVec, bVec, dosePlane, uncPlane, labelSpecs, planeMode, xlab, ylab, ttl, outPath)
relUncPct = 100 * uncPlane ./ dosePlane;
validDose = dosePlane(isfinite(dosePlane));
if isempty(validDose)
    maxDose = NaN;
else
    maxDose = max(validDose);
end
doseMask = ~isfinite(dosePlane) | dosePlane <= 0;
if isfinite(maxDose) && maxDose > 0
    doseMask = doseMask | (dosePlane < 0.01 * maxDose);
end
relUncPct(doseMask) = NaN;
relUncPct(relUncPct > 100) = 100;
fig = figure('Color', 'w');
imagesc(aVec, bVec, relUncPct);
axis xy equal tight;
cb = colorbar;
ylabel(cb, 'Incerteza relativa 3sigma (%)');
hold on;
[markerHandles, markerNames] = plot_selected_geometry_labels_r2015(labelSpecs, planeMode);
xlabel(xlab);
ylabel(ylab);
title(ttl);
grid on;
if ~isempty(markerHandles)
    legend(markerHandles, markerNames, 'Location', 'northeastoutside');
end
saveas(fig, outPath);
close(fig);
end

function selectedPaths = choose_path_subset_r2015(paths, dialogTitle, displayRoot)
if isempty(paths)
    selectedPaths = paths;
    return;
end
if nargin < 2 || isempty(dialogTitle)
    dialogTitle = 'Select files';
end
if nargin < 3
    displayRoot = '';
end
shortNames = cell(numel(paths), 1);
for i = 1:numel(paths)
    rel = paths{i};
    if ~isempty(displayRoot)
        rel = strrep(paths{i}, displayRoot, '');
        if isempty(rel)
            rel = paths{i};
        end
    end
    shortNames{i} = rel;
end
[sel, ok] = listdlg( ...
    'ListString', shortNames, ...
    'SelectionMode', 'multiple', ...
    'Name', dialogTitle, ...
    'ListSize', [620, 400], ...
    'PromptString', 'Select files to process:');
if ok && ~isempty(sel)
    selectedPaths = paths(sel);
else
    selectedPaths = {};
end
end

function name = short_name_r2015(pathValue)
[~, name, ext] = fileparts(pathValue);
name = [name ext];
if isempty(name)
    name = pathValue;
end
end

function plot_slab_profile_r2015(axisCoords, doseVals, uncVals, axisLabel, plotTitle, outPath, csvPath, labelSpecs, axisMode)
if isempty(axisCoords) || isempty(doseVals)
    return;
end
validMask = isfinite(axisCoords) & isfinite(doseVals) & isfinite(uncVals);
axisCoords = axisCoords(validMask);
doseVals = doseVals(validMask);
uncVals = uncVals(validMask);
if isempty(axisCoords) || isempty(doseVals)
    return;
end
roundedAxis = round(axisCoords * 1e6) / 1e6;
[uniqueAxis, ~, groupIdx] = unique(roundedAxis);
meanDose = accumarray(groupIdx, doseVals, [], @mean);
stdDose = accumarray(groupIdx, doseVals, [], @std);
sampleCount = accumarray(groupIdx, 1, [], @sum);
meanUnc = accumarray(groupIdx, uncVals, [], @mean);
[uniqueAxis, order] = sort(uniqueAxis);
meanDose = meanDose(order);
stdDose = stdDose(order);
sampleCount = sampleCount(order);
meanUnc = meanUnc(order);

fig = figure('Color', 'w');
hSamples = plot(axisCoords, doseVals, '.', 'Color', [0.45 0.45 0.45], 'MarkerSize', 8);
hold on;
hMean = plot(uniqueAxis, meanDose, 'k-', 'LineWidth', 1.5);
plot(uniqueAxis, meanDose, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 4);
xlabel(axisLabel);
ylabel('Dose (eV/g)');
title(plotTitle);
yLimits = ylim;
[markerHandles, markerNames] = plot_profile_markers_r2015(labelSpecs, axisMode, yLimits(1), yLimits(2));
legendHandles = [hSamples; hMean];
legendNames = {'amostras perto do alvo', ['m' char(233) 'dia por corte']};
if ~isempty(markerHandles)
    legendHandles = [legendHandles; markerHandles(:)];
    legendNames = [legendNames, markerNames];
end
legend(legendHandles, legendNames, 'Location', 'best');
grid on;
hold off;
saveas(fig, outPath);
close(fig);
write_slab_profile_csv_r2015(csvPath, uniqueAxis, meanDose, stdDose, sampleCount, meanUnc);
end

function plot_central_profile_r2015(axisCoords, doseVals, uncVals, axisLabel, plotTitle, outPath, csvPath, labelSpecs, axisMode)
validMask = isfinite(axisCoords) & isfinite(doseVals);
axisCoords = axisCoords(validMask);
doseVals = doseVals(validMask);
uncVals = uncVals(validMask);
if isempty(axisCoords) || isempty(doseVals)
    return;
end
[axisCoords, order] = sort(axisCoords);
doseVals = doseVals(order);
uncVals = uncVals(order);
fig = figure('Color', 'w');
hCentral = plot(axisCoords, doseVals, 'k-', 'LineWidth', 1.6);
hold on;
plot(axisCoords, doseVals, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 4);
xlabel(axisLabel);
ylabel('Dose (eV/g)');
title(plotTitle);
yLimits = ylim;
[markerHandles, markerNames] = plot_profile_markers_r2015(labelSpecs, axisMode, yLimits(1), yLimits(2));
legendHandles = hCentral;
legendNames = {'linha central'};
if ~isempty(markerHandles)
    legendHandles = [legendHandles; markerHandles(:)];
    legendNames = [legendNames, markerNames];
end
legend(legendHandles, legendNames, 'Location', 'best');
grid on;
hold off;
saveas(fig, outPath);
close(fig);
write_central_profile_csv_r2015(csvPath, axisCoords, doseVals, uncVals);
end

function [handles, names] = plot_profile_markers_r2015(labelSpecs, axisMode, yMin, yMax)
handles = [];
names = {};
if isempty(labelSpecs)
    return;
end
palette = lines(max(1, size(labelSpecs, 1) - 1));
bodyCounter = 0;
for idx = 1:size(labelSpecs, 1)
    row = labelSpecs(idx, :);
    if numel(row) == 1 && iscell(row{1})
        row = row{1};
    end
    if numel(row) < 5
        continue;
    end
    label = char(row{1});
    markerMode = lower(strtrim(char(row{2})));
    coordVal = coordinate_for_axis_r2015(row{3}, row{4}, row{5}, axisMode);
    if ~isfinite(coordVal)
        continue;
    end
    if strcmp(markerMode, 'target') || strcmp(markerMode, 'o')
        h = draw_vertical_marker_r2015(coordVal, yMin, yMax, [0 0 0], ':', 1.2);
    else
        bodyCounter = bodyCounter + 1;
        clr = palette(1 + mod(bodyCounter - 1, size(palette, 1)), :);
        h = draw_vertical_marker_r2015(coordVal, yMin, yMax, clr, '--', 0.9);
    end
    handles(end + 1, 1) = h; %#ok<AGROW>
    names{end + 1} = label; %#ok<AGROW>
end
end

function h = draw_vertical_marker_r2015(xPos, yMin, yMax, colorValue, lineStyle, lineWidthValue)
h = line([xPos xPos], [yMin yMax], 'Color', colorValue, 'LineStyle', lineStyle, 'LineWidth', lineWidthValue);
end

function coordVal = coordinate_for_axis_r2015(xVal, yVal, zVal, axisMode)
coordVal = NaN;
mode = lower(strtrim(axisMode));
if strcmp(mode, 'x')
    coordVal = xVal;
elseif strcmp(mode, 'y')
    coordVal = yVal;
elseif strcmp(mode, 'z')
    coordVal = zVal;
end
end

function write_slab_profile_csv_r2015(csvPath, coords, meanDose, stdDose, sampleCount, meanUnc)
if isempty(csvPath)
    return;
end
relPct = NaN(size(meanDose));
validMask = abs(meanDose) > 0;
relPct(validMask) = 100 * abs(meanUnc(validMask) ./ meanDose(validMask));
fid = fopen(csvPath, 'wt');
if fid < 0
    return;
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'coordinate_cm,mean_dose_ev_g,std_dose_ev_g,n_voxels,mean_3sigma_unc_ev_g,relative_3sigma_pct\n');
for idx = 1:numel(coords)
    fprintf(fid, '%.12g,%.12g,%.12g,%d,%.12g,%.12g\n', coords(idx), meanDose(idx), stdDose(idx), sampleCount(idx), meanUnc(idx), relPct(idx));
end
end

function write_central_profile_csv_r2015(csvPath, coords, doseVals, uncVals)
if isempty(csvPath)
    return;
end
relPct = NaN(size(doseVals));
validMask = abs(doseVals) > 0;
relPct(validMask) = 100 * abs(uncVals(validMask) ./ doseVals(validMask));
fid = fopen(csvPath, 'wt');
if fid < 0
    return;
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'coordinate_cm,dose_ev_g,uncertainty_3sigma_ev_g,relative_3sigma_pct\n');
for idx = 1:numel(coords)
    fprintf(fid, '%.12g,%.12g,%.12g,%.12g\n', coords(idx), doseVals(idx), uncVals(idx), relPct(idx));
end
end

function [handles, names] = plot_selected_geometry_labels_r2015(labelSpecs, planeMode)
handles = [];
names = {};
if isempty(labelSpecs)
    return;
end
palette = lines(max(1, size(labelSpecs, 1) - 1));
bodyCounter = 0;
for idx = 1:size(labelSpecs, 1)
    row = labelSpecs(idx, :);
    if numel(row) == 1 && iscell(row{1})
        row = row{1};
    end
    if numel(row) < 5
        continue;
    end
    label = row{1};
    marker = row{2};
    xVal = row{3};
    yVal = row{4};
    zVal = row{5};
    [aVal, bVal] = project_geometry_label_r2015(xVal, yVal, zVal, planeMode);
    if ~isfinite(aVal) || ~isfinite(bVal)
        continue;
    end
    markerMode = lower(strtrim(char(marker)));
    if strcmp(markerMode, 'target') || strcmp(markerMode, 'o')
        h = plot(aVal, bVal, 'o', 'MarkerSize', 9, 'LineWidth', 1.6, 'MarkerEdgeColor', 'k', 'MarkerFaceColor', 'w', 'Color', 'k');
    else
        bodyCounter = bodyCounter + 1;
        clr = palette(1 + mod(bodyCounter - 1, size(palette, 1)), :);
        h = plot(aVal, bVal, 'o', 'MarkerSize', 8, 'LineWidth', 1.4, 'MarkerEdgeColor', 'k', 'MarkerFaceColor', clr, 'Color', clr);
    end
    handles = [handles h]; %#ok<AGROW>
    names{end + 1, 1} = label; %#ok<AGROW>
end
end

function [aVal, bVal] = project_geometry_label_r2015(xVal, yVal, zVal, planeMode)
aVal = NaN;
bVal = NaN;
mode = lower(strtrim(planeMode));
if strcmp(mode, 'xy')
    aVal = xVal;
    bVal = yVal;
elseif strcmp(mode, 'xz')
    aVal = xVal;
    bVal = zVal;
elseif strcmp(mode, 'yz')
    aVal = yVal;
    bVal = zVal;
end
end
